include cgen.inc
global  _sub_3564
global  ncsv, cret, indir
global  _word_AFF8
global  _codeFrag
global  amul
global  _sub_2D09
global  _fputchar
psect   text
_sub_3564:
global csv
call csv
push hl
push hl
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
ld      hl,0
ld      (_word_AFF8),hl
ld      (ix+-1),l
jp      l14
l11:
push    iy
pop     de
ld      a,(ix+-1)
ld      l,a
rla
sbc     a,a
ld      h,a
add     hl,de
inc     hl
inc     hl
inc     hl
ld      l,(hl)
ld      h,0
ld      de,10
call    amul
ld      de,_codeFrag
add     hl,de
ex      de,hl
push    ix
pop     hl
dec     hl
dec     hl
dec     hl
ld      (hl),e
inc     hl
ld      (hl),d
ld      hl,6
add     hl,de
ld      a,(hl)
inc     hl
or      (hl)
jp      z,l13
ld      l,(ix+-1)
push    hl
ld      e,(ix+-3)
ld      d,(ix+-2)
ld      hl,6
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
push    iy
call    _sub_2D09
pop     bc
pop     bc
ld      hl,10
ex      (sp),hl
call    _fputchar
pop     bc
l13:
inc     (ix+-1)
l14:
ld      e,(iy+1)
ld      d,0
ld      l,(ix+-1)
ld      h,d
or      a
sbc     hl,de
jp      nz,l11
jp      cret
global  _sub_35E6
global  _dopetab
global  _word_AFFB
global  _prPush
global  _prPop
_sub_35E6:
global csv
call csv
push hl
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
ld      de,_dopetab
ld      l,(iy+0)
ld      h,0
add     hl,hl
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
bit     1,b
jp      z,l17
ld      hl,(_word_AFFB)
inc     hl
ld      (_word_AFFB),hl
l17:
ld      de,_dopetab
ld      l,(iy+0)
ld      h,0
add     hl,hl
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      a,c
and     12
ld      l,a
xor     a
ld      h,a
ld      (ix+-2),l
ld      (ix+-1),h
ld      de,8
ld      h,(ix+-1)
or      a
sbc     hl,de
jp      nz,l18
bit     0,(iy+2)
jp      z,l19
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
call    _sub_35E6
ld      l,(iy+27)
ld      h,(iy+28)
ex      (sp),hl
call    _sub_35E6
pop     bc
jp      l18
l19:
ld      l,(iy+27)
ld      h,(iy+28)
push    hl
call    _sub_35E6
pop     bc
bit     1,(iy+2)
jp      z,l21
ld      e,(iy+27)
ld      d,(iy+28)
ld      l,e
ld      h,d
inc     hl
ld      l,(hl)
ld      h,0
add     hl,de
ld      de,14
add     hl,de
ld      l,(hl)
push    hl
call    _prPush
pop     bc
l21:
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
call    _sub_35E6
pop     bc
l18:

;ld      de,4
;ld      l,(ix+-2)
;ld      h,(ix+-1)
;or      a
;sbc     hl,de
ld	a,(ix+-2)
cp	4

jp      nz,l22
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
call    _sub_35E6
pop     bc
l22:
bit     1,(iy+2)
jp      z,l23
ld      e,(iy+27)
ld      d,(iy+28)
ld      l,e
ld      h,d
inc     hl
ld      l,(hl)
ld      h,0
add     hl,de
ld      de,14
add     hl,de
ld      l,(hl)
push    hl
call    _prPop
pop     bc
l23:
push    iy
call    _sub_3564
pop     bc
ld      de,_dopetab
ld      l,(iy+0)
ld      h,0
add     hl,hl
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
bit     1,b
jp      z,cret
ld      hl,(_word_AFFB)
dec     hl
ld      (_word_AFFB),hl
jp      cret
global  _freeNode
global  _byte_B013
global  _free
global  _nodeFreeList
_freeNode:
global csv
call csv
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
ld      a,1
ld      (_byte_B013),a
ld      a,(iy+0)
cp      68
jp      nz,l26
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
call    _free
l26:
ld      hl,(_nodeFreeList)
ld      (iy+23),l
ld      (iy+24),h
ld      (_nodeFreeList),iy
jp      cret
global  _allocNode
global  _blkclr
global  _allocMem
_allocNode:
global csv
call csv
ld      a,1
ld      (_byte_B013),a
ld      hl,(_nodeFreeList)
ld      a,l
or      h
jp      z,l28
ld      iy,(_nodeFreeList)
ld      l,(iy+23)
ld      h,(iy+24)
ld      (_nodeFreeList),hl
ld      hl,29
push    hl
push    iy
call    _blkclr
pop     bc
pop     bc
jp      l29
l28:
ld      hl,29
push    hl
call    _allocMem
pop     bc
push    hl
pop     iy
l29:
;push    iy
;pop     hl
;jp      cret
jp	pushIYpopHLcret
global  _releaseNodeFreeList
_releaseNodeFreeList:
global csv
call csv
ld      hl,(_nodeFreeList)
ld      a,l
or      h
jp      nz,l32
;ld      l,0
;jp      cret
jp	ldL0cret
l33:
ld      l,(iy+23)
ld      h,(iy+24)
ld      (_nodeFreeList),hl
push    iy
call    _free
pop     bc
l32:
ld      iy,(_nodeFreeList)
push    iy
pop     hl
ld      a,l
or      h
jp      nz,l33
;ld      l,1
;jp      cret
jp	ldL1cret
global  _sub_377A
_sub_377A:
global csv
call csv
call    _allocNode
push    hl
pop     iy
ld      l,(ix+6)
ld      h,(ix+7)
push    iy
pop     de
push    hl
ld      bc,29
ldir
pop     hl
ld      de,_dopetab
ld      l,(iy+0)
ld      h,0
add     hl,hl
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      a,c
and     12
ld      l,a
xor     a
ld      h,a
ld      a,l
or      h
jp      z,l36
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
call    _sub_377A
pop     bc
ld      (iy+25),l
ld      (iy+26),h
l36:
ld      de,_dopetab
ld      l,(iy+0)
ld      h,0
add     hl,hl
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      a,c
and     12

;ld      l,a
;xor     a
;ld      h,a
;ld      de,8
;or      a
;sbc     hl,de
cp	8

jp      nz,l37
ld      l,(iy+27)
ld      h,(iy+28)
push    hl
call    _sub_377A
pop     bc
ld      (iy+27),l
ld      (iy+28),h
l37:
;push    iy
;pop     hl
;jp      cret
jp	pushIYpopHLcret
global  _sub_37ED
global  aslr
_sub_37ED:
global csv
call csv
push hl
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
ld      l,(iy+23)
ld      h,(iy+24)
ld      (ix+-2),l
ld      (ix+-1),h
ld      a,(iy+21)
or      (iy+22)
jp      z,l41
ld      b,2
push    iy
pop     de
ld      hl,21
add     hl,de
call    aslr
jp      cret
l42:
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      hl,15
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (ix+-2),c
ld      (ix+-1),b
l41:
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      hl,13
add     hl,de
ld      a,(hl)
inc     hl
or      (hl)
jp      z,l42
ld      hl,15
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (iy+23),c
ld      (iy+24),b
ld      hl,13
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
srl     b
rr      c
srl     b
rr      c
ld      (iy+21),c
ld      (iy+22),b
jp      cret
global  _sub_385B
_sub_385B:
global csv
call csv
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
ld      l,(iy+21)
ld      h,(iy+22)
add     hl,hl
add     hl,hl
set     0,l
ld      (iy+21),l
ld      (iy+22),h
jp      cret
global  _sub_387A
global  _nodesize
_sub_387A:
global csv
call csv
push hl
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
ld      a,(iy+21)
or      (iy+22)
jp      nz,l46
ld      e,(iy+23)
ld      d,(iy+24)
ld      hl,15
add     hl,de
ld      a,(hl)
inc     hl
or      (hl)
jp      nz,l46
ld      hl,13
add     hl,de
ld      a,(hl)
inc     hl
or      (hl)
jp      nz,l46
;ld      hl,1
;jp      cret
jp	ldHL1cret
l46:
push    iy
call    _sub_37ED
pop     bc
push    iy
call    _nodesize
pop     bc
ld      (ix+-1),l
push    iy
call    _sub_385B
pop     bc
ld      l,(ix+-1)
;ld      h,0
;jp      cret
jp	ldHL0cret
global  _sub_38CA
_sub_38CA:
global csv
call csv
ld      e,(ix+6)
ld      d,(ix+7)
ld      hl,21
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      a,c
and     (ix+8)
ld      l,a
ld      a,b
and     (ix+9)
ld      h,a
ld      a,l
or      h
jp      z,l48
L1:
;ld      l,1
;jp      cret
jp	ldL1cret
l48:
ld      e,(ix+6)
ld      d,(ix+7)
ld      hl,21
add     hl,de
ld      a,(hl)
inc     hl
or      (hl)
jp      z,l49
L3:
;ld      l,0
;jp      cret
jp	ldL0cret
l49:
ld      e,(ix+6)
ld      d,(ix+7)
ld      hl,23
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
pop     iy
l52:
ld      a,(iy+13)
and     (ix+8)
ld      l,a
ld      a,(iy+14)
and     (ix+9)
ld      h,a
ld      a,l
or      h
jp      nz,L1
ld      a,(iy+13)
or      (iy+14)
jp      nz,L3
ld      l,(iy+15)
ld      h,(iy+16)
push    hl
pop     iy
ld      a,l
or      h
jp      nz,l52
jp      L3
global  _sub_393C
_sub_393C:
global csv
call csv
ld      hl,1
push    hl
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
call    _sub_38CA
;pop     bc
;pop     bc
;jp      cret
jp	popBCpopBCcret
global  _sub_3952
_sub_3952:
global csv
call csv
ld      hl,2
push    hl
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
call    _sub_38CA
;pop     bc
;pop     bc
;jp      cret
jp	popBCpopBCcret
global  _sub_3968
_sub_3968:
global csv
call csv
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
ld      l,(iy+23)
ld      h,(iy+24)
inc     hl
inc     hl
ld      a,(hl)
cp      55
jp      nz,L5
bit     0,(iy+21)
jp      nz,L5
;ld      hl,1
;jp      cret
jp	ldHL1cret
L5:
;ld      hl,0
;jp      cret
jp	ldHL0cret
global  _prError
_nodesize:
global csv
call csv
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
bit     1,(iy+21)
jp      z,l59
ld      hl,19f
push    hl
call    _prError
pop     bc
l59:
bit     0,(iy+21)
jp      z,l60
ld      hl,2
jp      cret
l60:
ld      e,(iy+23)
ld      d,(iy+24)
ld      hl,9
add     hl,de
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
jp      cret
global  _sub_39CA
global  _sub_14F3
global  _sprintf
global  _strlen

IF RAM128

global  _MyAlloc
global  _PutString

ENDIF

global  _newLocal
global  _sub_3A79
_sub_39CA:
call ncsv
defw -50
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
ld      l,(iy+27)
ld      h,(iy+28)
push    hl
call    _freeNode
pop     bc
push    iy
call    _sub_14F3
pop     bc
ld      a,l
cp      3
jp      nz,l62
ld      e,(iy+25)
ld      d,(iy+26)
ld      hl,25
add     hl,de
ld      e,(hl)
inc     hl
ld      d,(hl)
inc     hl
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
push    hl
push    de
ld      hl,29f
push    hl
push    ix
pop     de
ld      hl,-50
add     hl,de
push    hl
call    _sprintf
pop     bc
pop     bc
pop     bc
ld      l,(iy+25)
ld      h,(iy+26)
ex      (sp),hl
call    _freeNode
push    ix
pop     de
ld      hl,-50
add     hl,de
ex      (sp),hl
call    _strlen
pop     bc
inc     hl
push    hl

IF RAM128

call    _MyAlloc

ELSE

call    _allocMem

ENDIF

ld      (iy+25),l
ld      (iy+26),h

IF RAM128

ex      (sp),hl
push    ix
pop     de
ld      hl,-50
add     hl,de
push    hl
call    _PutString

ELSE

push    ix
pop     de
ld      hl,-50
add     hl,de
ex      (sp),hl
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
call    _strcpy

ENDIF

pop     bc
pop     bc
call    _newLocal
ld      (iy+27),l
ld      (iy+28),h
ld      (iy+0),68
;push    iy
;pop     hl
;jp      cret
jp	pushIYpopHLcret
l62:
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
push    iy
call    _sub_3A79
pop     bc
pop     bc
push    iy
call    _freeNode
pop     bc
ld      l,(iy+25)
ld      h,(iy+26)
jp      cret
global  wrelop
global  asal
global  allsh
global  asaland
global  shal
global  aland
global  allsh
global  asalor
_sub_3A79:
global csv
call csv
push hl
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
push    hl
call    _nodesize
pop     bc
ld      (ix+-2),l
ld      (ix+-1),h
ld      a,l
or      (ix+-1)
jp      z,l64
ld      de,4
call    wrelop
jp      p,l64
ld      b,3
push    ix
pop     hl
dec     hl
dec     hl
call    asal
ld      b,(ix+-2)
ld      de,1
ld      hl,0
call    allsh
ex      de,hl
ld      bc,-1
add     hl,bc
ex      de,hl
adc     hl,bc
push    hl
push    de
ld      e,(ix+8)
ld      d,(ix+9)
ld      hl,25
add     hl,de
call    asaland
push    iy
call    _sub_14F3
pop     bc
ld      a,l
cp      1
ld      e,(ix+8)
ld      d,(ix+9)
jp      nz,L9
ld      hl,25
add     hl,de
ld      e,(hl)
inc     hl
ld      d,(hl)
inc     hl
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
push    hl
push    de
ld      l,(ix+-2)
ld      h,(ix+-1)
dec     hl
ld      b,l
ld      hl,1
call    shal
ex      de,hl
ld      a,d
rla
sbc     a,a
ld      l,a
ld      h,a
call    aland
ld      a,e
or      d
or      l
or      h
jp      z,l64
ld      b,(ix+-2)
ld      de,1
ld      hl,0
call    allsh
ex      de,hl
ld      bc,-1
add     hl,bc
ex      de,hl
adc     hl,bc
push    hl
push    de
ld      l,c
ld      h,b
pop     bc
or      a
sbc     hl,bc
pop     bc
ex      de,hl
ld      hl,-1
sbc     hl,bc
push    hl
push    de
ld      e,(ix+8)
ld      d,(ix+9)
ld      hl,25
add     hl,de
call    asalor
l64:
ld      e,(ix+8)
ld      d,(ix+9)
L9:
ld      hl,23
add     hl,de
ld      e,(iy+23)
ld      d,(iy+24)
ld      (hl),e
inc     hl
ld      (hl),d
ld      e,(ix+8)
ld      d,(ix+9)
ld      hl,21
add     hl,de
ld      e,(iy+21)
ld      d,(iy+22)
ld      (hl),e
inc     hl
ld      (hl),d
jp      cret
global  _sub_3B65
global  aslldiv
global  asllmod
global  asllrsh
_sub_3B65:
global csv
call csv
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
ld      l,(ix+12)
ld      h,(ix+13)
ld      a,h
or      a
jp      nz,cret
ld      a,l
cp      6
jp      z,l71
cp      24
jp      z,l70
cp      47
jp      z,l72
jp      cret
l70:
ld      e,(ix+8)
ld      d,(ix+9)
ld      l,(ix+10)
ld      h,(ix+11)
push    hl
push    de
push    iy
pop     hl
call    aslldiv
jp      cret
l71:
ld      e,(ix+8)
ld      d,(ix+9)
ld      l,(ix+10)
ld      h,(ix+11)
push    hl
push    de
push    iy
pop     hl
call    asllmod
jp      cret
l72:
ld      b,(ix+8)
push    iy
pop     hl
call    asllrsh
jp      cret
global  _sub_3BC6
global  asaladd
global  asalsub
global  asalmul
global  asaldiv
global  asalmod
global  asalor
global  asaland
global  asalxor
global  asallsh
global  asalrsh
_sub_3BC6:
global csv
call csv
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
ld      l,(ix+12)
ld      h,(ix+13)
ld      a,h
or      a
jp      nz,cret
ld      a,l
cp      6
jp      z,l80
cp      7
jp      z,l82
cp      12
jp      z,l78
cp      14
jp      z,l76
cp      18
jp      z,l77
cp      24
jp      z,l79
cp      31
jp      z,l84
cp      47
jp      z,l85
cp      58
jp      z,l83
cp      60
jp      z,l81
jp      cret
l76:
ld      e,(ix+8)
ld      d,(ix+9)
ld      l,(ix+10)
ld      h,(ix+11)
push    hl
push    de
push    iy
pop     hl
call    asaladd
jp      cret
l77:
ld      e,(ix+8)
ld      d,(ix+9)
ld      l,(ix+10)
ld      h,(ix+11)
push    hl
push    de
push    iy
pop     hl
call    asalsub
jp      cret
l78:
ld      e,(ix+8)
ld      d,(ix+9)
ld      l,(ix+10)
ld      h,(ix+11)
push    hl
push    de
push    iy
pop     hl
call    asalmul
jp      cret
l79:
ld      e,(ix+8)
ld      d,(ix+9)
ld      l,(ix+10)
ld      h,(ix+11)
push    hl
push    de
push    iy
pop     hl
call    asaldiv
jp      cret
l80:
ld      e,(ix+8)
ld      d,(ix+9)
ld      l,(ix+10)
ld      h,(ix+11)
push    hl
push    de
push    iy
pop     hl
call    asalmod
jp      cret
l81:
ld      e,(ix+8)
ld      d,(ix+9)
ld      l,(ix+10)
ld      h,(ix+11)
push    hl
push    de
push    iy
pop     hl
call    asalor
jp      cret
l82:
ld      e,(ix+8)
ld      d,(ix+9)
ld      l,(ix+10)
ld      h,(ix+11)
push    hl
push    de
push    iy
pop     hl
call    asaland
jp      cret
l83:
ld      e,(ix+8)
ld      d,(ix+9)
ld      l,(ix+10)
ld      h,(ix+11)
push    hl
push    de
push    iy
pop     hl
call    asalxor
jp      cret
l84:
ld      b,(ix+8)
push    iy
pop     hl
call    asallsh
jp      cret
l85:
ld      b,(ix+8)
push    iy
pop     hl
call    asalrsh
jp      cret
global  _sub_3CDF
global  _sub_2BD0
global  _byte_B014
global  _sub_4C6D
global  _array_AFFD
_sub_3CDF:
global csv
call csv
push hl
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
ld      a,(iy+0)
cp      28
jp      nz,l87
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
call    _sub_2BD0
pop     bc
push    iy
call    _freeNode
pop     bc
ld      l,(iy+27)
ld      h,(iy+28)
push    hl
pop     iy
l87:
ld      a,(_byte_B014)
cp      10
jp      z,L16
ld      de,_dopetab
ld      l,(iy+0)
ld      h,0
add     hl,hl
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
bit     6,b
jp      z,l89
L16:
;push    iy
;pop     hl
;jp      cret
jp	pushIYpopHLcret
l89:
ld      a,(iy+0)
cp      15
jp      z,L14
cp      19
jp      nz,l90
L14:
push    iy
call    _sub_4C6D
pop     bc
ld      a,l
or      a
jp      z,l90
ld      a,(_byte_B014)
ld      e,a
inc     a
ld      (_byte_B014),a
ld      l,e
ld      h,0
add     hl,hl
ld      de,_array_AFFD
add     hl,de
push    iy
pop     de
ld      (hl),e
inc     hl
ld      (hl),d
ld      a,(iy+0)
cp      15
jp      z,L13
ld      hl,38
jp      L12
L13:
ld      hl,37
L12:
ld      (iy+0),l
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
call    _sub_377A
pop     bc
push    hl
pop     iy
l90:
ld      de,_dopetab
ld      l,(iy+0)
ld      h,0
add     hl,hl
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (ix+-2),c
ld      (ix+-1),b
ld      a,c
and     12
ld      l,a
xor     a
ld      h,a
ld      a,l
or      h
jp      z,l91
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
call    _sub_3CDF
pop     bc
ld      (iy+25),l
ld      (iy+26),h
l91:

;ld      de,8
ld      a,(ix+-2)
and     12
;ld      l,a
;xor     a
;ld      h,a
;or      a
;sbc     hl,de
cp	8

jp      nz,L16
ld      l,(iy+27)
ld      h,(iy+28)
push    hl
call    _sub_3CDF
pop     bc
ld      (iy+27),l
ld      (iy+28),h
jp      L16
psect   data
19:
defb    99,97,110,39,116,32,116,97,107,101,32,115,105,122,101,111
defb    102,32,102,117,110,99,0
29:
defb    37,108,100,46,0
psect   text

