global  _sub_2BD0
global  ncsv, cret, indir
global  _sub_1F4B
global  _word_B017
global  wrelop
global  _fatalErr
global  _sub_35E6
global  _prFrameHead
global  _array_AEDB
global  _lvlidx
global  _sub_1EDF
global  _sub_475C
psect   text
_sub_2BD0:
global csv
call csv
push hl
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
ld      (iy+1),0
push    ix
pop     hl
dec     hl
dec     hl
push    hl
ld      hl,0
push    hl
ld      hl,(_word_B017)
push    hl
ld      hl,72
push    hl
push    iy
call    _sub_1F4B
pop     bc
pop     bc
pop     bc
pop     bc
pop     bc
ex      de,hl
ld      hl,0
call    wrelop
jp      m,l11
ld      hl,19f
push    hl
call    _fatalErr
pop     bc
l11:
push    iy
call    _sub_35E6
pop     bc
ld      a,(iy+0)
cp      26
jp      nz,l12
bit     1,(iy+21)
jp      z,l13
ld      de,_array_AEDB
ld      hl,(_lvlidx)
add     hl,hl
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      hl,17
add     hl,bc
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
call    _prFrameHead
pop     bc
call    _sub_1EDF
l13:
ld      l,(iy+25)
ld      h,(iy+26)
ld      a,(hl)
cp      66
jp      nz,l12
ex      de,hl
ld      hl,25
add     hl,de
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
inc     hl
inc     hl
inc     hl
set     0,(hl)
l12:
push    iy
call    _sub_475C
jp      cret
global  _sub_2C5E
global  _nodesize
global  brelop
global  allsh
global  aland
global  allsh
global  asalor
_sub_2C5E:
global csv
call csv
push hl
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
call    _nodesize
pop     bc
add     hl,hl
add     hl,hl
add     hl,hl
ld      a,l
ld      (ix+-1),a
ld      b,32
call    brelop
ld      e,(ix+8)
ld      d,(ix+9)
ld      l,(ix+10)
ld      h,(ix+11)
jp      p,cret
push    hl
push    de
ld      a,(ix+-1)
add     a,255
ld      b,a
ld      de,1
ld      hl,0
call    allsh
call    aland
ld      a,e
or      d
or      l
or      h
jp      z,l17
ld      b,(ix+-1)
ld      de,1
ld      hl,0
call    allsh
ex      de,hl
ld      bc,-1
add     hl,bc
ex      de,hl
adc     hl,bc
push    hl
push    de
ld      l,c
ld      h,b
pop     bc
or      a
sbc     hl,bc
pop     bc
ex      de,hl
ld      hl,-1
sbc     hl,bc
push    hl
push    de
push    ix
pop     de
ld      hl,8
add     hl,de
call    asalor
l17:
ld      e,(ix+8)
ld      d,(ix+9)
ld      l,(ix+10)
ld      h,(ix+11)
jp      cret
global  _sub_2CE0
global  _printf
_sub_2CE0:
global csv
call csv
ld      e,(ix+8)
ld      d,(ix+9)
ld      l,(ix+10)
ld      h,(ix+11)
push    hl
push    de
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
call    _sub_2C5E
pop     bc
pop     bc
ex      (sp),hl
push    de
ld      hl,29f
push    hl
call    _printf
jp      cret
psect   data
19:
defb    69,120,112,114,101,115,115,105,111,110,32,116,111,111,32,99
defb    111,109,112,108,105,99,97,116,101,100,0
29:
defb    37,108,100,0
psect   text

