include cgen.inc
global  _sub_808
global  ncsv, cret, indir
global  _sub_475C
global  _sub_1CC4
global  amod
global  amod
global  _prDefb0s
global  _sub_43EF
global  _sub_415E
global  allsh
global  _parseExpr
global  _nodesize
global  _sub_2BD0
global  _sub_600E
global  wrelop
global  wrelop
global  _prError
psect   text
_sub_808:
call ncsv
defw -12
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
ld      (ix+-2),0
ld      (ix+-1),0
ld      l,(ix+8)
ld      h,(ix+9)
ld      a,(hl)
cp      26
jp      nz,l11
push    hl
call    _sub_475C
pop     bc
ld      (ix+-10),0
ld      (ix+-9),0
ld      a,(iy+2)
cp      55
jp      nz,l12
push    iy
pop     hl
ld      (ix+-6),l
ld      (ix+-5),h
jp      l13
l14:
ld      e,(ix+-6)
ld      d,(ix+-5)
ld      hl,19
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      l,(ix+-10)
ld      h,(ix+-9)
inc     hl
ld      (ix+-10),l
ld      (ix+-9),h
dec     hl
add     hl,hl
add     hl,bc
inc     hl
inc     hl
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (ix+-8),c
ld      (ix+-7),b
push    bc
call    _sub_1CC4
pop     bc
ld      (ix+-4),l
ld      (ix+-3),h
ld      a,l
or      h
jp      z,l16
ld      e,l
ld      d,h
inc     de
ld      (ix+-4),e
ld      (ix+-3),d
ld      l,(ix+-2)
ld      h,(ix+-1)
call    amod
ld      a,l
or      h
jp      z,l16
ld      e,(ix+-4)
ld      d,(ix+-3)
ld      l,(ix+-2)
ld      h,(ix+-1)
call    amod
ex      de,hl
ld      l,(ix+-4)
ld      h,(ix+-3)
or      a
sbc     hl,de
ld      (ix+-4),l
ld      (ix+-3),h
ex      de,hl
ld      l,(ix+-2)
ld      h,(ix+-1)
add     hl,de
ld      (ix+-2),l
ld      (ix+-1),h
ld      l,e
ld      h,d
push    hl
call    _prDefb0s
pop     bc
l16:
ld      l,(ix+-8)
ld      h,(ix+-7)
inc     hl
inc     hl
inc     hl
bit     4,(hl)
jp      z,l17
ld      e,(ix+-8)
ld      d,(ix+-7)
ld      hl,5
add     hl,de
ld      b,(hl)
ld      de,1
ld      hl,0
call    allsh
ex      de,hl
ld      bc,-1
add     hl,bc
ex      de,hl
adc     hl,bc
push    hl
push    de
call    _sub_415E
pop     bc
ex      (sp),hl
ld      l,(ix+8)
ld      h,(ix+9)
push    hl
ld      l,7
push    hl
call    _sub_43EF
pop     bc
pop     bc
pop     bc
ld      (ix+8),l
ld      (ix+9),h
ld      e,(ix+-8)
ld      d,(ix+-7)
ld      hl,6
add     hl,de
ld      a,(hl)
or      a
jp      z,l18
ld      de,0
ld      l,e
ld      h,d
push    hl
push    de
call    _sub_415E
pop     bc
ex      (sp),hl
ld      l,(ix+8)
ld      h,(ix+9)
push    hl
ld      l,31
push    hl
call    _sub_43EF
pop     bc
pop     bc
ex      (sp),hl
ld      l,(ix+-12)
ld      h,(ix+-11)
push    hl
ld      l,60
push    hl
call    _sub_43EF
pop     bc
pop     bc
pop     bc
ld      (ix+-12),l
ld      (ix+-11),h
jp      l19
l18:
ld      l,(ix+8)
ld      h,(ix+9)
ld      (ix+-12),l
ld      (ix+-11),h
l19:
ld      e,(ix+-6)
ld      d,(ix+-5)
ld      hl,19
add     hl,de
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
ld      e,(hl)
inc     hl
ld      d,(hl)
ld      l,(ix+-10)
ld      h,(ix+-9)
or      a
sbc     hl,de
jp      z,l20
ld      e,(ix+-6)
ld      d,(ix+-5)
ld      hl,19
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      l,(ix+-10)
ld      h,(ix+-9)
add     hl,hl
add     hl,bc
inc     hl
inc     hl
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
inc     hl
inc     hl
inc     hl
bit     4,(hl)
jp      z,l20
ld      e,(ix+-8)
ld      d,(ix+-7)
ld      hl,17
add     hl,de
ld      e,(hl)
inc     hl
ld      d,(hl)
push    de
ld      e,(ix+-6)
ld      d,(ix+-5)
ld      hl,19
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      l,(ix+-10)
ld      h,(ix+-9)
add     hl,hl
add     hl,bc
inc     hl
inc     hl
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      hl,17
add     hl,bc
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
pop     de
or      a
sbc     hl,de
jp      z,l13
l20:
ld      l,(ix+-12)
ld      h,(ix+-11)
ld      (ix+8),l
ld      (ix+9),h
l17:
ld      l,(ix+8)
ld      h,(ix+9)
push    hl
ld      l,(ix+-8)
ld      h,(ix+-7)
push    hl
call    _sub_808
pop     bc
pop     bc
ex      de,hl
ld      l,(ix+-2)
ld      h,(ix+-1)
add     hl,de
ld      (ix+-2),l
ld      (ix+-1),h
l13:
call    _parseExpr
ld      (ix+8),l
ld      (ix+9),h
ld      a,(hl)
cp      23
jp      nz,l14
push    hl
L4:
call    _sub_475C
pop     bc
jp      l29
l12:
ld      l,(iy+15)
ld      h,(iy+16)
ld      (ix+-6),l
ld      (ix+-5),h
l22:
call    _parseExpr
ld      (ix+8),l
ld      (ix+9),h
ld      a,(hl)
cp      26
jp      nz,L1
push    hl
ld      l,(ix+-6)
ld      h,(ix+-5)
push    hl
call    _sub_808
pop     bc
pop     bc
ex      de,hl
ld      l,(ix+-2)
ld      h,(ix+-1)
add     hl,de
ld      (ix+-2),l
ld      (ix+-1),h
jp      l22
L1:
ld      a,(hl)
cp      23
ld      l,(ix+8)
ld      h,(ix+9)
push    hl
jp      z,L4
call    _nodesize
ex      de,hl
ld      l,(ix+-2)
ld      h,(ix+-1)
add     hl,de
ld      (ix+-2),l
ld      (ix+-1),h
ld      hl,0
ex      (sp),hl
ld      l,(ix+8)
ld      h,(ix+9)
push    hl
ld      l,49
push    hl
call    _sub_43EF
pop     bc
pop     bc
ex      (sp),hl
call    _sub_600E
ex      (sp),hl
call    _sub_2BD0
pop     bc
jp      l22
l11:
ld      hl,0
push    hl
ld      l,(ix+8)
ld      h,(ix+9)
push    hl
ld      l,49
push    hl
call    _sub_43EF
pop     bc
pop     bc
ex      (sp),hl
call    _sub_600E
ld      (ix+8),l
ld      (ix+9),h
ex      (sp),hl
call    _nodesize
ld      (ix+-2),l
ld      (ix+-1),h
ld      l,(ix+8)
ld      h,(ix+9)
ex      (sp),hl
call    _sub_2BD0
pop     bc
l29:
ld      e,(iy+9)
ld      d,(iy+10)
ld      l,(ix+-2)
ld      h,(ix+-1)
call    wrelop
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      l,(iy+9)
ld      h,(iy+10)
jp      nc,L3
or      a
sbc     hl,de
push    hl
call    _prDefb0s
pop     bc
ld      l,(iy+9)
ld      h,(iy+10)
ld      (ix+-2),l
ld      (ix+-1),h
jp      l31
L3:
call    wrelop
jp      nc,l31
ld      a,(iy+9)
or      (iy+10)
jp      z,l31
ld      hl,19f
push    hl
call    _prError
pop     bc
l31:
;ld      l,(ix+-2)
;ld      h,(ix+-1)
;jp      cret
jp	ldLIXm2ldHIXm1cret
global  _parseInit
global  _sub_265
global  _getToken
global  _prPsect
global  _sub_CAB
global  adiv
global  _varSize
global  _expect
_parseInit:
global csv
call csv
push hl
push hl
call    _getToken
push    hl
call    _sub_265
push    hl
pop     iy
ld      hl,3
ex      (sp),hl
call    _prPsect
pop     bc
push    iy
call    _sub_CAB
pop     bc
call    _parseExpr
push    hl
push    iy
call    _sub_808
pop     bc
pop     bc
ld      (ix+-2),l
ld      (ix+-1),h
ld      a,(iy+13)
or      (iy+14)
jp      nz,L6
ld      e,(iy+15)
ld      d,(iy+16)
ld      hl,9
add     hl,de
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
jp      L5
L6:
ld      hl,2
L5:
ld      (ix+-4),l
ld      (ix+-3),h
ld      a,(iy+11)
or      (iy+12)
jp      nz,l34
ex      de,hl
ld      l,(ix+-2)
ld      h,(ix+-1)
call    adiv
ld      (iy+11),l
ld      (iy+12),h
push    iy
call    _varSize
pop     bc
ld      (iy+9),l
ld      (iy+10),h
l34:
ld      l,93
push    hl
call    _expect
jp      cret
global  _prFrameHead
global  _printf
psect   bss
F426:
defs    1
psect   text
_prFrameHead:
global csv
call csv
ld      hl,2
push    hl
call    _prPsect
pop     bc
ld      a,(F426)
or      a
jp      nz,l36
ld      hl,29f
push    hl
call    _printf
pop     bc
l36:
ld      hl,39f
push    hl
call    _printf
ld      a,1
ld      (F426),a
ld      l,(ix+6)
ld      h,(ix+7)
ex      (sp),hl
ld      hl,49f
push    hl
call    _printf
jp      cret
global  _prFrameTail
_prFrameTail:
global csv
call csv
ld      hl,2
push    hl
call    _prPsect
ld      l,(ix+8)
ld      h,(ix+9)
ex      (sp),hl
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
ld      hl,59f
push    hl
call    _printf
jp      cret
global  _sub_BEE
_sub_BEE:
global csv
call csv
ld      hl,2
push    hl
call    _prPsect
ld      l,(ix+6)
ld      h,(ix+7)
ex      (sp),hl
ld      l,(ix+8)
ld      h,(ix+9)
push    hl
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
ld      hl,69f
push    hl
call    _printf
pop     bc
pop     bc
pop     bc
ld      hl,1
ex      (sp),hl
call    _prPsect
ld      l,(ix+8)
ld      h,(ix+9)
ex      (sp),hl
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
ld      hl,79f
push    hl
call    _printf
jp      cret
global  _prGlobalDef

IF RAM128

global  _GetString
global  _tmpBuf

ENDIF

_prGlobalDef:
global csv
call csv
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
ld      l,(iy+0)
ld      h,(iy+1)
push    hl

IF RAM128

ld      hl,_tmpBuf
push    hl
call    _GetString
pop     bc
ld      hl,_tmpBuf
ex      (sp),hl

ENDIF

ld      hl,89f
push    hl
call    _printf
set     1,(iy+3)
jp      cret
global  _sub_C57
_sub_C57:
global csv
call csv
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
bit     0,(iy+3)
jp      nz,cret
ld      a,(iy+11)
or      (iy+12)
jp      z,cret
bit     1,(iy+13)
jp      nz,cret
ld      hl,1
push    hl
call    _prPsect
pop     bc
ld      a,(iy+21)
cp      3
jp      nz,l42
bit     1,(iy+3)
push    iy
jp      nz,L7
call    _prGlobalDef
pop     bc
l42:
push    iy
L7:
call    _sub_CAB
ld      l,(iy+9)
ld      h,(iy+10)
ex      (sp),hl
ld      hl,99f
push    hl
call    _printf
jp      cret
_sub_CAB:
global csv
call csv
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
bit     1,(iy+3)
jp      nz,l44
ld      a,(iy+21)
cp      3
jp      nz,l44
push    iy
call    _prGlobalDef
pop     bc
l44:
set     0,(iy+3)
ld      l,(iy+0)
ld      h,(iy+1)
push    hl

IF RAM128

ld      hl,_tmpBuf
push    hl
call    _GetString
pop     bc
ld      hl,_tmpBuf
ex      (sp),hl

ENDIF

ld      hl,109f
push    hl
call    _printf
jp      cret
global  _fputchar
_prDefb0s:
global csv
call csv
push hl
ld      (ix+-1),0
jp      l46
L8:
or      a
jp      nz,l49
ld      hl,119f
push    hl
call    _printf
pop     bc
jp      l50
l49:
ld      hl,129f
push    hl
call    _printf
pop     bc
l50:
inc     (ix+-1)
ld      a,(ix+-1)
cp      16
jp      nz,l46
ld      (ix+-1),0
ld      hl,10
push    hl
call    _fputchar
pop     bc
l46:
ld      l,(ix+6)
ld      h,(ix+7)
dec     hl
ld      (ix+6),l
ld      (ix+7),h
inc     hl
ld      a,l
or      h
ld      a,(ix+-1)
jp      nz,L8
or      a
jp      z,cret
ld      hl,10
push    hl
call    _fputchar
jp      cret
psect   data
F440:
defw    139f
defw    149f
defw    159f
defw    169f
psect   bss
F439:
defs    2
psect   text
_prPsect:
global csv
call csv
ld      de,(F439)
ld      l,(ix+6)
ld      h,(ix+7)
or      a
sbc     hl,de
jp      z,cret
ld      de,F440
ld      l,(ix+6)
ld      h,(ix+7)
ld      (F439),hl
add     hl,hl
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
ld      hl,179f
push    hl
call    _printf
jp      cret
global  _sortCaseLabels
global  wrelop
global  wrelop
_sortCaseLabels:
call ncsv
defw -9
l58:
ld      (ix+-1),0
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
ld      l,(ix+8)
ld      h,(ix+9)
ld      (ix+-3),l
ld      (ix+-2),h
ld      l,(ix+10)
ld      h,(ix+11)
ld      (ix+-5),l
ld      (ix+-4),h
jp      l62
l59:
ld      e,(iy+0)
ld      d,(iy+1)
ld      l,(iy+2)
ld      h,(iy+3)
call    wrelop
jp      p,l63
ld      (ix+-1),1
ld      l,(iy+0)
ld      h,(iy+1)
ld      (ix+-7),l
ld      (ix+-6),h
ld      l,(iy+2)
ld      h,(iy+3)
ld      (iy+0),l
ld      (iy+1),h
ld      l,(ix+-7)
ld      h,(ix+-6)
ld      (iy+2),l
ld      (iy+3),h
ld      l,(ix+-3)
ld      h,(ix+-2)
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (ix+-9),c
ld      (ix+-8),b
inc     hl
ld      c,(hl)
inc     hl
ld      b,(hl)
dec     hl
dec     hl
dec     hl
ld      (hl),c
inc     hl
ld      (hl),b
ld      e,(ix+-9)
ld      d,(ix+-8)
inc     hl
ld      (hl),e
inc     hl
ld      (hl),d
l61:
push    iy
pop     hl
inc     hl
inc     hl
push    hl
pop     iy
ld      l,(ix+-3)
ld      h,(ix+-2)
inc     hl
inc     hl
ld      (ix+-3),l
ld      (ix+-2),h
dec     hl
dec     hl
l62:
ld      e,(ix+-5)
ld      d,(ix+-4)
dec     de
ld      (ix+-5),e
ld      (ix+-4),d
ld      hl,0
call    wrelop
jp      m,l59
ld      a,(ix+-1)
or      a
jp      nz,l58
jp      cret
l63:
ld      e,(iy+2)
ld      d,(iy+3)
ld      l,(iy+0)
ld      h,(iy+1)
or      a
sbc     hl,de
jp      nz,l61
ld      hl,189f
push    hl
call    _prError
;pop     bc
;jp      cret
jp	popBCcret
global  _parseSwitch
global  _atoi
global  _freeNode
global  _prWarning
global  wrelop
global  amul
global  wrelop
global  _allocNode
global  _sub_3DC9
global  _newLocal
global  shar
global  wrelop
global  shar
global  shar
global  shar
global  shar
global  _sub_1420
global  shar
global  asar
global  wrelop
global  wrelop
global  wrelop
global  wrelop
_parseSwitch:
call ncsv
defw -1038
call    _parseExpr
ld      (ix+-2),l
ld      (ix+-1),h
ld      (ix+-10),0
ld      (ix+-9),0
l67:
call    _parseExpr
push    hl
call    _sub_600E
pop     bc
push    hl
pop     iy
call    _getToken
push    hl
call    _atoi
pop     bc
ld      (ix+-4),l
ld      (ix+-3),h
ld      a,(iy+0)
cp      23
jp      nz,l70
ld      (ix+-12),l
ld      (ix+-11),h
push    iy
call    _freeNode
ld      l,93
ex      (sp),hl
call    _expect
pop     bc
ld      a,(ix+-10)
or      (ix+-9)
jp      nz,l68
ld      hl,199f
push    hl
call    _prWarning
ld      l,(ix+-2)
ld      h,(ix+-1)
ex      (sp),hl
call    _sub_475C
ld      l,(ix+-12)
ld      h,(ix+-11)
ex      (sp),hl
ld      hl,209f
L10:
push    hl
call    _printf
;pop     bc
;pop     bc
;jp      cret
jp	popBCpopBCcret
l70:
ld      a,(iy+0)
cp      67
jp      nz,l72
push    ix
pop     de
ld      l,(ix+-10)
ld      h,(ix+-9)
add     hl,hl
add     hl,de
ld      de,-528
add     hl,de
ld      e,(iy+25)
ld      d,(iy+26)
ld      (hl),e
inc     hl
ld      (hl),d
push    ix
pop     de
ld      l,(ix+-10)
ld      h,(ix+-9)
inc     hl
ld      (ix+-10),l
ld      (ix+-9),h
dec     hl
add     hl,hl
add     hl,de
ld      de,-1038
add     hl,de
ld      e,(ix+-4)
ld      d,(ix+-3)
ld      (hl),e
inc     hl
ld      (hl),d
jp      l73
l72:
ld      hl,219f
push    hl
call    _prError
pop     bc
l73:
push    iy
call    _sub_475C
pop     bc
jp      l67
l68:
ld      l,(ix+-10)
ld      h,(ix+-9)
push    hl
push    ix
pop     de
ld      hl,-1038
add     hl,de
push    hl
push    ix
pop     de
ld      hl,-528
add     hl,de
push    hl
call    _sortCaseLabels
pop     bc
pop     bc
pop     bc
push    ix
pop     de
ld      hl,-528
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
push    ix
pop     de
ld      l,(ix+-10)
ld      h,(ix+-9)
dec     hl
add     hl,hl
add     hl,de
ld      de,-528
add     hl,de
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
or      a
sbc     hl,bc
ld      (ix+-8),l
ld      (ix+-7),h
bit     7,(ix+-7)
jp      nz,l74
ld      de,16000
call    wrelop
jp      p,l74
ld      de,5
ld      l,(ix+-10)
ld      h,(ix+-9)
call    amul
push    hl
ld      de,20
ld      l,(ix+-8)
ld      h,(ix+-7)
add     hl,hl
add     hl,de
pop     de
call    wrelop
jp      p,l74
call    _allocNode
push    hl
pop     iy
ld      (iy+0),65
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      hl,23
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (iy+23),c
ld      (iy+24),b
ld      hl,21
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (iy+21),c
ld      (iy+22),b
push    iy
push    ix
pop     de
ld      hl,-528
add     hl,de
ld      e,(hl)
inc     hl
ld      d,(hl)
ld      a,d
rla
sbc     a,a
ld      l,a
ld      h,a
push    hl
push    de
call    _sub_415E
pop     bc
pop     bc
push    hl
ld      l,20
push    hl
call    _sub_43EF
pop     bc
pop     bc
push    hl
pop     iy
ex      (sp),hl
ld      l,(ix+-2)
ld      h,(ix+-1)
push    hl
ld      l,18
push    hl
call    _sub_43EF
pop     bc
pop     bc
push    hl
pop     iy
ex      (sp),hl
call    _nodesize
pop     bc

;ld      de,2
;or      a
;sbc     hl,de
ld	a,l
cp	2

jp      z,l75
call    _allocNode
ld      (ix+-2),l
ld      (ix+-1),h
ld      (hl),65
ld      hl,229f
push    hl
call    _sub_265
pop     bc
push    hl
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      hl,23
add     hl,de
pop     de
ld      (hl),e
inc     hl
ld      (hl),d
ld      l,(ix+-2)
ld      h,(ix+-1)
push    hl
push    iy
ld      l,20
push    hl
call    _sub_43EF
pop     bc
pop     bc
pop     bc
push    hl
pop     iy
l75:
ld      hl,2
push    hl
call    _prPsect
pop     bc
ld      hl,0
push    hl
push    iy
ld      l,11
push    hl
call    _sub_43EF
pop     bc
pop     bc
ex      (sp),hl
call    _sub_3DC9
pop     bc
call    _newLocal
ld      (ix+-6),l
ld      (ix+-5),h
push    hl
ld      l,(ix+-12)
ld      h,(ix+-11)
push    hl
ld      l,(ix+-8)
xor     a
ld      h,a
push    hl
ld      l,(ix+-12)
ld      h,(ix+-11)
push    hl
ld      b,8
ld      l,(ix+-8)
ld      h,(ix+-7)
call    shar
push    hl
ld      hl,239f
push    hl
call    _printf
ld      hl,12
add     hl,sp
ld      sp,hl
ld      hl,3
push    hl
call    _prPsect
ld      l,(ix+-6)
ld      h,(ix+-5)
ex      (sp),hl
ld      hl,249f
push    hl
call    _printf
pop     bc
pop     bc
ld      (ix+-4),0
ld      (ix+-3),0
push    ix
pop     de
ld      hl,-528
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (ix+-8),c
ld      (ix+-7),b
l78:
push    ix
pop     de
ld      l,(ix+-4)
ld      h,(ix+-3)
add     hl,hl
add     hl,de
ld      de,-528
add     hl,de
ld      e,(hl)
inc     hl
ld      d,(hl)
ld      l,(ix+-8)
ld      h,(ix+-7)
or      a
sbc     hl,de
jp      nz,l79
push    ix
pop     de
ld      l,(ix+-4)
ld      h,(ix+-3)
add     hl,hl
add     hl,de
ld      de,-1038
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
ld      hl,259f
push    hl
call    _printf
pop     bc
pop     bc
ld      l,(ix+-4)
ld      h,(ix+-3)
inc     hl
ld      (ix+-4),l
ld      (ix+-3),h
jp      l80
l79:
ld      l,(ix+-12)
ld      h,(ix+-11)
push    hl
ld      hl,269f
push    hl
call    _printf
pop     bc
pop     bc
l80:
ld      l,(ix+-8)
ld      h,(ix+-7)
inc     hl
ld      (ix+-8),l
ld      (ix+-7),h
ld      e,(ix+-10)
ld      d,(ix+-9)
ld      l,(ix+-4)
ld      h,(ix+-3)
call    wrelop
jp      m,l78
jp      cret
l74:
ld      l,(ix+-2)
ld      h,(ix+-1)
push    hl
call    _nodesize
pop     bc
ld      de,2
or      a
sbc     hl,de
ld      l,e
ld      h,d
push    hl
jp      nz,L9
call    _prPsect
ld      hl,0
ex      (sp),hl
ld      l,(ix+-2)
ld      h,(ix+-1)
push    hl
ld      l,11
push    hl
call    _sub_43EF
pop     bc
pop     bc
ex      (sp),hl
call    _sub_3DC9
pop     bc
ld      (ix+-14),255
ld      (ix+-13),255
ld      a,0
ld      (ix+-18),a
ld      (ix+-17),a
ld      l,a
rla
sbc     a,a
ld      h,a
ld      (ix+-16),l
ld      (ix+-15),h
ld      (ix+-4),l
ld      (ix+-3),l
jp      l85
l82:
push    ix
pop     de
ld      l,(ix+-4)
ld      h,(ix+-3)
add     hl,hl
add     hl,de
ld      de,-528
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      l,(ix+-14)
ld      h,(ix+-13)
ld      a,l
and     c
ld      l,a
ld      a,h
and     b
ld      h,a
ld      (ix+-14),l
ld      (ix+-13),h
push    ix
pop     de
ld      l,(ix+-4)
ld      h,(ix+-3)
add     hl,hl
add     hl,de
ld      de,-528
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      l,(ix+-16)
ld      h,(ix+-15)
ld      a,l
or      c
ld      l,a
ld      a,h
or      b
ld      h,a
ld      (ix+-16),l
ld      (ix+-15),h
ld      b,8
call    shar
ex      de,hl
ld      b,8
ld      l,(ix+-14)
ld      h,(ix+-13)
call    shar
or      a
sbc     hl,de
jp      z,l86
ld      e,(ix+-16)
xor     a
ld      d,a
ld      l,(ix+-14)
ld      h,a
or      a
sbc     hl,de
jp      z,l86
ld      a,(ix+-17)
ld      e,a
rla
sbc     a,a
ld      d,a
ld      a,(ix+-18)
ld      l,a
rla
sbc     a,a
ld      h,a
ld      a,l
or      e
ld      l,a
ld      a,h
or      d
ld      h,a
ld      a,l
or      h
jp      z,l87
ld      hl,279f
push    hl
call    _printf
pop     bc
l87:
xor     a
ld      (ix+-18),a
ld      (ix+-17),a
push    ix
pop     de
ld      l,(ix+-4)
ld      h,(ix+-3)
add     hl,hl
add     hl,de
ld      de,-528
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (ix+-16),c
ld      (ix+-15),b
ld      (ix+-14),c
ld      (ix+-13),b
l86:
ld      b,8
ld      l,(ix+-16)
ld      h,(ix+-15)
call    shar
ex      de,hl
ld      b,8
ld      l,(ix+-14)
ld      h,(ix+-13)
call    shar
or      a
sbc     hl,de
jp      nz,l88
ld      a,(ix+-18)
or      a
jp      nz,l89
ld      hl,289f
push    hl
call    _printf
pop     bc
ld      b,8
ld      l,(ix+-14)
ld      h,(ix+-13)
call    shar
push    hl
call    _sub_1420
ld      hl,299f
ex      (sp),hl
call    _printf
pop     bc
ld      (ix+-18),1
l89:
push    ix
pop     de
ld      l,(ix+-4)
ld      h,(ix+-3)
add     hl,hl
add     hl,de
ld      de,-528
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
xor     a
ld      b,a
ld      (hl),b
dec     hl
ld      (hl),c
jp      l90
l88:
ld      a,(ix+-17)
or      a
jp      nz,l91
ld      a,(ix+-18)
or      a
jp      z,l92
ld      hl,309f
push    hl
call    _printf
pop     bc
l92:
ld      hl,319f
push    hl
call    _printf
ld      l,(ix+-14)
xor     a
ld      h,a
ex      (sp),hl
call    _sub_1420
ld      hl,329f
ex      (sp),hl
call    _printf
pop     bc
ld      (ix+-17),1
l91:
ld      b,8
push    ix
pop     de
ld      l,(ix+-4)
ld      h,(ix+-3)
add     hl,hl
add     hl,de
ld      de,-528
add     hl,de
call    asar
push    ix
pop     de
ld      l,(ix+-4)
ld      h,(ix+-3)
add     hl,hl
add     hl,de
ld      de,-528
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
xor     a
ld      b,a
ld      (hl),b
dec     hl
ld      (hl),c
l90:
push    ix
pop     de
ld      l,(ix+-4)
ld      h,(ix+-3)
add     hl,hl
add     hl,de
ld      de,-528
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
call    _sub_1420
pop     bc
push    ix
pop     de
ld      l,(ix+-4)
ld      h,(ix+-3)
add     hl,hl
add     hl,de
ld      de,-1038
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
ld      hl,339f
push    hl
call    _printf
pop     bc
pop     bc
ld      l,(ix+-4)
ld      h,(ix+-3)
inc     hl
ld      (ix+-4),l
ld      (ix+-3),h
l85:
ld      e,(ix+-10)
ld      d,(ix+-9)
ld      l,(ix+-4)
ld      h,(ix+-3)
call    wrelop
jp      m,l82
ld      a,(ix+-17)
ld      e,a
rla
sbc     a,a
ld      d,a
ld      a,(ix+-18)
ld      l,a
rla
sbc     a,a
ld      h,a
ld      a,l
or      e
ld      l,a
ld      a,h
or      d
ld      h,a
ld      a,l
or      h
jp      z,l93
ld      hl,349f
push    hl
call    _printf
pop     bc
l93:
ld      l,(ix+-12)
ld      h,(ix+-11)
push    hl
ld      hl,359f
jp      L10
L9:
call    _prPsect
ld      hl,0
ex      (sp),hl
ld      l,(ix+-2)
ld      h,(ix+-1)
push    hl
ld      l,70
push    hl
call    _sub_43EF
pop     bc
pop     bc
ex      (sp),hl
call    _sub_3DC9
pop     bc
ld      (ix+-4),0
ld      (ix+-3),0
jp      l97
l94:
push    ix
pop     de
ld      l,(ix+-4)
ld      h,(ix+-3)
add     hl,hl
add     hl,de
ld      de,-528
add     hl,de
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
ld      de,256
call    wrelop
jp      p,l96
push    ix
pop     de
ld      l,(ix+-4)
ld      h,(ix+-3)
add     hl,hl
add     hl,de
ld      de,-528
add     hl,de
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
ld      de,-128
call    wrelop
jp      m,l96
push    ix
pop     de
ld      l,(ix+-4)
ld      h,(ix+-3)
add     hl,hl
add     hl,de
ld      de,-528
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
call    _sub_1420
pop     bc
push    ix
pop     de
ld      l,(ix+-4)
ld      h,(ix+-3)
add     hl,hl
add     hl,de
ld      de,-1038
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
ld      hl,369f
push    hl
call    _printf
pop     bc
pop     bc
l96:
ld      l,(ix+-4)
ld      h,(ix+-3)
inc     hl
ld      (ix+-4),l
ld      (ix+-3),h
l97:
ld      e,(ix+-10)
ld      d,(ix+-9)
ld      l,(ix+-4)
ld      h,(ix+-3)
call    wrelop
jp      m,l94
ld      l,(ix+-12)
ld      h,(ix+-11)
push    hl
ld      hl,379f
push    hl
call    _printf
jp      cret
_sub_1420:
global csv
call csv
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
ld      a,l
or      (ix+7)
jp      nz,L12
ld      hl,399f
jp      L11
L12:
ld      hl,389f
L11:
push    hl
call    _printf
jp      cret
global  _prPush
global  brelop
global  _regNames
_prPush:
global csv
call csv
ld      a,(ix+6)
cp      15
jp      nz,l101
ld      hl,409f
push    hl
call    _printf
;pop     bc
;jp      cret
jp	popBCcret
l101:
ld      b,8
ld      a,(ix+6)
call    brelop
jp      nc,l102
ld      e,(ix+6)
ld      d,0
srl     d
rr      e
ld      hl,11
add     hl,de
ld      (ix+6),l
l102:
ld      de,_regNames
ld      l,(ix+6)
ld      h,0
add     hl,hl
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
ld      hl,419f
push    hl
call    _printf
jp      cret
global  _prPop
global  brelop
_prPop:
global csv
call csv
ld      a,(ix+6)
cp      15
jp      nz,l104
ld      hl,429f
push    hl
call    _printf
;pop     bc
;jp      cret
jp	popBCcret
l104:
ld      b,8
ld      a,(ix+6)
call    brelop
jp      nc,l105
ld      e,(ix+6)
ld      d,0
srl     d
rr      e
ld      hl,11
add     hl,de
ld      (ix+6),l
l105:
ld      de,_regNames
ld      l,(ix+6)
ld      h,0
add     hl,hl
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
ld      hl,439f
push    hl
call    _printf
jp      cret
global  _prIXnPush
_prIXnPush:
global csv
call csv
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
ld      l,(iy+17)
ld      h,(iy+18)
inc     hl
push    hl
dec     hl
push    hl
ld      hl,449f
push    hl
call    _printf
jp      cret
global  _sub_14F3
global  wrelop
_sub_14F3:
global csv
call csv
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
bit     1,(iy+21)
jp      z,l108
L13:
;ld      l,0
;jp      cret
jp	ldL0cret
l108:
ld      a,(iy+21)
or      (iy+22)
jp      z,l109
ld      l,2
jp      cret
l109:
ld      e,(iy+23)
ld      d,(iy+24)
ld      hl,11
add     hl,de
ld      e,(hl)
inc     hl
ld      d,(hl)
ld      hl,1
call    wrelop
jp      c,L13
ld      e,(iy+23)
ld      d,(iy+24)
ld      hl,21
add     hl,de
ld      l,(hl)
jp      cret
global  _sub_153A
psect   data
F477:
defb    0
defb    97
defb    108
defb    102
psect   text
_sub_153A:
global csv
call csv
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
push    hl
call    _sub_14F3
ld      e,l
ld      d,0
ld      hl,F477
add     hl,de
ld      a,(hl)
ld      l,a
rla
sbc     a,a
ld      h,a
ex      (sp),hl
call    _fputchar
jp      cret
global  _prDefb
_prDefb:
global csv
call csv
push hl
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
ld      (ix+-1),0
jp      l113
L14:
or      a
jp      nz,l116
ld      hl,459f
push    hl
call    _printf
pop     bc
jp      l117
l116:
ld      hl,44
push    hl
call    _fputchar
pop     bc
l117:
push    iy
pop     hl
inc     hl
push    hl
pop     iy
dec     hl
ld      l,(hl)
ld      h,0
push    hl
ld      hl,469f
push    hl
call    _printf
pop     bc
pop     bc
inc     (ix+-1)
ld      a,(ix+-1)
cp      16
jp      nz,l113
ld      hl,10
push    hl
call    _fputchar
pop     bc
ld      (ix+-1),0
l113:
ld      l,(ix+8)
ld      h,(ix+9)
dec     hl
ld      (ix+8),l
ld      (ix+9),h
inc     hl
ld      a,l
or      h
ld      a,(ix+-1)
jp      nz,L14
or      a
jp      z,cret
ld      hl,10
push    hl
call    _fputchar
jp      cret
global  _prJmpLabel
_prJmpLabel:
global csv
call csv
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
ld      hl,479f
push    hl
call    _printf
jp      cret
global  _prJump
_prJump:
global csv
call csv
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
ld      hl,489f
push    hl
call    _printf
jp      cret
global  _sub_15FB
global  wrelop
global  wrelop
global  wrelop
_sub_15FB:
global csv
call csv
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
bit     7,(ix+9)
jp      nz,l123
ld      (iy+21),2
ld      e,(ix+10)
ld      d,(ix+11)
ld      hl,255
call    wrelop
jp      m,L18
ld      (iy+9),1
L17:
ld      (iy+10),0
jp      cret
L18:
ld      (iy+9),2
jp      L17
l123:
ld      (iy+21),1
ld      e,(ix+10)
ld      d,(ix+11)
ld      hl,127
call    wrelop
jp      m,L18
ld      de,-128
ld      l,(ix+8)
ld      h,(ix+9)
call    wrelop
jp      m,L18
ld      (iy+9),1
jp      L17
global  _max
global  wrelop
_max:
global csv
call csv
ld      e,(ix+6)
ld      d,(ix+7)
ld      l,(ix+8)
ld      h,(ix+9)
call    wrelop
jp      m,L20
ld      l,(ix+8)
ld      h,(ix+9)
jp      cret
L20:
ld      l,(ix+6)
ld      h,(ix+7)
jp      cret
global  _sub_1680
psect   data
F503:
defw    499f
defw    2
defw    0
defb    1
defw    509f
defw    2
defw    0
defb    1
defw    519f
defw    1
defw    0
defb    1
defw    529f
defw    4
defw    0
defb    1
defw    539f
defw    2
defw    0
defb    2
defw    549f
defw    2
defw    0
defb    2
defw    559f
defw    1
defw    0
defb    2
defw    569f
defw    4
defw    0
defb    2
defw    579f
defw    4
defw    0
defb    3
defw    589f
defw    4
defw    0
defb    3
defw    599f
defw    2
defw    0
defb    1
defw    609f
defw    2
defw    0
defb    2
defw    619f
defw    0
defw    0
defb    0
defw    629f
defw    0
defw    0
defb    0
global  _blkclr
global  _hashtab
global  _typeLong
global  _typeDouble
global  _typeB
global  _typeVar
global  _typeChar
global  _typeUChar
global  _typeX
global  _lvlidx
psect   text
_sub_1680:
global csv
call csv
push hl
push hl
ld      hl,202
push    hl
ld      hl,_hashtab
push    hl
call    _blkclr
pop     bc
pop     bc
ld      (ix+-4),14
ld      (ix+-3),0
ld      iy,F503
l134:
ld      l,(iy+0)
ld      h,(iy+1)
push    hl
call    _sub_265
pop     bc
ld      (ix+-2),l
ld      (ix+-1),h
inc     hl
inc     hl
ld      (hl),65
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      hl,17
add     hl,de
ld      e,(iy+4)
ld      d,(iy+5)
ld      (hl),e
inc     hl
ld      (hl),d
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      hl,9
add     hl,de
ld      e,(iy+2)
ld      d,(iy+3)
ld      (hl),e
inc     hl
ld      (hl),d
ld      a,(iy+6)
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      hl,21
add     hl,de
ld      (hl),a
ld      de,7
add     iy,de
ld      l,(ix+-4)
ld      h,(ix+-3)
dec     hl
ld      (ix+-4),l
ld      (ix+-3),h
ld      a,l
or      h
jp      nz,l134
ld      hl,639f
push    hl
call    _sub_265
ld      (_typeLong),hl
ld      hl,649f
ex      (sp),hl
call    _sub_265
ld      (_typeDouble),hl
ld      hl,659f
ex      (sp),hl
call    _sub_265
ld      (_typeB),hl
ld      hl,669f
ex      (sp),hl
call    _sub_265
ld      (_typeVar),hl
ld      hl,679f
ex      (sp),hl
call    _sub_265
ld      (_typeChar),hl
ld      hl,689f
ex      (sp),hl
call    _sub_265
ld      (_typeUChar),hl
ld      hl,699f
ex      (sp),hl
call    _sub_265
ld      (_typeX),hl
ld      hl,-1
ld      (_lvlidx),hl
jp      cret
psect   bss
F505:
defs    2
psect   text
_newLocal:
ld      hl,(F505)
inc     hl
ld      (F505),hl
ret
global  _sub_1754
global  _nstdpth
global  _gethashptr
global  _allocMem
global  _strlen

IF RAM128

global  _MyAlloc

global  _PutString

ENDIF

_sub_1754:
global csv
call csv
push hl
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
call    _sub_265
pop     bc
push    hl
pop     iy
ld      de,(_nstdpth)
ld      l,(iy+4)
ld      h,0
or      a
sbc     hl,de
jp      z,l137
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
call    _gethashptr
ld      (ix+-2),l
ld      (ix+-1),h
ld      hl,22
ex      (sp),hl
call    _allocMem
pop     bc
push    hl
pop     iy
ld      l,(ix+-2)
ld      h,(ix+-1)
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (iy+7),c
ld      (iy+8),b
push    iy
pop     de
dec     hl
ld      (hl),e
inc     hl
ld      (hl),d
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
call    _strlen
pop     bc
inc     hl
push    hl

IF RAM128

call    _MyAlloc

ELSE

call    _allocMem

ENDIF

ld      (iy+0),l
ld      (iy+1),h

IF RAM128

ex      (sp),hl
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
call    _PutString

ELSE

ld      l,(ix+6)
ld      h,(ix+7)
ex      (sp),hl
ld      l,(iy+0)
ld      h,(iy+1)
push    hl
call    _strcpy

ENDIF

pop     bc
pop     bc
ld      a,(_nstdpth)
ld      (iy+4),a
l137:
ld      a,(ix+8)
ld      (iy+2),a
;push    iy
;pop     hl
;jp      cret
jp	pushIYpopHLcret
psect   data
19:
defb    84,111,111,32,109,97,110,121,32,105,110,105,116,105,97,108
defb    105,122,101,114,115,0
29:
defb    103,108,111,98,97,108,9,110,99,115,118,44,32,99,114,101
defb    116,44,32,105,110,100,105,114,10,0
39:
defb    99,97,108,108,9,110,99,115,118,10,0
49:
defb    100,101,102,119,9,102,37,100,10,0
59:
defb    106,112,9,99,114,101,116,10,102,37,100,9,101,113,117,9
defb    37,100,10,0
69:
defb    108,100,9,100,101,44,107,37,100,10,108,100,9,98,99,44
defb    37,100,10,108,100,105,114,10,108,100,9,104,108,44,107,37
defb    100,10,0
79:
defb    107,37,100,58,100,101,102,115,9,37,100,10,0
89:
defb    103,108,111,98,97,108,9,37,115,10,0
99:
defb    9,100,101,102,115,9,37,117,10,0
109:
defb    37,115,58,10,0
119:
defb    100,101,102,98,9,48,0
129:
defb    44,48,0
139:
defb    0
149:
defb    98,115,115,0
159:
defb    116,101,120,116,0
169:
defb    100,97,116,97,0
179:
defb    112,115,101,99,116,9,37,115,10,0
189:
defb    68,117,112,108,105,99,97,116,101,32,99,97,115,101,32,108
defb    97,98,101,108,0
199:
defb    78,111,32,99,97,115,101,9,108,97,98,101,108,115,0
209:
defb    106,112,9,108,37,100,10,0
219:
defb    78,111,110,45,99,111,110,115,116,97,110,116,32,99,97,115
defb    101,32,108,97,98,101,108,0
229:
defb    117,115,0
239:
defb    108,100,9,97,44,37,117,10,99,112,9,104,10,106,112,9
defb    99,44,108,37,100,10,106,112,9,110,122,44,49,102,10,108
defb    100,9,97,44,37,117,10,99,112,9,108,10,106,112,9,99
defb    44,108,37,100,10,49,58,97,100,100,9,104,108,44,104,108
defb    10,108,100,9,100,101,44,83,37,117,10,97,100,100,9,104
defb    108,44,100,101,10,108,100,9,97,44,40,104,108,41,10,105
defb    110,99,9,104,108,10,108,100,9,104,44,40,104,108,41,10
defb    108,100,9,108,44,97,10,106,112,9,40,104,108,41,10,0
249:
defb    83,37,100,58,10,0
259:
defb    100,101,102,119,9,108,37,100,10,0
269:
defb    100,101,102,119,9,108,37,100,10,0
279:
defb    49,58,10,0
289:
defb    108,100,9,97,44,104,10,0
299:
defb    106,112,9,110,122,44,49,102,10,108,100,9,97,44,108,10
defb    0
309:
defb    49,58,10,0
319:
defb    108,100,9,97,44,108,10,0
329:
defb    106,112,9,110,122,44,49,102,10,108,100,9,97,44,104,10
defb    0
339:
defb    106,112,9,122,44,108,37,100,10,0
349:
defb    49,58,10,0
359:
defb    106,112,9,108,37,100,10,0
369:
defb    106,112,9,122,44,108,37,100,10,0
379:
defb    106,112,9,108,37,100,10,0
389:
defb    99,112,9,37,100,10,0
399:
defb    111,114,9,97,10,0
409:
defb    112,117,115,104,9,104,108,10,112,117,115,104,9,100,101,10
defb    0
419:
defb    112,117,115,104,9,37,115,10,0
429:
defb    112,111,112,9,100,101,10,112,111,112,9,104,108,10,0
439:
defb    112,111,112,9,37,115,10,0
449:
defb    108,100,9,108,44,40,105,120,43,37,100,41,10,108,100,9
defb    104,44,40,105,120,43,37,100,41,10,112,117,115,104,9,104
defb    108,10,112,111,112,9,105,121,10,0
459:
defb    100,101,102,98,9,0
469:
defb    37,100,0
479:
defb    106,37,100,58,10,0
489:
defb    106,112,9,106,37,100,10,0
499:
defb    105,0
509:
defb    115,0
519:
defb    99,0
529:
defb    108,0
539:
defb    117,105,0
549:
defb    117,115,0
559:
defb    117,99,0
569:
defb    117,108,0
579:
defb    102,0
589:
defb    100,0
599:
defb    120,0
609:
defb    117,120,0
619:
defb    98,0
629:
defb    118,0
639:
defb    108,0
649:
defb    100,0
659:
defb    98,0
669:
defb    118,0
679:
defb    99,0
689:
defb    117,99,0
699:
defb    120,0
psect   text

