include cgen.inc
global  _sub_5CF5
global  ncsv, cret, indir
global  _sub_61AA
global  _array_AE13
global  _lvlidx
global  wrelop
global  wrelop

IF RAM128

global  _GetString
global  _tmpBuf

ENDIF

global  _prWarning
global  _array_AE97
global  _sub_C57
psect   text
_sub_5CF5:
global csv
call csv
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
ld      a,(iy+21)
cp      1
jp      z,l13
cp      3
jp      z,l20
cp      4
jp      z,l20
cp      5
jp      z,l16
jp      cret
l13:
ld      l,(ix+8)
ld      h,(ix+9)
push    hl
push    iy
call    _sub_61AA
pop     bc
pop     bc
ld      a,l
or      a
jp      nz,cret
ld      c,(iy+9)
ld      b,(iy+10)
ld      de,_array_AE13
ld      hl,(_lvlidx)
add     hl,hl
add     hl,de
ld      e,(hl)
inc     hl
ld      d,(hl)
ex      de,hl
or      a
sbc     hl,bc
ex      de,hl
ld      (hl),d
dec     hl
ld      (hl),e
ex      de,hl
ld      de,_array_AE13
ld      hl,(_lvlidx)
add     hl,hl
add     hl,de
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
ld      (iy+17),l
ld      (iy+18),h
ld      de,-128
call    wrelop
jp      p,cret
ld      e,(iy+9)
ld      d,(iy+10)
ld      hl,4
call    wrelop
jp      c,cret
ld      l,(iy+0)
ld      h,(iy+1)
push    hl

IF RAM128

ld      hl,_tmpBuf
push    hl
call    _GetString
pop     bc
ld      hl,_tmpBuf
ex      (sp),hl

ENDIF

ld      hl,19f
push    hl
call    _prWarning
pop     bc
L1:
;pop     bc
;jp      cret
jp	popBCcret
l16:
ld      de,_array_AE97
ld      hl,(_lvlidx)
add     hl,hl
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (iy+17),c
ld      (iy+18),b
ld      c,(iy+9)
ld      b,(iy+10)
ld      hl,(_lvlidx)
add     hl,hl
add     hl,de
ld      e,(hl)
inc     hl
ld      d,(hl)
ex      de,hl
add     hl,bc
ex      de,hl
ld      (hl),d
dec     hl
ld      (hl),e
ex      de,hl

;ld      de,1
;ld      l,c
;ld      h,b
;or      a
;sbc     hl,de
ld	a,c
cp	1

jp      nz,l17
ld      l,(iy+15)
ld      h,(iy+16)
inc     hl
inc     hl
ld      a,(hl)
cp      55
jp      z,l17
ld      a,(hl)
cp      56
jp      z,l17
ld      de,_array_AE97
ld      hl,(_lvlidx)
add     hl,hl
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
inc     bc
ld      (hl),b
dec     hl
ld      (hl),c
l17:
ld      l,(ix+8)
ld      h,(ix+9)
push    hl
push    iy
call    _sub_61AA
pop     bc
pop     bc
ld      a,l
or      a
jp      nz,cret
ld      (iy+21),1
jp      cret
l20:
push    iy
call    _sub_C57
jp      L1
global  _sub_5DF6
global  _dopetab
global  _sub_43EF
global  _freeNode
global  _strlen
global  _strcpy
global  _strcat

IF RAM128

global  _MyAlloc
global  _PutString
global  _Free128
_sub_5DF6:
call ncsv
defw -63

ELSE

global _allocMem
global _free
_sub_5DF6:
global csv
call csv
push hl
push hl

ENDIF

ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
ld      de,_dopetab
ld      l,(iy+0)
ld      h,0
add     hl,hl
add     hl,de
ld      a,(hl)
and     12
ld      (ix+-1),a
cp      8
jp      nz,l22
ld      l,(iy+27)
ld      h,(iy+28)
push    hl
call    _sub_5DF6
pop     bc
ld      (iy+27),l
ld      (iy+28),h
l22:
ld      a,(ix+-1)
or      a
jp      z,l25
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
call    _sub_5DF6
pop     bc
ld      (iy+25),l
ld      (iy+26),h
l25:
ld      a,(iy+0)
cp      18
jp      z,l27
cp      21
jp      z,l30
cp      38
jp      nz,l24
l27:
ld      l,(iy+27)
ld      h,(iy+28)
ld      a,(hl)
cp      67
jp      nz,l28
ex      de,hl
ld      hl,25
add     hl,de
ld      e,(hl)
inc     hl
ld      d,(hl)
inc     hl
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
push    hl
push    de
ld      hl,0
pop     bc
or      a
sbc     hl,bc
pop     bc
ex      de,hl
ld      hl,0
sbc     hl,bc
push    hl
push    de
ld      e,(iy+27)
ld      d,(iy+28)
ld      hl,25
add     hl,de
pop     de
ld      (hl),e
inc     hl
ld      (hl),d
inc     hl
pop     bc
ld      (hl),c
inc     hl
ld      (hl),b
ld      l,c
ld      h,b
jp      l29
l28:
ld      hl,0
push    hl
ld      l,(iy+27)
ld      h,(iy+28)
push    hl
ld      l,21
push    hl
call    _sub_43EF
pop     bc
pop     bc
pop     bc
ld      (iy+27),l
ld      (iy+28),h
l29:
ld      a,(iy+0)
cp      18
jp      z,L3
ld      hl,37
jp      L2
L3:
ld      hl,14
L2:
ld      (iy+0),l
l24:
push    iy
L4:
;pop     hl
;jp      cret
jp	popHLcret
l30:
ld      l,(iy+25)
ld      h,(iy+26)
ld      a,(hl)
cp      21
jp      nz,l31
push    iy
call    _freeNode
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
pop     iy
ex      (sp),hl
call    _freeNode
pop     bc
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
pop     iy
l31:
ld      l,(iy+25)
ld      h,(iy+26)
ld      a,(hl)
cp      68
push    iy
jp      nz,L4
call    _freeNode
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
pop     iy
ld      l,(iy+25)
ld      h,(iy+26)
ex      (sp),hl
call    _strlen
pop     bc
inc     hl
inc     hl
push    hl

IF RAM128

call    _MyAlloc

ELSE

call    _allocMem

ENDIF

ld      (ix+-3),l
ld      (ix+-2),h
ld      l,(iy+25)
ld      h,(iy+26)
ex      (sp),hl

IF RAM128

push    ix
pop     de
ld      hl,-63
add     hl,de
push    hl
call    _GetString
pop     bc
ld      hl,29f
ex      (sp),hl
ld      hl,_tmpBuf
push    hl
call    _strcpy
pop     bc
push    ix
pop     de
ld      hl,-63
add     hl,de
ex      (sp),hl
ld      hl,_tmpBuf
push    hl
call    _strcat
pop     bc
ld      l,(ix+-3)
ld      h,(ix+-2)
ex      (sp),hl
ld      hl,_tmpBuf
push    hl
call    _PutString
pop     bc
ld      l,(iy+25)
ld      h,(iy+26)
ex      (sp),hl
call    _Free128

ELSE

ld      hl,29f
push    hl
ld      l,(ix+-3)
ld      h,(ix+-2)
push    hl
call    _strcpy
pop     bc
ex      (sp),hl
call    _strcat
pop     bc
ld      l,(iy+25)
ld      h,(iy+26)
ex      (sp),hl
call    _free

ENDIF

pop     bc
ld      l,(ix+-3)
ld      h,(ix+-2)
ld      (iy+25),l
ld      (iy+26),h
jp      l24
global  _sub_5F52
_sub_5F52:
global csv
call csv
push hl
push hl
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
ld      de,_dopetab
ld      l,(iy+0)
ld      h,0
add     hl,hl
add     hl,de
ld      a,(hl)
and     12
ld      (ix+-1),a
cp      8
jp      nz,l34
ld      l,(iy+27)
ld      h,(iy+28)
push    hl
call    _sub_5F52
pop     bc
ld      (iy+27),l
ld      (iy+28),h
l34:
ld      a,(ix+-1)
or      a
jp      z,l37
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
call    _sub_5F52
pop     bc
ld      (iy+25),l
ld      (iy+26),h
l37:
ld      a,(iy+0)
cp      14
jp      z,l38
cp      37
jp      z,l40
l36:
;push    iy
;pop     hl
;jp      cret
jp	pushIYpopHLcret
l38:
ld      l,(iy+25)
ld      h,(iy+26)
ld      a,(hl)
cp      21
jp      nz,l40
ld      (ix+-3),l
ld      (ix+-2),h
ld      l,(iy+27)
ld      h,(iy+28)
ld      (iy+25),l
ld      (iy+26),h
ld      l,(ix+-3)
ld      h,(ix+-2)
ld      (iy+27),l
ld      (iy+28),h
l40:
ld      l,(iy+27)
ld      h,(iy+28)
ld      a,(hl)
cp      21
jp      nz,l36
push    hl
call    _freeNode
pop     bc
ld      e,(iy+27)
ld      d,(iy+28)
ld      hl,25
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (iy+27),c
ld      (iy+28),b
ld      a,(iy+0)
cp      37
jp      z,L6
ld      hl,18
jp      L5
L6:
ld      hl,38
L5:
ld      (iy+0),l
jp      l36
global  _sub_600E
global  _warningMsg
global  _byte_B013
global  _sub_3EAA
global  _sub_54B6
_sub_600E:
global csv
call csv
push hl
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
ld      hl,0
ld      (_warningMsg),hl
push    iy
call    _sub_5DF6
pop     bc
push    hl
pop     iy
ld      (ix+-2),0
ld      (ix+-1),0
l45:
xor     a
ld      (_byte_B013),a
push    iy
call    _sub_54B6
ex      (sp),hl
call    _sub_3EAA
pop     bc
push    hl
pop     iy
ld      a,(_byte_B013)
or      a
jp      nz,l45
ld      hl,(_warningMsg)
ld      a,l
or      h
jp      z,l46
push    hl
call    _prWarning
pop     bc
l46:
push    iy
call    _sub_5F52
;pop     bc
;jp      cret
jp	popBCcret
global  _invertTest
_invertTest:
global csv
call csv
ld      l,(ix+6)
ld      h,(ix+7)
ld      a,h
or      a
jp      nz,l48
ld      a,l
cp      2
jp      z,l48
cp      30
jp      z,l52
cp      32
jp      z,l53
cp      41
jp      z,l50
cp      45
jp      z,l55
cp      46
jp      z,l54
l48:
ld      hl,41
jp      cret
l50:
ld      hl,2
jp      cret
l52:
ld      hl,46
jp      cret
l53:
ld      hl,45
jp      cret
l54:
ld      hl,30
jp      cret
l55:
ld      hl,32
jp      cret
global  _sub_60A8
global  _nodesize
global  wrelop
global  _sub_14F3
global  shll
global  asaldiv
global  arelop
global  arelop
_sub_60A8:
global csv
call csv
push hl
push hl
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
ld      a,(iy+0)
cp      67
jp      z,l57
L13:
;ld      l,0
;jp      cret
jp	ldL0cret
l57:
ld      l,(ix+8)
ld      h,(ix+9)
push    hl
call    _nodesize
pop     bc
ld      de,4
call    wrelop
jp      c,l58
bit     7,(iy+28)
jp      z,L12
ld      l,(ix+8)
ld      h,(ix+9)
push    hl
call    _sub_14F3
pop     bc
ld      a,l
cp      1
jp      nz,L11
L12:
;ld      hl,1
;jp      cret
jp	ldHL1cret
L11:
;ld      hl,0
;jp      cret
jp	ldHL0cret
l58:
ld      l,(ix+8)
ld      h,(ix+9)
push    hl
call    _nodesize
pop     bc
add     hl,hl
add     hl,hl
add     hl,hl
ld      b,l
ld      hl,1
call    shll
ex      de,hl
ld      hl,0
ld      (ix+-4),e
ld      (ix+-3),d
ld      (ix+-2),l
ld      (ix+-1),h
ld      l,(ix+8)
ld      h,(ix+9)
push    hl
call    _sub_14F3
pop     bc
ld      a,l
cp      2
jp      nz,l59
bit     7,(iy+28)
jp      nz,L13
ld      e,(ix+-4)
ld      d,(ix+-3)
ld      l,(ix+-2)
ld      h,(ix+-1)
push    hl
push    de
L15:
ld      e,(iy+25)
ld      d,(iy+26)
ld      l,(iy+27)
ld      h,(iy+28)
call    arelop
ld      bc,1
jp      m,L14
dec     bc
L14:
ld      l,c
jp      cret
l59:
ld      de,2
ld      hl,0
push    hl
push    de
push    ix
pop     hl
dec     hl
dec     hl
dec     hl
dec     hl
call    asaldiv
bit     7,(iy+28)
ld      e,(ix+-4)
ld      d,(ix+-3)
ld      l,(ix+-2)
ld      h,(ix+-1)
push    hl
push    de
jp      z,L15
ld      hl,0
pop     bc
or      a
sbc     hl,bc
pop     bc
ex      de,hl
ld      hl,0
sbc     hl,bc
push    hl
push    de
ld      e,(iy+25)
ld      d,(iy+26)
ld      l,(iy+27)
ld      h,(iy+28)
call    arelop
ld      bc,1
jp      p,L14
dec     bc
jp      L14
global  _rflag
global  __ctype_
global  wrelop
global  _sub_6589
global  _word_B017
global  _array_AAE8
_sub_61AA:
global csv
call csv
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
ld      a,(_rflag)
or      a
jp      nz,L16
ld      e,(ix+8)
ld      d,(ix+9)
ld      hl,__ctype_+1
add     hl,de
bit     0,(hl)
jp      z,L16

;ld      de,1
;ld      l,(iy+13)
;ld      h,(iy+14)
;or      a
;sbc     hl,de
ld	a,(iy+13)
cp	1

jp      nz,L16
ld      e,(iy+11)
ld      d,(iy+12)
ld      hl,1
call    wrelop
jp      c,L16
ld      hl,9
push    hl
ld      hl,(_word_B017)
push    hl
call    _sub_6589
pop     bc
pop     bc
ld      a,l
or      a
jp      nz,l65
L16:
;ld      l,0
;jp      cret
jp	ldL0cret
l65:
ld      a,(iy+21)
cp      5
jp      nz,l66
set     2,(iy+3)
l66:
ld      (iy+21),2
ld      hl,9
push    hl
ld      hl,(_word_B017)
push    hl
call    _sub_6589
pop     bc
pop     bc
ld      h,0
ld      (iy+19),l
ld      (iy+20),h
ld      de,_array_AAE8
ld      h,(iy+20)
add     hl,hl
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      hl,-1
or      a
sbc     hl,bc
ex      de,hl
ld      hl,(_word_B017)
ld      a,l
and     e
ld      l,a
ld      a,h
and     d
ld      h,a
ld      (_word_B017),hl
;ld      l,1
;jp      cret
jp	ldL1cret
global  _sub_6246
_sub_6246:
global csv
call csv
ld      l,(ix+8)
ld      h,(ix+9)
push    hl
call    _nodesize
ex      (sp),hl
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
call    _nodesize
pop     bc
pop     de
or      a
sbc     hl,de
jp      nz,L18
ld      l,(ix+8)
ld      h,(ix+9)
push    hl
call    _sub_14F3
pop     bc
ld      e,l
push    de
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
call    _sub_14F3
pop     bc
ld      a,l
pop     de
cp      e
jp      nz,L18
;ld      hl,1
;jp      cret
jp	ldHL1cret
L18:
;ld      hl,0
;jp      cret
jp	ldHL0cret
global  _sub_628F
_sub_628F:
global csv
call csv
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
call    _sub_14F3
pop     bc
ld      a,l
cp      1
jp      nz,L23
ld      l,(ix+8)
ld      h,(ix+9)
push    hl
call    _sub_14F3
pop     bc
ld      a,l
cp      1
jp      nz,L23
;ld      hl,1
;jp      cret
jp	ldHL1cret
L23:
;ld      hl,0
;jp      cret
jp	ldHL0cret
global  _sub_62BE
global  brelop
global  allsh
global  asaldiv
global  arelop
global  arelop
_sub_62BE:
call ncsv
defw -9
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
call    _nodesize
pop     bc
add     hl,hl
add     hl,hl
add     hl,hl
ld      (ix+-9),l
ld      b,32
ld      a,l
call    brelop
jp      m,l70
;ld      l,1
;jp      cret
jp	ldL1cret
l70:
ld      b,(ix+-9)
ld      de,1
ld      hl,0
call    allsh
ld      (ix+-4),e
ld      (ix+-3),d
ld      (ix+-2),l
ld      (ix+-1),h
ld      (ix+-8),0
ld      (ix+-7),0
ld      (ix+-6),0
ld      (ix+-5),0
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
push    iy
call    _sub_628F
pop     bc
pop     bc
ld      a,l
or      a
jp      z,l71
ld      de,2
ld      hl,0
push    hl
push    de
push    ix
pop     hl
dec     hl
dec     hl
dec     hl
dec     hl
call    asaldiv
ld      e,(ix+-4)
ld      d,(ix+-3)
ld      l,(ix+-2)
ld      h,(ix+-1)
push    hl
push    de
ld      hl,0
pop     bc
or      a
sbc     hl,bc
pop     bc
ex      de,hl
ld      hl,0
sbc     hl,bc
ld      (ix+-8),e
ld      (ix+-7),d
ld      (ix+-6),l
ld      (ix+-5),h
l71:
ld      e,(ix+-8)
ld      d,(ix+-7)
ld      l,(ix+-6)
ld      h,(ix+-5)
push    hl
push    de
ld      e,(ix+8)
ld      d,(ix+9)
ld      hl,25
add     hl,de
ld      e,(hl)
inc     hl
ld      d,(hl)
inc     hl
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
call    arelop
jp      m,L28
ld      e,(ix+-4)
ld      d,(ix+-3)
ld      l,(ix+-2)
ld      h,(ix+-1)
push    hl
push    de
ld      e,(ix+8)
ld      d,(ix+9)
ld      hl,25
add     hl,de
ld      e,(hl)
inc     hl
ld      d,(hl)
inc     hl
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
call    arelop
jp      p,L28
;ld      hl,1
;jp      cret
jp	ldHL1cret
L28:
;ld      hl,0
;jp      cret
jp	ldHL0cret
global  _sub_63B8
global  wrelop
global  _array_AB54
global  amul
_sub_63B8:
global csv
call csv
push hl
push hl
res     6,(ix+10)
ld      (ix+-1),0
ld      a,(ix+8)
or      (ix+9)
jp      nz,l73
ld      l,(ix+10)
ld      h,(ix+11)
push    hl
ld      l,(ix+6)
ld      h,(ix+7)
L42:
push    hl
call    _sub_6589
pop     bc
pop     bc
ld      e,l
ld      (ix+-1),e
jp      l74
l73:
xor     a
ld      l,a
ld      a,(ix+9)
and     128
ld      h,a
ld      a,l
or      h
jp      z,l75
ld      l,(ix+10)
ld      h,(ix+11)
push    hl
xor     a
ld      l,a
ld      a,(ix+9)
and     128
ld      h,a
ld      a,l
or      h
jp      nz,L41
ld      de,_array_AAE8
ld      l,(ix+8)
ld      h,(ix+9)
add     hl,hl
add     hl,de
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
jp      L40
L41:
ld      e,(ix+8)
ld      d,(ix+9)
ld      hl,-1
or      a
sbc     hl,de
L40:
ld      a,l
and     (ix+6)
ld      l,a
ld      a,h
and     (ix+7)
ld      h,a
jp      L42
l75:
ld      de,24
ld      l,(ix+10)
ld      h,(ix+11)
call    wrelop
jp      p,l77
ld      l,(ix+10)
ld      h,(ix+11)
push    hl
xor     a
ld      l,a
ld      a,(ix+9)
and     128
ld      h,a
ld      a,l
or      h
jp      nz,L39
ld      de,_array_AAE8
ld      l,(ix+8)
ld      h,(ix+9)
add     hl,hl
add     hl,de
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
jp      L38
L39:
ld      e,(ix+8)
ld      d,(ix+9)
ld      hl,-1
or      a
sbc     hl,de
L38:
ld      a,l
and     (ix+6)
ld      l,a
ld      a,h
and     (ix+7)
ld      h,a
push    hl
call    _sub_6589
pop     bc
pop     bc
ld      a,l
ld      (ix+-1),a
or      a
jp      nz,l74
ld      l,(ix+10)
ld      h,(ix+11)
push    hl
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
call    _sub_6589
pop     bc
pop     bc
ld      e,l
ld      h,0
ld      (ix+-4),l
ld      (ix+-3),h
ld      a,l
or      h
jp      z,l74
ld      l,(ix+8)
ld      h,(ix+9)
push    hl
xor     a
ld      l,a
ld      a,(ix+-3)
and     128
ld      h,a
ld      a,l
or      h
jp      nz,L37
ld      de,_array_AAE8
ld      l,(ix+-4)
ld      h,(ix+-3)
add     hl,hl
add     hl,de
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
jp      L36
L37:
ld      e,(ix+-4)
ld      d,(ix+-3)
ld      hl,-1
or      a
sbc     hl,de
L36:
push    hl
call    _sub_6589
pop     bc
pop     bc
ld      a,l
or      a
jp      z,l74
ld      a,(ix+-4)
L43:
ld      (ix+-1),a
jp      l74
l77:
ld      (ix+-4),6
ld      (ix+-3),0
ld      e,(ix+10)
ld      d,(ix+11)
ld      hl,-24
add     hl,de
ld      de,6
call    amul
ld      de,_array_AB54
add     hl,de
push    hl
pop     iy
l83:
ld      a,(iy+0)
or      a
jp      nz,L33
jp      l74
l81:
push    iy
pop     hl
inc     hl
push    hl
pop     iy
dec     hl
ld      l,(hl)
ld      h,0
push    hl
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
call    _sub_6589
pop     bc
pop     bc
ld      a,l
ld      (ix+-2),a
or      a
jp      z,l83
ld      l,(ix+8)
ld      h,(ix+9)
push    hl
ld      de,_array_AAE8
ld      l,a
ld      h,0
add     hl,hl
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
call    _sub_6589
pop     bc
pop     bc
ld      a,l
or      a
jp      nz,L34
ld      l,(ix+-2)
ld      h,0
push    hl
ld      de,_array_AAE8
ld      l,(ix+8)
ld      h,(ix+9)
add     hl,hl
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
call    _sub_6589
pop     bc
pop     bc
ld      a,l
or      a
jp      z,l83
L34:
ld      a,(ix+-2)
jp      L43
L33:
ld      l,(ix+-4)
ld      h,(ix+-3)
dec     hl
ld      (ix+-4),l
ld      (ix+-3),h
inc     hl
ld      a,l
or      h
jp      nz,l81
l74:
ld      l,(ix+-1)
jp      cret
global  wrelop
global  amul
_sub_6589:
global csv
call csv
push hl
push hl
res     6,(ix+8)
ld      de,24
ld      l,(ix+8)
ld      h,(ix+9)
call    wrelop
jp      p,l85
ld      de,_array_AAE8
ld      l,(ix+8)
ld      h,(ix+9)
add     hl,hl
add     hl,de
ld      e,(hl)
inc     hl
ld      d,(hl)
push    de
ld      de,_array_AAE8
ld      l,(ix+8)
ld      h,(ix+9)
add     hl,hl
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      a,(ix+6)
and     c
ld      l,a
ld      a,(ix+7)
and     b
ld      h,a
pop     de
or      a
sbc     hl,de
jp      nz,L46
ld      l,(ix+8)
jp      cret
l85:
ld      de,-24
ld      l,(ix+8)
ld      h,(ix+9)
add     hl,de
ld      (ix+8),l
ld      (ix+9),h
ld      (ix+-1),6
ld      de,6
call    amul
ld      de,_array_AB54
add     hl,de
ld      (ix+-3),l
ld      (ix+-2),h
l90:
ld      l,(ix+-3)
ld      h,(ix+-2)
ld      a,(hl)
or      a
jp      z,l88
ld      de,_array_AAE8
ld      l,(hl)
ld      h,0
add     hl,hl
add     hl,de
ld      e,(hl)
inc     hl
ld      d,(hl)
push    de
ld      de,_array_AAE8
ld      l,(ix+-3)
ld      h,(ix+-2)
ld      l,(hl)
ld      h,0
add     hl,hl
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      a,(ix+6)
and     c
ld      l,a
ld      a,(ix+7)
and     b
ld      h,a
pop     de
or      a
sbc     hl,de
ld      l,(ix+-3)
ld      h,(ix+-2)
jp      nz,L47
ld      l,(hl)
jp      cret
l88:
ld      l,(ix+-3)
ld      h,(ix+-2)
L47:
inc     hl
ld      (ix+-3),l
ld      (ix+-2),h
ld      a,(hl)
or      a
jp      z,L46
dec     (ix+-1)
jp      nz,l90
L46:
;ld      l,0
;jp      cret
jp	ldL0cret
global  _sub_665B
global  _array_AB24
global  wrelop
_sub_665B:
global csv
call csv
push hl
ld      a,(ix+6)
or      (ix+7)
jp      nz,l93
L48:
;ld      hl,0
;jp      cret
jp	ldHL0cret
l93:
ld      a,(ix+8)
add     a,208
ld      (ix+8),a
ld      (ix+-2),1
ld      (ix+-1),0
jp      l97
l94:
ld      e,(ix+8)
ld      d,0
ld      l,(ix+-2)
ld      h,(ix+-1)
add     hl,hl
add     hl,de
ld      de,_array_AB24
add     hl,de
ld      l,(hl)
ld      h,0
ld      e,(ix+6)
ld      d,(ix+7)
or      a
sbc     hl,de
ld      l,(ix+-2)
ld      h,(ix+-1)
jp      z,cret
inc     hl
ld      (ix+-2),l
ld      (ix+-1),h
l97:
ld      de,24
ld      l,(ix+-2)
ld      h,(ix+-1)
call    wrelop
jp      c,l94
jp      L48
global  _sub_66BC
global  wrelop
_sub_66BC:
call ncsv
defw -6
ld      (ix+-4),0
ld      (ix+-3),0
xor     a
ld      l,a
ld      a,(ix+9)
and     128
ld      h,a
ld      a,l
or      h
ld      a,(ix+6)
jp      z,L62
or      (ix+7)
jp      nz,l101
ld      l,(ix+8)
ld      h,(ix+9)
L70:
ld      (ix+-4),l
L73:
ld      (ix+-3),h
jp      l105
l101:
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
xor     a
ld      l,a
ld      a,(ix+9)
and     128
ld      h,a
ld      a,l
or      h
jp      nz,L61
ld      de,_array_AAE8
ld      l,(ix+8)
ld      h,(ix+9)
add     hl,hl
add     hl,de
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
jp      L60
L61:
ld      e,(ix+8)
ld      d,(ix+9)
ld      hl,-1
or      a
sbc     hl,de
L60:
ld      a,l
and     (ix+10)
ld      l,a
ld      a,h
and     (ix+11)
ld      h,a
push    hl
call    _sub_6589
pop     bc
pop     bc
ld      e,l
ld      h,0
ld      (ix+-2),l
ld      (ix+-1),h
ld      a,l
or      h
jp      z,l103
ld      h,(ix+-1)
jp      L70
l103:
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
ld      l,(ix+10)
ld      h,(ix+11)
push    hl
call    _sub_6589
pop     bc
pop     bc
ld      e,l
ld      h,0
jp      L70
L62:
or      (ix+7)
ld      a,(ix+8)
jp      nz,L63
or      (ix+9)
jp      z,L72
ld      a,(ix+12)
or      (ix+13)
jp      nz,l107
L72:
ld      l,(ix+8)
ld      h,(ix+9)
jp      L70
l107:
ld      l,(ix+12)
ld      h,(ix+13)
ld      (ix+-6),l
ld      (ix+-5),h
jp      l112
l111:
ld      l,(ix+-6)
ld      h,(ix+-5)
inc     hl
ld      (ix+-6),l
ld      (ix+-5),h
l112:
ld      l,(ix+-6)
ld      h,(ix+-5)
inc     hl

;ld      a,(hl)
;ld      e,a
;rla
;sbc     a,a
;ld      d,a
ld	e,(hl)
ld	d,0

ld      hl,__ctype_+1
add     hl,de
bit     2,(hl)
jp      nz,l111
ld      de,24
ld      l,(ix+8)
ld      h,(ix+9)
call    wrelop
jp      m,l117
ld      l,(ix+8)
ld      h,(ix+9)
push    hl
ld      l,(ix+10)
ld      h,(ix+11)
push    hl
call    _sub_6589
pop     bc
pop     bc
ld      e,l
ld      h,0
ld      (ix+8),l
ld      (ix+9),h
ld      a,l
or      h
jp      nz,l117
ld      (ix+-4),h
jp      L73
l117:
ld      l,(ix+-6)
ld      h,(ix+-5)
ld      l,(hl)
push    hl
ld      l,(ix+8)
ld      h,(ix+9)
push    hl
call    _sub_665B
pop     bc
pop     bc
ld      (ix+8),l
ld      (ix+9),h
ld      e,(ix+12)
ld      d,(ix+13)
ld      l,(ix+-6)
ld      h,(ix+-5)
dec     hl
ld      (ix+-6),l
ld      (ix+-5),h
inc     hl
or      a
sbc     hl,de
jp      nz,l117
jp      L72
L63:
or      (ix+9)
jp      nz,l119
L66:
ld      l,(ix+6)
ld      h,(ix+7)
jp      L70
l119:
xor     a
ld      l,a
ld      a,(ix+9)
and     128
ld      h,a
ld      a,l
or      h
jp      nz,L57
ld      de,_array_AAE8
ld      l,(ix+8)
ld      h,(ix+9)
add     hl,hl
add     hl,de
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
jp      L56
L57:
ld      e,(ix+8)
ld      d,(ix+9)
ld      hl,-1
or      a
sbc     hl,de
L56:
ex      de,hl
push    de
xor     a
ld      l,a
ld      a,(ix+7)
and     128
ld      h,a
ld      a,l
or      h
jp      nz,L55
ld      de,_array_AAE8
ld      l,(ix+6)
ld      h,(ix+7)
add     hl,hl
add     hl,de
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
jp      L54
L55:
ld      e,(ix+6)
ld      d,(ix+7)
ld      hl,-1
or      a
sbc     hl,de
L54:
pop     de
ld      a,l
and     e
ld      l,a
ld      a,h
and     d
ld      h,a
ld      (ix+-2),l
ld      (ix+-1),h
xor     a
ld      l,a
ld      a,(ix+7)
and     128
ld      h,a
ld      a,l
or      h
jp      nz,L53
ld      de,_array_AAE8
ld      l,(ix+6)
ld      h,(ix+7)
add     hl,hl
add     hl,de
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
jp      L52
L53:
ld      e,(ix+6)
ld      d,(ix+7)
ld      hl,-1
or      a
sbc     hl,de
L52:
ld      e,(ix+-2)
ld      d,(ix+-1)
or      a
sbc     hl,de
jp      z,L66
xor     a
ld      l,a
ld      a,(ix+9)
and     128
ld      h,a
ld      a,l
or      h
jp      nz,L51
ld      de,_array_AAE8
ld      l,(ix+8)
ld      h,(ix+9)
add     hl,hl
add     hl,de
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
jp      L50
L51:
ld      e,(ix+8)
ld      d,(ix+9)
ld      hl,-1
or      a
sbc     hl,de
L50:
ld      e,(ix+-2)
ld      d,(ix+-1)
or      a
sbc     hl,de
jp      z,L72
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
ld      l,e
ld      h,d
push    hl
call    _sub_6589
pop     bc
pop     bc
ld      e,l
ld      h,0
ld      (ix+-4),l
ld      (ix+-3),h
l105:
ld      l,(ix+-4)
ld      h,(ix+-3)
jp      cret
psect   data
19:
defb    37,115,58,32,108,97,114,103,101,32,111,102,102,115,101,116
defb    0
29:
defb    45,0
psect   text

