global  _sub_54B6
global  ncsv, cret, indir
global  _dopetab
global  _sub_4C12
global  wrelop
global  _byte_B013
global  _sub_4B89
global  wrelop
global  _nodesize
global  _sub_60A8
global  wrelop
global  wrelop
global  _sub_14F3
global  _sub_62BE
global  _freeNode
global  _warningMsg
global  _sub_6246
global  _sub_4DA3
global  _sub_4E8D
global  _sub_4C8B
global  _sub_4BE5
global  _sub_475C
global  _sub_415E
global  asaladd
global  arelop
global  _sub_4FA8
global  _allocNode
global  _typeUChar
global  _typeChar
global  _sub_43EF
global  arelop
global  _sub_46F7
global  _sub_4FCE
global  _prWarning
global  wrelop
global  lllsh
global  lland
global  lrelop
global  _sub_508A
global  _sub_53EE
psect   text
_sub_54B6:
call ncsv
defw -10
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
ld      de,_dopetab
ld      l,(iy+0)
ld      h,0
add     hl,hl
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      a,c
and     12
ld      l,a
xor     a
ld      h,a
ld      (ix+-6),l
ld      (ix+-5),h
ld      a,l
or      (ix+-5)
jp      z,l11
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
call    _sub_54B6
pop     bc
ld      (iy+25),l
ld      (iy+26),h
l11:

;ld      de,8
;ld      l,(ix+-6)
;ld      h,(ix+-5)
;or      a
;sbc     hl,de
ld	a,(ix+-6)
cp	8

jp      nz,l12
ld      l,(iy+27)
ld      h,(iy+28)
push    hl
call    _sub_54B6
pop     bc
ld      (iy+27),l
ld      (iy+28),h
l12:
ld      de,_dopetab
ld      l,(iy+0)
ld      h,0
add     hl,hl
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
bit     6,c
jp      z,l13
ld      l,(iy+27)
ld      h,(iy+28)
push    hl
call    _sub_4C12
ex      (sp),hl
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
call    _sub_4C12
pop     bc
pop     de
call    wrelop
jp      p,l14
ld      a,1
ld      (_byte_B013),a
ld      l,(iy+25)
ld      h,(iy+26)
ld      (ix+-2),l
ld      (ix+-1),h
ld      l,(iy+27)
ld      h,(iy+28)
ld      (iy+25),l
ld      (iy+26),h
ld      l,(ix+-2)
ld      h,(ix+-1)
ld      (iy+27),l
ld      (iy+28),h
l14:
ld      de,_dopetab
ld      l,(iy+0)
ld      h,0
add     hl,hl
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
bit     5,b
jp      z,l13
ld      l,(iy+25)
ld      h,(iy+26)
ld      a,(iy+0)
cp      (hl)
jp      nz,l13
ld      l,(iy+27)
ld      h,(iy+28)
push    hl
call    _sub_4B89
pop     bc
ld      a,l
or      a
jp      z,l16
ld      e,(iy+25)
ld      d,(iy+26)
ld      (ix+-2),e
ld      (ix+-1),d
ld      hl,27
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
call    _sub_4B89
pop     bc
ld      a,l
or      a
jp      z,l16
ld      a,1
ld      (_byte_B013),a
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      hl,27
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (iy+25),c
ld      (iy+26),b
ld      hl,27
add     hl,de
push    iy
pop     de
ld      (hl),e
inc     hl
ld      (hl),d
ld      l,(ix+-2)
ld      h,(ix+-1)
push    hl
pop     iy
jp      l13
l16:
ld      l,(iy+27)
ld      h,(iy+28)
push    hl
call    _sub_4C12
pop     bc
push    hl
ld      e,(iy+25)
ld      d,(iy+26)
ld      hl,27
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
call    _sub_4C12
pop     bc
pop     de
call    wrelop
jp      p,l13
ld      a,1
ld      (_byte_B013),a
ld      l,(iy+27)
ld      h,(iy+28)
ld      (ix+-2),l
ld      (ix+-1),h
ld      e,(iy+25)
ld      d,(iy+26)
ld      hl,27
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (iy+27),c
ld      (iy+28),b
ld      hl,27
add     hl,de
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      (hl),e
inc     hl
ld      (hl),d
l13:
ld      de,_dopetab
ld      l,(iy+0)
ld      h,0
add     hl,hl
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
xor     a
ld      l,a
ld      a,b
and     12
ld      h,a
ld      de,2048
or      a
sbc     hl,de
jp      nz,l19
ld      l,(iy+25)
ld      h,(iy+26)
ld      a,(hl)
cp      20
jp      nz,l19
push    iy
call    _nodesize
pop     bc
push    hl
ld      e,(iy+25)
ld      d,(iy+26)
ld      hl,25
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
call    _nodesize
pop     bc
pop     de
call    wrelop
jp      nc,l19
ld      e,(iy+25)
ld      d,(iy+26)
ld      hl,25
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
ld      l,(iy+27)
ld      h,(iy+28)
push    hl
call    _sub_60A8
pop     bc
pop     bc
ld      a,l
or      a
jp      z,l19
ld      l,(iy+25)
ld      h,(iy+26)
ld      (ix+-4),l
ld      (ix+-3),h
ld      e,(ix+-4)
ld      d,(ix+-3)
ld      hl,25
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (iy+25),c
ld      (iy+26),b
ld      e,c
ld      d,b
ld      hl,23
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (iy+23),c
ld      (iy+24),b
ld      hl,21
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (iy+21),c
ld      (iy+22),b
ld      e,(iy+27)
ld      d,(iy+28)
ld      hl,23
add     hl,de
ld      e,(iy+23)
ld      d,(iy+24)
ld      (hl),e
inc     hl
ld      (hl),d
ld      e,(iy+27)
ld      d,(iy+28)
ld      hl,21
add     hl,de
ld      e,c
ld      d,b
ld      (hl),e
inc     hl
ld      (hl),d
ld      e,(ix+-4)
ld      d,(ix+-3)
ld      hl,25
add     hl,de
push    iy
pop     de
ld      (hl),e
inc     hl
ld      (hl),d
ld      l,(ix+-4)
ld      h,(ix+-3)
push    hl
pop     iy
l19:
ld      de,_dopetab
ld      l,(iy+0)
ld      h,0
add     hl,hl
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      a,c
and     32
ld      l,a
ld      a,b
and     4
ld      h,a
ld      de,1056
or      a
sbc     hl,de
jp      nz,l27
ld      l,(iy+25)
ld      h,(iy+26)
ld      (ix+-2),l
ld      (ix+-1),h
ld      a,(hl)
cp      20
jp      nz,l27
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      hl,25
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
call    _nodesize
pop     bc
ld      a,l
or      h
jp      z,l27
ld      l,(ix+-2)
ld      h,(ix+-1)
push    hl
call    _nodesize
pop     bc
push    hl
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      hl,25
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
call    _nodesize
pop     bc
pop     de
call    wrelop
jp      nc,l27
ld      l,(iy+27)
ld      h,(iy+28)
ld      a,(hl)
cp      67
jp      nz,l21
ld      l,(ix+-2)
ld      h,(ix+-1)
push    hl
call    _sub_14F3
pop     bc
ld      a,l
cp      1
jp      z,L15
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      hl,25
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
call    _sub_14F3
pop     bc
ld      a,l
cp      2
jp      nz,l21
L15:
ld      l,(iy+27)
ld      h,(iy+28)
push    hl
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
call    _sub_62BE
pop     bc
pop     bc
ld      a,l
or      a
jp      z,l22
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
call    _freeNode
pop     bc
ld      e,(iy+25)
ld      d,(iy+26)
ld      hl,27
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
call    _freeNode
pop     bc
ld      e,(iy+25)
ld      d,(iy+26)
ld      hl,25
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (iy+25),c
ld      (iy+26),b
ld      e,c
ld      d,b
ld      hl,23
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      e,(iy+27)
ld      d,(iy+28)
ld      hl,23
add     hl,de
ld      (hl),c
inc     hl
ld      (hl),b
ld      e,(iy+25)
ld      d,(iy+26)
ld      hl,21
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      e,(iy+27)
ld      d,(iy+28)
ld      hl,21
add     hl,de
ld      (hl),c
inc     hl
ld      (hl),b
jp      l27
l22:
ld      hl,19f
ld      (_warningMsg),hl
jp      l27
l21:
ld      l,(iy+27)
ld      h,(iy+28)
ld      a,(hl)
cp      20
jp      nz,l27
ex      de,hl
ld      hl,25
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
ld      e,(iy+25)
ld      d,(iy+26)
ld      hl,25
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
call    _sub_6246
pop     bc
pop     bc
ld      a,l
or      a
jp      z,l27
ld      l,(iy+25)
ld      h,(iy+26)
ld      (ix+-2),l
ld      (ix+-1),h
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      hl,25
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (iy+25),c
ld      (iy+26),b
ld      hl,27
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
call    _freeNode
ld      l,(ix+-2)
ld      h,(ix+-1)
ex      (sp),hl
call    _freeNode
pop     bc
ld      l,(iy+27)
ld      h,(iy+28)
ld      (ix+-2),l
ld      (ix+-1),h
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      hl,25
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (iy+27),c
ld      (iy+28),b
ld      hl,27
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
call    _freeNode
ld      l,(ix+-2)
ld      h,(ix+-1)
ex      (sp),hl
call    _freeNode
pop     bc
l27:
ld      a,(iy+0)
cp      1
jp      z,l30
cp      6
jp      z,l59
cp      7
jp      z,l62
cp      9
jp      z,l77
cp      12
jp      z,l56
cp      13
jp      z,l79
cp      14
jp      z,l50
cp      16
jp      z,l76
cp      18
jp      z,l50
cp      20
jp      z,l75
cp      22
jp      z,l29
cp      24
jp      z,l56
cp      30
jp      z,l32
cp      31
jp      z,l50
cp      32
jp      z,l35
cp      34
jp      z,l59
cp      35
jp      z,l62
cp      36
jp      z,l56
cp      37
jp      z,l50
cp      38
jp      z,l50
cp      39
jp      z,l56
cp      40
jp      z,l50
cp      42
jp      z,l50
cp      44
jp      z,l41
cp      45
jp      z,l35
cp      46
jp      z,l32
cp      47
jp      z,l50
cp      60
jp      z,l41
cp      66
push    iy
jp      nz,L27
call    _sub_4DA3
L34:
;pop     bc
;jp      cret
jp	popBCcret
l29:
push    iy
call    _sub_4E8D
jp      L34
l30:
push    iy
call    _sub_4C8B
jp      L34
l32:
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
call    _sub_14F3
pop     bc
ld      a,l
cp      2
jp      nz,l26
ld      l,(iy+27)
ld      h,(iy+28)
push    hl
call    _sub_4BE5
pop     bc
ld      a,l
or      a
jp      z,l26
ld      hl,29f
ld      (_warningMsg),hl
push    iy
call    _sub_475C
pop     bc
ld      a,(iy+0)
cp      46
jp      z,L14
ld      de,0
ld      l,e
ld      h,d
jp      L13
L14:
ld      de,1
ld      hl,0
L13:
push    hl
push    de
call    _sub_415E
pop     bc
pop     bc
push    hl
pop     iy
l26:
push    iy
L27:
;pop     hl
;jp      cret
jp	popHLcret
l35:
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
call    _sub_14F3
pop     bc
ld      a,l
cp      2
jp      nz,l36
ld      l,(iy+27)
ld      h,(iy+28)
push    hl
call    _sub_4BE5
pop     bc
ld      a,l
or      a
jp      z,l36
ld      a,(iy+0)
cp      45
jp      z,L12
ld      hl,41
jp      L28
L12:
ld      hl,2
L28:
ld      (iy+0),l
jp      l26
l36:
ld      l,(iy+27)
ld      h,(iy+28)
ld      a,(hl)
cp      67
jp      nz,l38
ld      de,1
ld      hl,0
push    hl
push    de
ld      e,(iy+27)
ld      d,(iy+28)
ld      hl,25
add     hl,de
call    asaladd
ld      a,(iy+0)
cp      45
jp      z,L32
L31:
ld      hl,30
jp      L28
L32:
ld      hl,46
jp      L28
l38:
ld      l,(iy+25)
ld      h,(iy+26)
ld      (ix+-2),l
ld      (ix+-1),h
ld      l,(iy+27)
ld      h,(iy+28)
ld      (iy+25),l
ld      (iy+26),h
ld      l,(ix+-2)
ld      h,(ix+-1)
ld      (iy+27),l
ld      (iy+28),h
ld      a,(iy+0)
cp      45
jp      nz,L32
jp      L31
l41:
ld      l,(iy+27)
ld      h,(iy+28)
ld      a,(hl)
cp      67
jp      nz,l50
ld      de,-1
ld      l,e
ld      h,d
push    hl
push    de
ld      e,(iy+27)
ld      d,(iy+28)
ld      hl,25
add     hl,de
ld      e,(hl)
inc     hl
ld      d,(hl)
inc     hl
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
call    arelop
jp      nz,l50
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
call    _sub_475C
pop     bc
push    iy
call    _freeNode
pop     bc
ld      l,(iy+27)
ld      h,(iy+28)
jp      cret
l50:
ld      l,(iy+27)
ld      h,(iy+28)
ld      a,(hl)
cp      67
jp      nz,l51
ex      de,hl
ld      hl,25
add     hl,de
ld      e,(hl)
inc     hl
ld      d,(hl)
inc     hl
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
ld      a,e
or      d
or      l
or      h
jp      nz,l51
L36:
push    iy
call    _sub_4FA8
jp      L34
l51:
ld      de,_dopetab
ld      l,(iy+0)
ld      h,0
add     hl,hl
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
bit     7,c
jp      z,l26
ld      l,(iy+27)
ld      h,(iy+28)
push    hl
call    _nodesize
pop     bc

;ld      de,1
;or      a
;sbc     hl,de
ld	a,l
cp	1

jp      z,l26
call    _allocNode
ld      (ix+-2),l
ld      (ix+-1),h
ld      l,(iy+27)
ld      h,(iy+28)
push    hl
call    _sub_14F3
pop     bc
ld      a,l
cp      2
jp      z,L6
ld      hl,(_typeChar)
jp      L5
L6:
ld      hl,(_typeUChar)
L5:
push    hl
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      hl,23
add     hl,de
pop     de
ld      (hl),e
inc     hl
ld      (hl),d
ld      l,(ix+-2)
ld      h,(ix+-1)
ld      (hl),65
push    hl
ld      l,(iy+27)
ld      h,(iy+28)
push    hl
ld      l,20
push    hl
call    _sub_43EF
pop     bc
pop     bc
pop     bc
ld      (iy+27),l
ld      (iy+28),h
jp      l26
l56:
ld      l,(iy+27)
ld      h,(iy+28)
ld      a,(hl)
cp      67
jp      nz,l59
ld      de,1
ld      hl,0
push    hl
push    de
ld      e,(iy+27)
ld      d,(iy+28)
ld      hl,25
add     hl,de
ld      e,(hl)
inc     hl
ld      d,(hl)
inc     hl
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
call    arelop
jp      z,L36
l59:
ld      l,(iy+27)
ld      h,(iy+28)
ld      a,(hl)
cp      67
jp      nz,l62
ex      de,hl
ld      hl,25
add     hl,de
ld      e,(hl)
inc     hl
ld      d,(hl)
inc     hl
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
push    hl
push    de
call    _sub_46F7
pop     bc
pop     bc
ld      a,l
or      a
jp      z,l62
push    iy
call    _sub_4FCE
jp      L34
l62:
ld      l,(iy+27)
ld      h,(iy+28)
ld      a,(hl)
cp      67
jp      nz,l63
ex      de,hl
ld      hl,25
add     hl,de
ld      e,(hl)
inc     hl
ld      d,(hl)
inc     hl
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
ld      a,e
or      d
or      l
or      h
jp      nz,l63
ld      a,(iy+0)
cp      6
jp      z,l69
cp      7
jp      z,l71
cp      12
jp      z,l71
cp      24
jp      z,l69
cp      34
jp      z,l69
cp      35
jp      z,l73
cp      36
jp      z,l73
cp      39
jp      nz,l63
l69:
ld      hl,39f
push    hl
call    _prWarning
pop     bc
L33:
push    iy
jp      L27
l71:
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
call    _sub_475C
ld      l,(iy+27)
ld      h,(iy+28)
ex      (sp),hl
call    _sub_475C
pop     bc
ld      (iy+0),67
ld      (iy+25),0
ld      (iy+26),0
ld      (iy+27),0
ld      (iy+28),0
jp      L33
l73:
ld      (iy+0),33
jp      L33
l63:
push    iy
call    _nodesize
pop     bc
ld      de,4
call    wrelop
jp      nc,L4
push    iy
call    _nodesize
pop     bc
add     hl,hl
add     hl,hl
add     hl,hl
ld      b,l
ld      de,1
ld      hl,0
call    lllsh
ex      de,hl
ld      bc,-1
add     hl,bc
ex      de,hl
adc     hl,bc
jp      L3
L4:
ld      de,-1
ld      l,e
ld      h,d
L3:
ld      (ix+-10),e
ld      (ix+-9),d
ld      (ix+-8),l
ld      (ix+-7),h
ld      a,(iy+0)
cp      7
jp      z,L1
cp      35
jp      nz,l26
L1:
ld      l,(iy+27)
ld      h,(iy+28)
ld      a,(hl)
cp      67
jp      nz,l26
ld      e,(ix+-10)
ld      d,(ix+-9)
ld      l,(ix+-8)
ld      h,(ix+-7)
push    hl
push    de
push    hl
push    de
ld      e,(iy+27)
ld      d,(iy+28)
ld      hl,25
add     hl,de
ld      e,(hl)
inc     hl
ld      d,(hl)
inc     hl
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
call    lland
call    lrelop
jp      nz,l26
jp      L36
l75:
push    iy
call    _sub_508A
jp      L34
l76:
push    iy
call    _freeNode
pop     bc
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
pop     iy
jp      l26
l77:
ld      l,(iy+25)
ld      h,(iy+26)
ld      a,(hl)
cp      13
push    iy
jp      nz,L27
L25:
call    _sub_53EE
jp      L34
l79:
ld      l,(iy+25)
ld      h,(iy+26)
ld      a,(hl)
cp      9
jp      nz,l26
ex      de,hl
ld      hl,25
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (ix+-2),c
ld      (ix+-1),b
ld      l,c
ld      h,b
ld      a,(hl)
cp      10
jp      z,l26
ld      a,(hl)
cp      33
jp      z,l26
ld      a,(hl)
cp      48
jp      z,l26
push    iy
jp      L25
psect   data
19:
defb    109,105,115,109,97,116,99,104,101,100,32,99,111,109,112,97
defb    114,105,115,105,111,110,0
29:
defb    100,101,103,101,110,101,114,97,116,101,32,117,110,115,105,103
defb    110,101,100,32,99,111,109,112,97,114,105,115,105,111,110,0
39:
defb    68,105,118,105,115,105,111,110,32,98,121,32,122,101,114,111
defb    0
psect   text

