include cgen.inc
global  _main
global  ncsv, cret, indir
global  _baseHeap
global  _sbrk
global  _pflag
global  _wflag
global  _rflag
global  _bflag
global  _eflag
global  _hflag
global  _fatalErr
global  wrelop
global  wrelop
global  _freopen
global  __iob
global  wrelop
global  _sub_1680
global  _parseStmt
global  _fclose
global  _prError
global  _exit
global  _errcnt
psect   text
_main:
global csv
call csv
IF RAM128
global  _InitDynM
call    _InitDynM
ENDIF
ld      hl,0
push    hl
call    _sbrk
pop     bc
ld      (_baseHeap),hl
ld      l,(ix+6)
ld      h,(ix+7)
dec     hl
ld      (ix+6),l
ld      (ix+7),h
ld      l,(ix+8)
ld      h,(ix+9)
inc     hl
inc     hl
ld      (ix+8),l
ld      (ix+9),h
jp      l11
l12:
ld      l,(ix+8)
ld      h,(ix+9)
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
inc     hl
ld      a,(hl)
cp      66
jp      z,l21
cp      69
jp      z,l22
cp      72
jp      z,l23
cp      80
jp      z,l17
cp      82
jp      z,l20
cp      87
jp      z,l19
cp      112
jp      z,l17
cp      119
jp      z,l19
ld      l,(ix+8)
ld      h,(ix+9)
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
inc     hl
ld      a,(hl)
ld      l,a
rla
sbc     a,a
ld      h,a
push    hl
ld      hl,19f
push    hl
call    _fatalErr
pop     bc
pop     bc
l14:
ld      l,(ix+8)
ld      h,(ix+9)
inc     hl
inc     hl
ld      (ix+8),l
ld      (ix+9),h
ld      l,(ix+6)
ld      h,(ix+7)
dec     hl
ld      (ix+6),l
ld      (ix+7),h
l11:
ld      e,(ix+6)
ld      d,(ix+7)
ld      hl,0
call    wrelop
jp      m,L3
jp      l13
l17:
ld      a,1
ld      (_pflag),a
jp      l14
l19:
ld      a,1
ld      (_wflag),a
jp      l14
l20:
ld      a,1
ld      (_rflag),a
jp      l14
l21:
ld      a,1
ld      (_bflag),a
jp      l14
l22:
ld      a,1
ld      (_eflag),a
jp      l14
l23:
ld      a,1
ld      (_hflag),a
jp      l14
L3:
ld      l,(ix+8)
ld      h,(ix+9)
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
ld      a,(hl)
cp      45
jp      z,l12
l13:
ld      e,(ix+6)
ld      d,(ix+7)
dec     de
ld      (ix+6),e
ld      (ix+7),d
inc     de
ld      hl,0
call    wrelop
jp      p,l25
ld      hl,__iob
push    hl
ld      hl,29f
push    hl
ld      l,(ix+8)
ld      h,(ix+9)
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
call    _freopen
pop     bc
pop     bc
pop     bc
ld      a,l
or      h
jp      nz,l26
ld      l,(ix+8)
ld      h,(ix+9)
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
ld      hl,39f
push    hl
call    _fatalErr
pop     bc
pop     bc
jp      l25
l26:
ld      e,(ix+6)
ld      d,(ix+7)
ld      hl,0
call    wrelop
jp      p,l25
ld      hl,__iob+8
push    hl
ld      hl,49f
push    hl
ld      l,(ix+8)
ld      h,(ix+9)
inc     hl
inc     hl
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
call    _freopen
pop     bc
pop     bc
pop     bc
ld      a,l
or      h
jp      nz,l25
ld      l,(ix+8)
ld      h,(ix+9)
inc     hl
inc     hl
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
ld      hl,59f
push    hl
call    _fatalErr
pop     bc
pop     bc
l25:
call    _sub_1680
call    _parseStmt
ld      hl,__iob+8
push    hl
call    _fclose
pop     bc
ld      de,-1
or      a
sbc     hl,de
jp      nz,l29
ld      hl,69f
push    hl
call    _prError
pop     bc
l29:
ld      hl,(_errcnt)
ld      a,l
or      h
ld      hl,1
jp      nz,L1
dec     hl
L1:
push    hl
call    _exit
jp      cret
global  _prMsg
_fatalErr:
global csv
call csv
push hl
push    ix
pop     de
ld      hl,8
add     hl,de
ld      (ix+-2),l
ld      (ix+-1),h
push    ix
pop     hl
dec     hl
dec     hl
push    hl
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
call    _prMsg
pop     bc
ld      hl,__iob+8
ex      (sp),hl
call    _fclose
ld      hl,2
ex      (sp),hl
call    _exit
jp      cret
global  _prWarning
global  _fprintf
global  _progname
global  _lineno
global  __doprnt
_prWarning:
global csv
call csv
push hl
ld      a,(_wflag)
or      a
jp      nz,cret
ld      hl,(_lineno)
push    hl
ld      hl,_progname
push    hl
ld      hl,79f
push    hl
ld      hl,__iob+16
push    hl
call    _fprintf
pop     bc
pop     bc
pop     bc
pop     bc
push    ix
pop     de
ld      hl,8
add     hl,de
ld      (ix+-2),l
ld      (ix+-1),h
push    ix
pop     hl
dec     hl
dec     hl
push    hl
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
ld      hl,__iob+16
push    hl
call    __doprnt
pop     bc
pop     bc
ld      hl,89f
ex      (sp),hl
ld      hl,__iob+16
push    hl
call    _fprintf
jp      cret
global  wrelop
_prError:
global csv
call csv
push hl
push    ix
pop     de
ld      hl,8
add     hl,de
ld      (ix+-2),l
ld      (ix+-1),h
push    ix
pop     hl
dec     hl
dec     hl
push    hl
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
call    _prMsg
pop     bc
pop     bc
ld      de,30
ld      hl,(_errcnt)
inc     hl
ld      (_errcnt),hl
call    wrelop
jp      m,cret
ld      hl,99f
push    hl
call    _fatalErr
jp      cret
global  _fputc
_prMsg:
global csv
call csv
ld      hl,(_lineno)
push    hl
ld      hl,_progname
push    hl
ld      hl,109f
push    hl
ld      hl,__iob+16
push    hl
call    _fprintf
pop     bc
pop     bc
pop     bc
ld      l,(ix+8)
ld      h,(ix+9)
ex      (sp),hl
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
ld      hl,__iob+16
push    hl
call    __doprnt
pop     bc
pop     bc
ld      hl,__iob+16
ex      (sp),hl
ld      hl,10
push    hl
call    _fputc
jp      cret
global  _allocMem
global  _malloc
global  _releaseNodeFreeList
global  _blkclr
_allocMem:
global csv
call csv
l39:
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
call    _malloc
pop     bc
push    hl
pop     iy
ld      a,l
or      h
jp      nz,l41
call    _releaseNodeFreeList
ld      a,l
or      a
jp      nz,l39
ld      hl,119f
push    hl
call    _fatalErr
pop     bc
l41:
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
push    iy
call    _blkclr
pop     bc
pop     bc
;push    iy
;pop     hl
;jp      cret
jp	pushIYpopHLcret

IF RAM128

global  _MyAlloc
global  _Alloc128
_MyAlloc:
global csv
call csv
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
call    _Alloc128
pop     bc
push    hl
pop     iy
ld      a,l
or      h
jp      z,l43
;push    iy
;pop     hl
;jp      cret
jp	pushIYpopHLcret
l43:
ld      hl,129f
push    hl
call    _fatalErr
jp      cret

ENDIF

psect   data
19:
defb    73,108,108,101,103,97,108,9,115,119,105,116,99,104,32,37
defb    99,0
29:
defb    114,0
39:
defb    67,97,110,39,116,32,111,112,101,110,32,37,115,0
49:
defb    119,0
59:
defb    67,97,110,39,116,32,99,114,101,97,116,101,32,37,115,0
69:
defb    69,114,114,111,114,32,99,108,111,115,105,110,103,32,111,117
defb    116,112,117,116,32,102,105,108,101,0
79:
defb    37,115,58,37,100,58,9,0
89:
defb    32,40,119,97,114,110,105,110,103,41,10,0
99:
defb    84,111,111,32,109,97,110,121,32,101,114,114,111,114,115,0
109:
defb    37,115,58,37,100,58,9,0
119:
defb    78,111,32,114,111,111,109,0
129:
defb    85,112,112,101,114,32,82,65,77,32,102,117,108,108,0
psect   text

