global  _parseVariable
global  ncsv, cret, indir
global  _sub_1754
global  _getToken
global  _sub_627
global  _sub_600E
global  _parseExpr
global  _fatalErr
global  _sub_475C
global  _expect
global  _varSize
global  _prError
global  _sub_5CF5
global  _newLocal
global  _lvlidx
global  _array_AE57
global  _nstdpth
global  _array_AE97
global  _array_AE13
global  _array_AEDB
psect   text
_parseVariable:
global csv
call csv
push hl
push hl
ld      l,57
push    hl
call    _getToken
push    hl
call    _sub_1754
pop     bc
push    hl
pop     iy
push    hl
pop     de
ld      hl,13
add     hl,de
ex      (sp),hl
call    _getToken
push    hl
call    _sub_627
pop     bc
pop     bc
ld      (iy+15),l
ld      (iy+16),h
call    _parseExpr
push    hl
call    _sub_600E
pop     bc
ld      (ix+-2),l
ld      (ix+-1),h
ld      a,(hl)
cp      67
jp      z,l11
ld      hl,19f
push    hl
call    _fatalErr
pop     bc
l11:
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      hl,25
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (iy+11),c
ld      (iy+12),b
ld      l,e
ld      h,d
push    hl
call    _sub_475C
pop     bc
call    _getToken
ld      a,(hl)
ld      l,a
rla
sbc     a,a
ld      h,a
ld      (ix+-4),l
ld      (ix+-3),h
ld      l,93
push    hl
call    _expect
pop     bc
ld      l,(ix+-4)
ld      h,(ix+-3)
ld      a,h
or      a
jp      nz,l29
ld      a,l
cp      65
jp      z,l15
cp      69
jp      z,l23
cp      80
jp      z,l19
cp      82
jp      z,l17
cp      83
jp      z,l21
cp      84
jp      z,l25
cp      97
jp      z,l15
cp      101
jp      z,l23
cp      112
jp      z,l19
cp      114
jp      z,l17
cp      115
jp      z,l21
cp      116
jp      z,l25
l29:
ld      hl,29f
push    hl
call    _fatalErr
pop     bc
l12:
push    iy
call    _varSize
pop     bc
ld      (iy+9),l
ld      (iy+10),h
ld      a,(iy+2)
cp      65
jp      z,cret
ld      a,(iy+13)
or      (iy+14)
jp      nz,l31
ld      a,l
or      (iy+10)
jp      nz,l31
ld      e,(iy+15)
ld      d,(iy+16)
ld      hl,9
add     hl,de
ld      a,(hl)
inc     hl
or      (hl)
jp      nz,l31
ld      hl,39f
push    hl
call    _prError
pop     bc
l31:
ld      a,(iy+21)
cp      5
jp      nz,L2
jp      L1
l15:
ld      (iy+21),1
jp      l12
l17:
set     3,(iy+3)
l19:
ld      (iy+21),5
jp      l12
l21:
ld      (iy+21),4
jp      l12
l23:
ld      (iy+21),3
jp      l12
l25:
ld      (iy+2),65
ld      a,(iy+13)
or      (iy+14)
jp      z,l26
ld      (iy+17),0
ld      (iy+18),0
ld      (iy+21),2
jp      l27
l26:
ld      e,(iy+15)
ld      d,(iy+16)
ld      hl,17
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (iy+17),c
ld      (iy+18),b
ld      hl,21
add     hl,de
ld      l,(hl)
ld      (iy+21),l
l27:

;ld      de,1
;ld      l,(iy+11)
;ld      h,(iy+12)
;or      a
;sbc     hl,de
ld	a,(iy+11)
cp	1

jp      z,l12
ld      (iy+21),0
jp      l12
L2:
ld      a,(iy+21)
cp      1
jp      nz,l32
L1:
ld      l,(ix+-4)
ld      h,(ix+-3)
push    hl
push    iy
call    _sub_5CF5
pop     bc
pop     bc
jp      l33
l32:
call    _newLocal
ld      (iy+17),l
ld      (iy+18),h
l33:
bit     1,(iy+13)
jp      z,cret
ld      a,(iy+11)
or      (iy+12)
jp      z,cret

;ld      de,32
ld      hl,(_lvlidx)
inc     hl
ld      (_lvlidx),hl
;or      a
;sbc     hl,de
ld	a,l
cp	32

jp      nz,l35
ld      hl,49f
push    hl
call    _fatalErr
pop     bc
l35:
ld      de,_array_AE57
ld      hl,(_lvlidx)
add     hl,hl
add     hl,de
ld      de,(_nstdpth)
ld      (hl),e
inc     hl
ld      (hl),d
ld      de,_array_AE97
ld      hl,(_lvlidx)
add     hl,hl
add     hl,de
ld      de,6
ld      (hl),e
inc     hl
ld      (hl),d
ld      de,_array_AE13
ld      hl,(_lvlidx)
add     hl,hl
add     hl,de
ld      de,0
ld      (hl),e
inc     hl
ld      (hl),d
ld      de,_array_AEDB
ld      hl,(_lvlidx)
add     hl,hl
add     hl,de
push    iy
pop     de
ld      (hl),e
inc     hl
ld      (hl),d
jp      cret
global  _parseMembers
global  _allocMem
global  _atoi
global  _bmove
global  _sub_1CEF
_parseMembers:
call ncsv
defw -526
ld      l,(ix+6)
push    hl
call    _getToken
push    hl
call    _sub_1754
pop     bc
pop     bc
ld      (ix+-4),l
ld      (ix+-3),h
push    ix
pop     de
ld      hl,-526
add     hl,de
ld      (ix+-6),l
ld      (ix+-5),h
ld      de,0
ld      (hl),e
inc     hl
ld      (hl),d
l39:
call    _getToken
ld      (ix+-10),l
ld      (ix+-9),h
ld      a,(hl)
cp      93
jp      z,l40
ld      hl,22
push    hl
call    _allocMem
pop     bc
push    hl
pop     iy
ld      (iy+2),22
ld      l,(ix+-10)
ld      h,(ix+-9)
ld      a,(hl)
cp      58
jp      nz,l43
inc     hl
push    hl
call    _atoi
pop     bc
ld      (iy+5),l
set     4,(iy+3)
call    _getToken
ld      (ix+-10),l
ld      (ix+-9),h
l43:
push    iy
pop     de
ld      hl,13
add     hl,de
push    hl
ld      l,(ix+-10)
ld      h,(ix+-9)
push    hl
call    _sub_627
pop     bc
pop     bc
ld      (iy+15),l
ld      (iy+16),h
call    _parseExpr
push    hl
call    _sub_600E
pop     bc
ld      (ix+-8),l
ld      (ix+-7),h
ld      a,(hl)
cp      67
jp      z,l44
ld      hl,59f
push    hl
call    _fatalErr
pop     bc
l44:
ld      e,(ix+-8)
ld      d,(ix+-7)
ld      hl,25
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (iy+11),c
ld      (iy+12),b
ld      l,e
ld      h,d
push    hl
call    _sub_475C
pop     bc
push    iy
call    _varSize
pop     bc
ld      (iy+9),l
ld      (iy+10),h
ld      e,(ix+-6)
ld      d,(ix+-5)
ex      de,hl
ld      e,(hl)
inc     hl
ld      d,(hl)
ex      de,hl
inc     hl
ex      de,hl
ld      (hl),d
dec     hl
ld      (hl),e
ex      de,hl
dec     hl
add     hl,hl
ld      e,(ix+-6)
ld      d,(ix+-5)
add     hl,de
inc     hl
inc     hl
push    iy
pop     de
ld      (hl),e
inc     hl
ld      (hl),d
jp      l39
l40:
ld      l,(ix+-6)
ld      h,(ix+-5)
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      hl,-1
add     hl,bc
add     hl,hl
inc     hl
inc     hl
inc     hl
inc     hl
ld      (ix+-2),l
ld      (ix+-1),h
push    hl
call    _allocMem
ld      (ix+-6),l
ld      (ix+-5),h
ld      l,(ix+-2)
ld      h,(ix+-1)
ex      (sp),hl
ld      l,(ix+-6)
ld      h,(ix+-5)
push    hl
push    ix
pop     de
ld      hl,-526
add     hl,de
push    hl
call    _bmove
pop     bc
pop     bc
pop     bc
ld      e,(ix+-4)
ld      d,(ix+-3)
ld      hl,19
add     hl,de
ld      e,(ix+-6)
ld      d,(ix+-5)
ld      (hl),e
inc     hl
ld      (hl),d
ld      l,(ix+-4)
ld      h,(ix+-3)
push    hl
call    _sub_1CEF
jp      cret
global  _parseEnum
global  _sub_15FB
global  arelop
global  arelop
_parseEnum:
call ncsv
defw -526
ld      (ix+-6),0
ld      (ix+-5),128
ld      (ix+-8),255
ld      (ix+-7),127
ld      l,52
push    hl
call    _getToken
push    hl
call    _sub_1754
pop     bc
pop     bc
push    hl
pop     iy
push    ix
pop     de
ld      hl,-526
add     hl,de
ld      (ix+-4),l
ld      (ix+-3),h
ld      de,0
ld      (hl),e
inc     hl
ld      (hl),d
l46:
call    _parseExpr
ld      (ix+-2),l
ld      (ix+-1),h
ld      a,(hl)
cp      23
push    hl
jp      nz,L4
call    _sub_475C
pop     bc
ld      l,(ix+-4)
ld      h,(ix+-3)
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      hl,-1
add     hl,bc
add     hl,hl
inc     hl
inc     hl
inc     hl
inc     hl
ld      (ix+-10),l
ld      (ix+-9),h
push    hl
call    _allocMem
ld      (ix+-4),l
ld      (ix+-3),h
ld      l,(ix+-10)
ld      h,(ix+-9)
ex      (sp),hl
ld      l,(ix+-4)
ld      h,(ix+-3)
push    hl
push    ix
pop     de
ld      hl,-526
add     hl,de
push    hl
call    _bmove
pop     bc
pop     bc
ld      l,(ix+-4)
ld      h,(ix+-3)
ld      (iy+19),l
ld      (iy+20),h
ld      l,(ix+-6)
ld      h,(ix+-5)
ex      (sp),hl
ld      l,(ix+-8)
ld      h,(ix+-7)
push    hl
push    iy
call    _sub_15FB
pop     bc
pop     bc
ld      l,93
ex      (sp),hl
call    _expect
;pop     bc
;jp      cret
jp	popBCcret
L4:
call    _sub_600E
pop     bc
ld      (ix+-2),l
ld      (ix+-1),h
ex      de,hl
ld      hl,25
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      e,(ix+-4)
ld      d,(ix+-3)
ex      de,hl
ld      e,(hl)
inc     hl
ld      d,(hl)
ex      de,hl
inc     hl
ex      de,hl
ld      (hl),d
dec     hl
ld      (hl),e
ex      de,hl
dec     hl
add     hl,hl
ld      e,(ix+-4)
ld      d,(ix+-3)
add     hl,de
inc     hl
inc     hl
ld      (hl),c
inc     hl
ld      (hl),b
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      hl,25
add     hl,de
ld      e,(hl)
inc     hl
ld      d,(hl)
inc     hl
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
push    hl
push    de
ld      e,(ix+-6)
ld      d,(ix+-5)
ld      a,d
rla
sbc     a,a
ld      l,a
ld      h,a
call    arelop
jp      p,l50
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      hl,25
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (ix+-6),c
ld      (ix+-5),b
l50:
ld      e,(ix+-8)
ld      d,(ix+-7)
ld      a,d
rla
sbc     a,a
ld      l,a
ld      h,a
push    hl
push    de
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      hl,25
add     hl,de
ld      e,(hl)
inc     hl
ld      d,(hl)
inc     hl
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
call    arelop
jp      p,l51
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      hl,25
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (ix+-8),c
ld      (ix+-7),b
l51:
ld      l,(ix+-2)
ld      h,(ix+-1)
push    hl
call    _sub_475C
pop     bc
jp      l46
global  _sub_1C6D
_sub_1C6D:
global csv
call csv
ld      e,(ix+8)
ld      d,(ix+9)
ld      hl,-1
or      a
sbc     hl,de
push    hl
ld      l,(ix+6)
ld      h,(ix+7)
add     hl,de
pop     de
ld      a,l
and     e
ld      l,a
ld      a,h
and     d
ld      h,a
jp      cret
global  lmul
_varSize:
global csv
call csv
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
bit     0,(iy+13)
jp      z,l54
ld      l,(iy+11)
ld      h,(iy+12)
add     hl,hl
jp      cret
l54:
ld      e,(iy+15)
ld      d,(iy+16)
ld      hl,9
add     hl,de
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
ld      e,(iy+11)
ld      d,(iy+12)
call    lmul
jp      cret
global  _sub_1CC4
_sub_1CC4:
global csv
call csv
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
ld      a,(iy+13)
or      (iy+14)
jp      z,l56
;ld      hl,0
;jp      cret
jp	ldHL0cret
l56:
ld      e,(iy+15)
ld      d,(iy+16)
ld      hl,17
add     hl,de
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
jp      cret
global  _max
global  wrelop
_sub_1CEF:
call ncsv
defw -8
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
ld      (ix+-2),0
ld      (ix+-1),0
ld      hl,0
ld      (ix+-6),l
ld      (ix+-5),h
ld      (ix+-4),l
ld      (ix+-3),h
jp      l61
l58:
ld      e,(iy+19)
ld      d,(iy+20)
ld      l,(ix+-4)
ld      h,(ix+-3)
add     hl,hl
add     hl,de
inc     hl
inc     hl
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (ix+-8),c
ld      (ix+-7),b
ld      a,(iy+2)
cp      56
jp      nz,l62
ld      e,c
ld      d,b
ld      hl,9
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
ld      l,(ix+-2)
ld      h,(ix+-1)
push    hl
call    _max
pop     bc
pop     bc
ld      (ix+-2),l
ld      (ix+-1),h
ld      e,(ix+-8)
ld      d,(ix+-7)
ld      hl,17
add     hl,de
ld      de,0
ld      (hl),e
inc     hl
ld      (hl),d
jp      l60
l62:
ld      l,(ix+-8)
ld      h,(ix+-7)
push    hl
call    _sub_1CC4
ex      (sp),hl
ld      l,(ix+-2)
ld      h,(ix+-1)
push    hl
call    _sub_1C6D
pop     bc
pop     bc
push    hl
ld      e,(ix+-8)
ld      d,(ix+-7)
ld      hl,17
add     hl,de
pop     de
ld      (hl),e
inc     hl
ld      (hl),d
ld      (ix+-2),e
ld      (ix+-1),d
ld      l,(ix+-8)
ld      h,(ix+-7)
inc     hl
inc     hl
inc     hl
bit     4,(hl)
jp      z,l64
ld      e,(ix+-8)
ld      d,(ix+-7)
ld      hl,5
add     hl,de
ld      l,(hl)
ld      h,0
ld      e,(ix+-6)
ld      d,(ix+-5)
add     hl,de
ex      de,hl
ld      hl,16
call    wrelop
jp      c,L5
ld      e,(ix+-8)
ld      d,(ix+-7)
ld      hl,5
add     hl,de
ld      a,(hl)
or      a
jp      nz,l65
L5:
ld      a,(ix+-6)
or      (ix+-5)
jp      z,l66
ld      e,(ix+-8)
ld      d,(ix+-7)
ld      hl,17
add     hl,de
ld      e,(ix+-2)
ld      d,(ix+-1)
inc     de
inc     de
ld      (ix+-2),e
ld      (ix+-1),d
ld      (hl),e
inc     hl
ld      (hl),d
l66:
ld      (ix+-6),0
ld      (ix+-5),0
l65:
ld      a,(ix+-6)
ld      e,(ix+-8)
ld      d,(ix+-7)
ld      hl,6
add     hl,de
ld      (hl),a
ld      hl,5
add     hl,de
ld      e,(hl)
ld      d,0
ld      l,a
ld      h,(ix+-5)
add     hl,de
ld      (ix+-6),l
ld      (ix+-5),h

;ld      de,32
;or      a
;sbc     hl,de
ld	a,l
cp	32

jp      nz,l60
ld      (ix+-6),0
ld      (ix+-5),0
ld      l,(ix+-2)
ld      h,(ix+-1)
inc     hl
inc     hl
ld      (ix+-2),l
ld      (ix+-1),h
jp      l60
l64:
ld      a,(ix+-6)
or      (ix+-5)
jp      z,l69
ld      (ix+-6),0
ld      (ix+-5),0
ld      e,(ix+-8)
ld      d,(ix+-7)
ld      hl,17
add     hl,de
ld      e,(ix+-2)
ld      d,(ix+-1)
inc     de
inc     de
ld      (ix+-2),e
ld      (ix+-1),d
ld      (hl),e
inc     hl
ld      (hl),d
l69:
ld      e,(ix+-8)
ld      d,(ix+-7)
ld      hl,9
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      l,(ix+-2)
ld      h,(ix+-1)
add     hl,bc
ld      (ix+-2),l
ld      (ix+-1),h
l60:
ld      l,(ix+-4)
ld      h,(ix+-3)
inc     hl
ld      (ix+-4),l
ld      (ix+-3),h
l61:
ld      l,(iy+19)
ld      h,(iy+20)
ld      e,(hl)
inc     hl
ld      d,(hl)
ld      l,(ix+-4)
ld      h,(ix+-3)
or      a
sbc     hl,de
jp      nz,l58
ld      a,(ix+-6)
or      (ix+-5)
jp      z,l70
ld      (ix+-6),0
ld      (ix+-5),0
ld      l,(ix+-2)
ld      h,(ix+-1)
inc     hl
inc     hl
ld      (ix+-2),l
ld      (ix+-1),h
l70:
ld      hl,0
push    hl
ld      l,(ix+-2)
ld      h,(ix+-1)
push    hl
call    _sub_1C6D
ld      (iy+9),l
ld      (iy+10),h
ld      (iy+17),0
ld      (iy+18),0
ld      (iy+2),55
jp      cret
global  _sub_1EDF
global  _hashtab
global  _prIXnPush
_sub_1EDF:
global csv
call csv
push hl
ld      hl,_hashtab
ld      (ix+-2),l
ld      (ix+-1),h
l74:
ld      l,(ix+-2)
ld      h,(ix+-1)
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
pop     iy
jp      l78
l75:
ld      a,(iy+2)
cp      57
jp      nz,l77
ld      a,(iy+21)
cp      2
jp      nz,l77
bit     2,(iy+3)
jp      z,l77
push    iy
call    _prIXnPush
pop     bc
l77:
ld      l,(iy+7)
ld      h,(iy+8)
push    hl
pop     iy
l78:
push    iy
pop     hl
ld      a,l
or      h
jp      z,l72

;ld      de,(_nstdpth)
;ld      l,(iy+4)
;ld      h,0
;or      a
;sbc     hl,de
ld	a,(_nstdpth)
cp	(iy+4)

jp      z,l75
l72:
ld      de,_hashtab+202
ld      l,(ix+-2)
ld      h,(ix+-1)
inc     hl
inc     hl
ld      (ix+-2),l
ld      (ix+-1),h
or      a
sbc     hl,de
jp      nz,l74
jp      cret
psect   data
19:
defb    66,97,100,32,101,108,101,109,101,110,116,32,99,111,117,110
defb    116,32,101,120,112,114,0
29:
defb    66,97,100,32,115,116,111,114,97,103,101,32,99,108,97,115
defb    115,0
39:
defb    66,97,100,32,100,105,109,101,110,115,105,111,110,115,0
49:
defb    70,117,110,99,116,105,111,110,115,32,110,101,115,116,101,100
defb    32,116,111,111,32,100,101,101,112,0
59:
defb    83,116,114,117,99,100,101,99,108,32,45,32,98,97,100,9
defb    110,101,108,101,109,0
psect   text

