psect   data
_array_A162:
defw    0
defw    9
defw    -10
defw    25
defw    -28
defw    21
defw    25
defw    -28
defw    7
defw    21
defw    25
defw    28
defw    -29
defw    11
defw    12
defw    13
defw    14
defw    -15
defw    4
defw    5
defw    21
defw    25
defw    -28
defw    6
defw    21
defw    25
defw    -28
defw    1
defw    21
defw    -28
defw    17
defw    20
defw    21
defw    22
defw    25
defw    26
defw    28
defw    -29
defw    3
defw    21
defw    25
defw    -28
defw    4
defw    5
defw    20
defw    21
defw    25
defw    -28
defw    2
defw    21
defw    25
defw    -28
defw    19
defw    23
defw    24
defw    -27
defw    20
defw    -28
defw    239
defw    -240
defw    133
defw    -134
defw    46
defw    -47
defw    43
defw    44
defw    46
defw    -47
defw    43
defw    44
defw    46
defw    47
defw    -48
defw    43
defw    44
defw    -47
defw    43
defw    44
defw    45
defw    46
defw    47
defw    -48
defw    43
defw    44
defw    45
defw    46
defw    -47
defw    45
defw    -47
defw    116
defw    117
defw    118
defw    119
defw    120
defw    121
defw    122
defw    123
defw    124
defw    127
defw    130
defw    131
defw    -132
defw    117
defw    118
defw    120
defw    125
defw    128
defw    131
defw    -132
defw    117
defw    118
defw    120
defw    126
defw    129
defw    131
defw    -132
defw    245
defw    -246
defw    212
defw    214
defw    -217
defw    218
defw    -221
defw    228
defw    229
defw    230
defw    231
defw    232
defw    233
defw    234
defw    235
defw    -236
defw    211
defw    -227
defw    224
defw    225
defw    -226
defw    214
defw    -219
defw    213
defw    -214
defw    135
defw    -136
defw    71
defw    72
defw    73
defw    -97
defw    93
defw    -94
defw    77
defw    78
defw    79
defw    80
defw    81
defw    -82
defw    85
defw    -86
defw    75
defw    -83
defw    73
defw    -91
defw    87
defw    -88
defw    30
defw    -31
defw    145
defw    146
defw    -147
defw    143
defw    -144
defw    175
defw    -178
defw    161
defw    -207
defw    185
defw    -204
defw    162
defw    163
defw    182
defw    183
defw    184
defw    -185
defw    161
defw    198
defw    199
defw    200
defw    -201
defw    173
defw    -180
defw    172
defw    -181
defw    161
defw    185
defw    186
defw    187
defw    205
defw    206
defw    208
defw    209
defw    -210
defw    169
defw    -171
defw    159
defw    165
defw    185
defw    194
defw    195
defw    196
defw    -203
defw    174
defw    -179
defw    163
defw    165
defw    188
defw    189
defw    191
defw    -193
defw    190
defw    -192
defw    176
defw    -179
defw    168
defw    -171
defw    177
defw    -178
defw    162
defw    -185
defw    161
defw    -163
defw    248
defw    -249
defw    40
defw    41
defw    -42
defw    38
defw    39
defw    40
defw    41
defw    -42
defw    40
defw    -41
defw    37
defw    38
defw    39
defw    40
defw    41
defw    -42
defw    38
defw    39
defw    40
defw    -41
defw    109
defw    -110
defw    243
defw    -244
defw    51
defw    -52
defw    152
defw    -153
defw    53
defw    55
defw    -56
defw    54
defw    -55
defw    107
defw    -108
defw    59
defw    60
defw    -61
defw    58
defw    -61
defw    58
defw    59
defw    -61
defw    105
defw    -106
defw    101
defw    -102
defw    101
defw    102
defw    -103
defw    156
defw    -157
defw    138
defw    -140
global  _sub_1F4B
global  ncsv, cret, indir
global  _sub_13D
global  _sub_6589
global  _array_AAE8
global  wrelop
global  _codeFrag
global  amul
global  brelop
global  _sub_47B2
global  __ctype_
global  brelop
global  _sub_66BC
global  _sub_63B8
global  brelop
global  _sub_2B2A
global  wrelop
global  _dopetab
global  adiv
global  _sub_2B79
global  brelop
psect   bss
F370:
defs    2
F365:
defs    2
F366:
defs    2
F367:
defs    2
F368:
defs    1
F369:
defs    2
psect   text
_sub_1F4B:
call ncsv
defw -16
ld      l,(ix+6)
ld      h,(ix+7)
inc     hl
ld      a,(hl)
or      a
dec     hl
jp      nz,L35
inc     hl
inc     hl
ld      (hl),0
dec     hl
dec     hl
L35:
ld      l,(hl)
ld      h,0
push    hl
ld      l,(ix+8)
ld      h,(ix+9)
push    hl
call    _sub_13D
pop     bc
pop     bc
ld      (ix+-2),l
ld      (ix+-1),h
ld      a,l
or      h
jp      nz,l12
L36:
;ld      hl,-1
;jp      cret
jp	ldHLFFFFcret
l12:
ld      a,(ix+12)
or      (ix+13)
jp      z,l16
xor     a
ld      l,a
ld      a,(ix+13)
and     128
ld      h,a
ld      a,l
or      h
jp      nz,l16
ld      l,(ix+12)
ld      h,(ix+13)
push    hl
ld      l,(ix+10)
ld      h,(ix+11)
push    hl
call    _sub_6589
pop     bc
pop     bc
ld      a,l
or      a
jp      nz,l16
ld      l,(ix+6)
ld      h,(ix+7)
ld      a,(hl)
cp      69
jp      nz,L33
ld      l,(ix+12)
ld      h,(ix+13)
push    hl
ld      e,(ix+6)
ld      d,(ix+7)
ld      hl,25
add     hl,de
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
add     hl,hl
ld      de,_array_AAE8
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
call    _sub_6589
pop     bc
pop     bc
ld      a,l
or      a
jp      nz,l16
L33:
;ld      hl,-1
;jp      cret
jp	ldHLFFFFcret
l16:
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      hl,0
call    wrelop
jp      p,l17
ld      de,_array_A162
ld      l,(ix+-2)
ld      h,(ix+-1)
inc     hl
ld      (ix+-2),l
ld      (ix+-1),h
dec     hl
add     hl,hl
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (ix+-10),c
ld      (ix+-9),b
ld      (F365),bc
jp      l18
l17:
ld      l,(ix+-2)
ld      h,(ix+-1)
ld      (ix+-10),l
ld      (ix+-9),h
ld      (F365),hl
l18:
ld      hl,(F365)
bit     7,h
jp      z,l19
ex      de,hl
ld      hl,0
or      a
sbc     hl,de
ld      (F365),hl
l19:
ld      de,10
ld      hl,(F365)
call    amul
ld      de,_codeFrag
add     hl,de
push    hl
pop     iy
ld      a,(iy+2)
or      a
jp      z,l20
ld      l,a
rla
sbc     a,a
ld      h,a
push    hl
ld      l,(ix+10)
ld      h,(ix+11)
push    hl
call    _sub_6589
pop     bc
pop     bc
ld      a,l
or      a
jp      z,l14
l20:
ld      b,72
ld      a,(iy+3)
call    brelop
jp      nc,l21
ld      a,(iy+4)
or      a
jp      z,l21
ld      e,(ix+6)
ld      d,(ix+7)
ld      hl,25
add     hl,de
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
ld      l,(hl)
ld      h,0
push    hl
ld      l,(iy+4)
push    hl
call    _sub_13D
pop     bc
pop     bc
ld      a,l
or      h
jp      z,l14
ld      a,(iy+5)
or      a
jp      z,l21
ld      e,(ix+6)
ld      d,(ix+7)
ld      hl,27
add     hl,de
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
ld      l,(hl)
ld      h,0
push    hl
ld      l,(iy+5)
push    hl
call    _sub_13D
pop     bc
pop     bc
ld      a,l
or      h
jp      z,l14
l21:
ld      a,(iy+0)
or      a
jp      z,l22
ld      l,a
rla
sbc     a,a
ld      h,a
push    hl
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
call    _sub_47B2
pop     bc
pop     bc
ld      a,l
or      a
jp      z,l14
l22:
ld      a,(iy+1)
ld      l,a
rla
sbc     a,a
ld      h,a
ld      (ix+-12),l
ld      (ix+-11),h
ld      (ix+-14),0
ld      (ix+-13),0
ld      a,(ix+12)
or      (ix+13)
jp      nz,l23
ld      a,(iy+3)
cp      69
jp      nz,l23
ld      a,l
rla
sbc     a,a
ld      h,a
ld      (ix+12),l
ld      (ix+13),h
l23:
ld      a,(ix+12)
or      (ix+13)
jp      z,l24
xor     a
ld      l,a
ld      a,(ix+13)
and     128
ld      h,a
ld      a,l
or      h
jp      z,L27
ld      a,(ix+-12)
or      (ix+-11)
jp      z,L27
ld      l,(ix+-12)
ld      h,(ix+-11)
push    hl
ld      l,(ix+12)
ld      a,(ix+13)
and     127
ld      h,a
push    hl
call    _sub_6589
pop     bc
pop     bc
ld      a,l
or      a
jp      z,l24
L27:
ld      l,(iy+8)
ld      h,(iy+9)
ld      (F366),hl
ld      a,l
or      h
jp      z,l25
ld      a,(hl)
cp      76
jp      nz,l27
inc     hl
ld      a,(hl)
or      a
jp      nz,l27
ld      hl,19f
ld      (F366),hl
jp      l27
l28:
ld      hl,(F366)
ld      a,(hl)
ld      (F368),a
cp      88
jp      z,L23
cp      71
jp      z,L23
cp      83
jp      nz,l30
ld      l,(ix+6)
ld      h,(ix+7)
ld      a,(hl)
cp      69
jp      nz,l30
L23:
ld      hl,(F366)
inc     hl
ld      (F366),hl

;ld      a,(hl)
;ld      e,a
;rla
;sbc     a,a
;ld      d,a
ld	e,(hl)
ld	d,0

ld      hl,__ctype_+1
add     hl,de
bit     2,(hl)
jp      z,l31
ld      hl,(F366)
L37:
ld      (F367),hl
jp      l33
l31:
ld      hl,0
jp      L37
L41:
inc     hl
ld      (F366),hl
l33:
ld      b,65
ld      hl,(F366)
ld      a,(hl)
call    brelop
ld      hl,(F366)
jp      m,L41
ld      a,(hl)
cp      76
jp      z,l38
cp      78
jp      z,l41
cp      82
jp      z,l40
jp      l27
l38:
ld      hl,(F367)
push    hl
ld      l,(ix+10)
ld      h,(ix+11)
push    hl
ld      l,(ix+12)
ld      h,(ix+13)
push    hl
ld      l,(ix+-12)
ld      h,(ix+-11)
push    hl
call    _sub_66BC
pop     bc
pop     bc
pop     bc
pop     bc
ld      (ix+-12),l
ld      (ix+-11),h
ld      a,l
or      h
jp      nz,l24
L39:
ld      (ix+-12),255
ld      (ix+-11),255
jp      l24
l40:
ld      l,(ix+12)
ld      h,(ix+13)
ld      (ix+-14),l
ld      (ix+-13),h
jp      l24
l41:
ld      a,(F368)
cp      83
jp      nz,l42
ld      l,(ix+6)
ld      h,(ix+7)
ld      a,(hl)
cp      69
jp      nz,l24
ld      hl,(F367)
push    hl
ld      e,(ix+6)
ld      d,(ix+7)
ld      hl,25
add     hl,de
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
add     hl,hl
ld      de,_array_AAE8
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
ld      l,(ix+12)
ld      h,(ix+13)
push    hl
ld      l,(ix+-12)
ld      h,(ix+-11)
L40:
push    hl
call    _sub_66BC
pop     bc
pop     bc
pop     bc
pop     bc
ld      a,l
or      h
jp      nz,l24
jp      L39
l42:
ld      a,(iy+2)
ld      l,a
rla
sbc     a,a
ld      h,a
push    hl
ld      l,(ix+12)
ld      h,(ix+13)
push    hl
ld      l,(ix+10)
ld      h,(ix+11)
push    hl
call    _sub_63B8
pop     bc
pop     bc
pop     bc
ld      a,l
or      a
jp      nz,l24
xor     a
ld      l,a
ld      a,(ix+13)
and     128
ld      h,a
ld      a,l
or      h
jp      z,L39
ld      hl,(F367)
push    hl
ld      l,(ix+10)
ld      h,(ix+11)
push    hl
ld      l,(ix+12)
ld      h,(ix+13)
push    hl
ld      a,(iy+2)
ld      l,a
rla
sbc     a,a
ld      h,a
jp      L40
l30:
ld      hl,(F366)
inc     hl
ld      (F366),hl
l27:
ld      hl,(F366)
ld      a,(hl)
or      a
jp      nz,l28
jp      l24
l25:
ld      hl,0
push    hl
ld      l,(ix+10)
ld      h,(ix+11)
push    hl
ld      l,(ix+12)
ld      h,(ix+13)
push    hl
ld      l,(ix+-12)
ld      h,(ix+-11)
push    hl
call    _sub_66BC
pop     bc
pop     bc
pop     bc
pop     bc
ld      (ix+-12),l
ld      (ix+-11),h
ld      a,l
or      h
jp      nz,l24
ld      (ix+-12),255
ld      (ix+-11),255
l24:
ld      de,-1
ld      l,(ix+-12)
ld      h,(ix+-11)
or      a
sbc     hl,de
jp      z,l14
ld      (ix+-8),0
ld      (ix+-7),0
ld      b,72
ld      a,(iy+3)
call    brelop
jp      c,l51
ld      l,(ix+6)
ld      h,(ix+7)
inc     hl
ld      (hl),0
push    ix
pop     hl
dec     hl
dec     hl
dec     hl
dec     hl
push    hl
ld      l,(ix+-12)
ld      h,(ix+-11)
push    hl
ld      l,(ix+10)
ld      h,(ix+11)
push    hl
ld      l,(iy+3)
ld      h,0
push    hl
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
call    _sub_1F4B
pop     bc
pop     bc
pop     bc
pop     bc
pop     bc
bit     7,h
jp      z,l53
ld      l,(ix+6)
ld      h,(ix+7)
inc     hl
ld      (hl),0
l14:
bit     7,(ix+-9)
jp      z,l16
jp      L36
l51:
ld      a,(iy+4)
or      a
jp      z,l54
ld      e,(ix+6)
ld      d,(ix+7)
ld      hl,25
add     hl,de
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
inc     hl
ld      (hl),0
push    ix
pop     hl
dec     hl
dec     hl
dec     hl
dec     hl
push    hl
ld      l,(ix+-12)
ld      h,(ix+-11)
push    hl
ld      l,(ix+10)
ld      h,(ix+11)
push    hl
ld      l,(iy+4)
ld      h,0
push    hl
ld      hl,25
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
call    _sub_1F4B
pop     bc
pop     bc
pop     bc
pop     bc
pop     bc
bit     7,h
jp      nz,l14
ld      a,(iy+5)
or      a
jp      z,l53
ld      e,(ix+6)
ld      d,(ix+7)
ld      hl,27
add     hl,de
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
inc     hl
ld      (hl),0
ld      hl,25
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
call    _sub_2B2A
pop     bc
ld      (ix+-16),l
ld      (ix+-15),h
ld      a,(ix+-14)
or      (ix+-13)
jp      nz,l57
ld      a,(iy+2)
or      a
jp      z,l58
ld      l,a
rla
sbc     a,a
ld      h,a
push    hl
ld      l,(ix+12)
ld      h,(ix+13)
push    hl
ld      l,(ix+10)
ld      h,(ix+11)
push    hl
call    _sub_63B8
pop     bc
pop     bc
pop     bc
ld      h,0
add     hl,hl
ld      de,_array_AAE8
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (ix+-14),c
ld      (ix+-13),b
jp      l59
l58:
ld      (ix+-14),0
ld      (ix+-13),0
l59:
ld      a,(ix+-16)
or      (ix+-14)
ld      l,a
ld      a,(ix+-15)
or      (ix+-13)
ld      h,a
ld      a,l
or      h
jp      nz,L20
ld      hl,0
jp      L19
L20:
ld      a,(ix+-16)
or      (ix+-14)
ld      l,a
ld      a,(ix+-15)
or      (ix+-13)
ld      h,a
set     7,h
L19:
ld      (ix+-14),l
ld      (ix+-13),h
l57:
push    ix
pop     de
ld      hl,-6
add     hl,de
push    hl
ld      l,(ix+-14)
ld      h,(ix+-13)
push    hl
ld      l,(ix+10)
ld      h,(ix+11)
push    hl
ld      l,(iy+5)
ld      h,0
push    hl
ld      e,(ix+6)
ld      d,(ix+7)
ld      hl,27
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
call    _sub_1F4B
pop     bc
pop     bc
pop     bc
pop     bc
pop     bc
bit     7,h
jp      nz,l14
ld      e,(ix+6)
ld      d,(ix+7)
ld      hl,27
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
call    _sub_2B2A
pop     bc
ld      (ix+-8),l
ld      (ix+-7),h
ld      a,l
and     (ix+-16)
ld      l,a
ld      a,h
and     (ix+-15)
ld      h,a
ld      a,l
or      h
jp      z,l61
ld      e,(ix+6)
ld      d,(ix+7)
ld      hl,27
add     hl,de
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
inc     hl
ld      (hl),0
push    ix
pop     de
ld      hl,-6
add     hl,de
push    hl
ld      l,(ix+-14)
ld      h,(ix+-13)
push    hl
ld      e,(ix+-16)
ld      d,(ix+-15)
ld      hl,-1
or      a
sbc     hl,de
ld      a,l
and     (ix+10)
ld      l,a
ld      a,h
and     (ix+11)
ld      h,a
push    hl
ld      l,(iy+5)
ld      h,0
push    hl
ld      e,(ix+6)
ld      d,(ix+7)
ld      hl,27
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
call    _sub_1F4B
pop     bc
pop     bc
pop     bc
pop     bc
pop     bc
ex      de,hl
ld      hl,0
call    wrelop
jp      p,l14
ld      e,(ix+6)
ld      d,(ix+7)
ld      hl,27
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
call    _sub_2B2A
pop     bc
ld      (ix+-8),l
ld      (ix+-7),h
l61:
ld      de,_dopetab
ld      l,(ix+6)
ld      h,(ix+7)
ld      l,(hl)
ld      h,0
add     hl,hl
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
bit     0,b
jp      nz,L17
ld      a,(ix+-8)
and     (ix+-4)
ld      l,a
ld      a,(ix+-7)
and     (ix+-3)
ld      h,a
ld      a,l
or      h
jp      z,l63
L17:
ld      a,(ix+-16)
and     (ix+-6)
ld      l,a
ld      a,(ix+-15)
and     (ix+-5)
ld      h,a
ld      a,l
or      h
jp      z,l64
ld      de,_dopetab
ld      l,(ix+6)
ld      h,(ix+7)
ld      l,(hl)
ld      h,0
add     hl,hl
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
bit     0,b
jp      nz,l14
ld      l,(ix+6)
ld      h,(ix+7)
inc     hl
inc     hl
ld      (hl),2
ld      (ix+-8),0
ld      (ix+-7),0
jp      l53
l64:
ld      l,(ix+6)
ld      h,(ix+7)
inc     hl
inc     hl
ld      (hl),1
jp      l53
l63:
ld      l,(ix+6)
ld      h,(ix+7)
inc     hl
inc     hl
ld      (hl),0
jp      l53
l54:
ld      a,(ix+-12)
or      (ix+-11)
jp      z,l53
ld      l,(ix+-12)
ld      h,(ix+-11)
ld      (ix+12),l
ld      (ix+13),h
l53:
ld      a,(iy+2)
or      a
jp      z,l70
ld      l,(ix+10)
ld      h,(ix+11)
ld      (F369),hl
bit     6,(iy+2)
jp      z,L15
ld      l,a
rla
sbc     a,a
ld      h,a
push    hl
ld      l,(ix+12)
ld      h,(ix+13)
push    hl
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
call    _sub_2B2A
ex      (sp),hl
call    _sub_63B8
pop     bc
pop     bc
pop     bc
ld      e,l
ld      h,0
ld      (F370),hl
ld      a,l
or      h
jp      nz,l71
L15:
bit     6,(iy+2)
jp      nz,l72
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
call    _sub_2B2A
pop     bc
ex      de,hl
ld      hl,-1
or      a
sbc     hl,de
ex      de,hl
ld      hl,(F369)
ld      a,l
and     e
ld      l,a
ld      a,h
and     d
ld      h,a
ld      (F369),hl
l72:
ld      e,(ix+-8)
ld      d,(ix+-7)
ld      hl,-1
or      a
sbc     hl,de
ex      de,hl
ld      hl,(F369)
ld      a,l
and     e
ld      l,a
ld      a,h
and     d
ld      h,a
ld      (F369),hl
ld      a,(iy+2)
ld      l,a
rla
sbc     a,a
ld      h,a
push    hl
ld      l,(ix+12)
ld      h,(ix+13)
push    hl
ld      hl,(F369)
push    hl
call    _sub_63B8
pop     bc
pop     bc
pop     bc
ld      e,l
ld      h,0
ld      (F370),hl
ld      a,l
or      h
jp      nz,l71
ld      a,(iy+2)
ld      l,a
rla
sbc     a,a
ld      h,a
push    hl
ld      hl,(F369)
push    hl
call    _sub_6589
pop     bc
pop     bc
ld      e,l
ld      h,0
ld      (F370),hl
ld      a,l
or      h
jp      z,l14
l71:
ld      a,(F370)
ld      e,(ix+6)
ld      d,(ix+7)
ld      l,e
ld      h,d
inc     hl
ld      l,(hl)
ld      h,0
add     hl,de
ld      de,9
add     hl,de
ld      (hl),a
jp      l74
l70:
ld      e,(ix+6)
ld      d,(ix+7)
ld      l,e
ld      h,d
inc     hl
ld      l,(hl)
ld      h,0
add     hl,de
ld      de,9
add     hl,de
ld      (hl),0
l74:
ld      de,_codeFrag
push    iy
pop     hl
or      a
sbc     hl,de
ld      de,10
call    adiv
ld      a,l
push    af
ld      e,(ix+6)
ld      d,(ix+7)
ld      l,e
ld      h,d
inc     hl
ld      a,(hl)
inc     (hl)
ld      l,a
ld      h,0
add     hl,de
inc     hl
inc     hl
inc     hl
pop     af
ld      (hl),a
ld      l,e
ld      h,d
push    hl
call    _sub_2B79
pop     bc
ld      h,0
ld      (F370),hl
ld      a,l
ld      e,(ix+6)
ld      d,(ix+7)
ld      l,e
ld      h,d
inc     hl
ld      l,(hl)
ld      h,0
add     hl,de
ld      de,14
add     hl,de
ld      (hl),a
ld      hl,(F370)
ld      a,l
or      h
jp      nz,l75
ld      l,(ix+6)
ld      h,(ix+7)
ld      a,(hl)
cp      69
jp      nz,l75
ex      de,hl
ld      hl,25
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (F370),bc
ld      l,e
ld      h,d
inc     hl
ld      l,(hl)
ld      h,0
add     hl,de
ld      de,14
add     hl,de
ld      (hl),c
l75:
ld      a,(ix+12)
or      (ix+13)
jp      z,L10
xor     a
ld      l,a
ld      a,(ix+13)
and     128
ld      h,a
ld      a,l
or      h
jp      nz,L10
ld      hl,(F370)
ld      a,l
or      h
jp      z,L3
push    hl
xor     a
ld      l,a
ld      a,(ix+13)
and     128
ld      h,a
ld      a,l
or      h
jp      nz,L13
ld      de,_array_AAE8
ld      l,(ix+12)
ld      h,(ix+13)
add     hl,hl
add     hl,de
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
jp      L12
L13:
ld      e,(ix+12)
ld      d,(ix+13)
ld      hl,-1
or      a
sbc     hl,de
L12:
push    hl
call    _sub_6589
pop     bc
pop     bc

;ld      h,0
;ld      de,(F370)
;or      a
;sbc     hl,de
ld	a,(F370)
cp	l

jp      nz,L3
L10:
xor     a
ld      l,a
ld      a,(ix+13)
and     128
ld      h,a
ld      a,l
or      h
jp      z,l76
ld      hl,(F370)
xor     a
ld      l,a
ld      a,h
and     128
ld      h,a
ld      a,l
or      h
jp      nz,L9
ld      de,_array_AAE8
ld      hl,(F370)
add     hl,hl
add     hl,de
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
jp      L8
L9:
ld      de,(F370)
ld      hl,-1
or      a
sbc     hl,de
L8:
ex      de,hl
push    de
ld      hl,(F370)
xor     a
ld      l,a
ld      a,h
and     128
ld      h,a
ld      a,l
or      h
jp      nz,L7
ld      de,_array_AAE8
ld      hl,(F370)
add     hl,hl
add     hl,de
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
jp      L6
L7:
ld      de,(F370)
ld      hl,-1
or      a
sbc     hl,de
L6:
ex      de,hl
push    de
xor     a
ld      l,a
ld      a,(ix+13)
and     128
ld      h,a
ld      a,l
or      h
jp      nz,L5
ld      de,_array_AAE8
ld      l,(ix+12)
ld      h,(ix+13)
add     hl,hl
add     hl,de
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
jp      L4
L5:
ld      e,(ix+12)
ld      d,(ix+13)
ld      hl,-1
or      a
sbc     hl,de
L4:
pop     de
ld      a,l
and     e
ld      l,a
ld      a,h
and     d
ld      h,a
pop     de
or      a
sbc     hl,de
jp      z,l76
L3:
ld      l,(ix+6)
ld      h,(ix+7)
inc     hl
dec     (hl)
jp      l14
l76:
ld      e,(ix+6)
ld      d,(ix+7)
ld      l,e
ld      h,d
inc     hl
ld      l,(hl)
ld      h,0
add     hl,de
ld      de,8
add     hl,de
ld      l,(hl)
ld      h,0
add     hl,hl
ld      de,_array_AAE8
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      l,(ix+14)
ld      h,(ix+15)
ld      (hl),c
inc     hl
ld      (hl),b
ld      b,72
ld      a,(iy+3)
call    brelop
jp      nc,L1
ld      a,(iy+4)
or      a
jp      z,l77
L1:
ld      l,(ix+14)
ld      h,(ix+15)
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      a,c
or      (ix+-4)
ld      c,a
ld      a,b
or      (ix+-3)
ld      b,a
ld      (hl),b
dec     hl
ld      (hl),c
l77:
ld      a,(iy+5)
or      a
jp      z,l78
ld      l,(ix+14)
ld      h,(ix+15)
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      a,c
or      (ix+-6)
ld      c,a
ld      a,b
or      (ix+-5)
ld      b,a
ld      (hl),b
dec     hl
ld      (hl),c
l78:
;ld      hl,1
;jp      cret
jp	ldHL1cret
psect   data
19:
defb    71,76,0
psect   text

