global  _sub_3DC9
global  ncsv, cret, indir
global  _sub_600E
global  _prWarning
global  _freeNode
global  _sub_475C
global  _byte_B014
global  _sub_3CDF
global  _sub_2BD0
global  _array_AFFD
global  wrelop
psect   text
_sub_3DC9:
global csv
call csv
push hl
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
push    hl
call    _sub_600E
pop     bc
push    hl
pop     iy
ld      a,(iy+0)
cp      4
jp      nz,l11
ld      l,(iy+25)
ld      h,(iy+26)
ld      a,(hl)
cp      67
jp      nz,l11
ld      hl,19f
push    hl
call    _prWarning
pop     bc
ld      e,(iy+25)
ld      d,(iy+26)
ld      hl,25
add     hl,de
ld      e,(hl)
inc     hl
ld      d,(hl)
inc     hl
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
ld      a,e
or      d
or      l
or      h
jp      z,l12
ld      (iy+0),5
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
call    _freeNode
pop     bc
ld      l,(iy+27)
ld      h,(iy+28)
ld      (iy+25),l
ld      (iy+26),h
l11:
xor     a
ld      (_byte_B014),a
ld      a,(iy+0)
cp      15
jp      nz,l14
ld      (iy+0),37
jp      l15
l12:
push    iy
call    _sub_475C
;pop     bc
;jp      cret
jp	popBCcret
l14:
ld      a,(iy+0)
cp      19
jp      nz,l15
ld      (iy+0),38
l15:
push    iy
call    _sub_3CDF
pop     bc
push    hl
pop     iy
ld      a,(_byte_B014)
or      a
push    iy
jp      z,L1
call    _sub_600E
push    hl
pop     iy
ex      (sp),hl
L1:
call    _sub_2BD0
pop     bc
ld      (ix+-2),0
ld      (ix+-1),0
jp      l21
l18:
ld      de,_array_AFFD
ld      l,(ix+-2)
ld      h,(ix+-1)
add     hl,hl
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
call    _sub_2BD0
pop     bc
ld      l,(ix+-2)
ld      h,(ix+-1)
inc     hl
ld      (ix+-2),l
ld      (ix+-1),h
l21:
ld      a,(_byte_B014)
ld      e,a
ld      d,0
ld      l,(ix+-2)
ld      h,(ix+-1)
call    wrelop
jp      c,l18
jp      cret
global  _sub_3EAA
global  _dopetab
global  _sub_14F3
global  _sub_39CA
global  _warningMsg
global  _sub_3B65
global  _sub_3A79
global  _sub_3BC6
_sub_3EAA:
global csv
call csv
push hl
push hl
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
ld      de,_dopetab
ld      l,(iy+0)
ld      h,0
add     hl,hl
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      a,c
and     12
ld      l,a
xor     a
ld      h,a
ld      (ix+-4),l
ld      (ix+-3),h
ld      a,l
or      h
jp      z,l23
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
call    _sub_3EAA
pop     bc
ld      (iy+25),l
ld      (iy+26),h
l23:

;ld      de,8
;ld      l,(ix+-4)
;ld      h,(ix+-3)
;or      a
;sbc     hl,de
ld	a,(ix+-4)
cp	8

jp      nz,l24
ld      l,(iy+27)
ld      h,(iy+28)
push    hl
call    _sub_3EAA
pop     bc
ld      (iy+27),l
ld      (iy+28),h
l24:
ld      a,(iy+0)
cp      20
jp      nz,l25
ld      l,(iy+25)
ld      h,(iy+26)
ld      a,(hl)
cp      68
jp      nz,l25
push    iy
call    _sub_14F3
pop     bc
ld      a,l
cp      3
jp      nz,l25
ld      l,(iy+25)
ld      h,(iy+26)
ld      (ix+-2),l
ld      (ix+-1),h
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      hl,23
add     hl,de
ld      e,(iy+23)
ld      d,(iy+24)
ld      (hl),e
inc     hl
ld      (hl),d
ld      l,(iy+27)
ld      h,(iy+28)
push    hl
call    _freeNode
pop     bc
push    iy
call    _freeNode
pop     bc
;ld      l,(ix+-2)
;ld      h,(ix+-1)
;jp      cret
jp	ldLIXm2ldHIXm1cret
l25:
ld      a,(ix+-4)
or      (ix+-3)
jp      z,L3
ld      l,(iy+25)
ld      h,(iy+26)
ld      a,(hl)
cp      67
jp      z,l26
L3:
push    iy
L12:
;pop     hl
;jp      cret
jp	popHLcret
l26:
ld      a,(iy+0)
cp      20
jp      nz,l27
push    iy
call    _sub_39CA
;pop     bc
;jp      cret
jp	popBCcret
l27:

;ld      de,8
;ld      l,(ix+-4)
;ld      h,(ix+-3)
;or      a
;sbc     hl,de
ld	a,(ix+-4)
cp	8

jp      nz,l28
ld      l,(iy+27)
ld      h,(iy+28)
ld      a,(hl)
cp      67
push    iy
jp      z,L5
jp      L12
l28:
push    iy
L5:
call    _sub_14F3
pop     bc
ld      a,l
cp      2
ld      a,(iy+0)
jp      nz,L8
cp      6
jp      z,l38
cp      24
jp      z,l38
cp      30
jp      z,l35
cp      32
jp      z,l35
cp      45
jp      z,l35
cp      46
jp      z,l35
cp      47
jp      z,l38
L8:
cp      1
jp      z,l62
cp      2
jp      z,l48
cp      6
jp      z,l60
cp      7
jp      z,l60
cp      8
jp      z,l60
cp      12
jp      z,l60
cp      14
jp      z,l60
cp      18
jp      z,l60
cp      21
jp      z,l61
cp      24
jp      z,l60
cp      30
jp      z,l48
cp      31
jp      z,l60
cp      32
jp      z,l48
cp      41
jp      z,l48
cp      45
jp      z,l48
cp      46
jp      z,l48
cp      47
jp      z,l60
cp      58
jp      z,l60
cp      60
jp      z,l60
cp      61
jp      z,l60
cp      63
jp      z,l63
L13:
push    iy
jp      L12
l35:
ld      hl,29f
L14:
ld      (_warningMsg),hl
jp      L13
l38:
ld      l,(iy+0)
ld      h,0
push    hl
ld      e,(iy+27)
ld      d,(iy+28)
ld      hl,25
add     hl,de
ld      e,(hl)
inc     hl
ld      d,(hl)
inc     hl
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
push    hl
push    de
ld      e,(iy+25)
ld      d,(iy+26)
ld      hl,25
add     hl,de
push    hl
call    _sub_3B65
pop     bc
pop     bc
pop     bc
pop     bc
l39:

;ld      de,8
;ld      l,(ix+-4)
;ld      h,(ix+-3)
;or      a
;sbc     hl,de
ld	a,(ix+-4)
cp	8

jp      nz,l40
ld      l,(iy+27)
ld      h,(iy+28)
push    hl
call    _sub_475C
pop     bc
l40:
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
push    iy
call    _sub_3A79
pop     bc
pop     bc
push    iy
call    _freeNode
pop     bc
ld      l,(iy+25)
ld      h,(iy+26)
jp      cret
l48:
ld      hl,39f
jp      L14
l60:
ld      l,(iy+0)
ld      h,0
push    hl
ld      e,(iy+27)
ld      d,(iy+28)
ld      hl,25
add     hl,de
ld      e,(hl)
inc     hl
ld      d,(hl)
inc     hl
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
push    hl
push    de
ld      e,(iy+25)
ld      d,(iy+26)
ld      hl,25
add     hl,de
push    hl
call    _sub_3BC6
pop     bc
pop     bc
pop     bc
pop     bc
jp      l39
l61:
ld      e,(iy+25)
ld      d,(iy+26)
ld      hl,25
add     hl,de
ld      e,(hl)
inc     hl
ld      d,(hl)
inc     hl
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
push    hl
push    de
ld      hl,0
pop     bc
or      a
sbc     hl,bc
pop     bc
ex      de,hl
ld      hl,0
sbc     hl,bc
L10:
push    hl
push    de
ld      e,(iy+25)
ld      d,(iy+26)
ld      hl,25
add     hl,de
pop     de
ld      (hl),e
inc     hl
ld      (hl),d
inc     hl
pop     bc
ld      (hl),c
inc     hl
ld      (hl),b
jp      l39
l62:
ld      e,(iy+25)
ld      d,(iy+26)
ld      hl,25
add     hl,de
ld      e,(hl)
inc     hl
ld      d,(hl)
inc     hl
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
ld      a,e
or      d
or      l
or      h
ld      de,1
jp      z,L2
dec     de
L2:
ld      a,d
rla
sbc     a,a
ld      l,a
ld      h,a
jp      L10
l63:
ld      e,(iy+25)
ld      d,(iy+26)
ld      hl,25
add     hl,de
ld      e,(hl)
inc     hl
ld      d,(hl)
inc     hl
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
push    hl
push    de
ld      hl,-1
pop     bc
or      a
sbc     hl,bc
pop     bc
ex      de,hl
ld      hl,-1
sbc     hl,bc
jp      L10
global  _sub_415E
global  _allocNode
global  _typeLong
_sub_415E:
global csv
call csv
call    _allocNode
push    hl
pop     iy
ld      (iy+0),67
ld      hl,(_typeLong)
ld      (iy+23),l
ld      (iy+24),h
ld      e,(ix+6)
ld      d,(ix+7)
ld      l,(ix+8)
ld      h,(ix+9)
ld      (iy+25),e
ld      (iy+26),d
ld      (iy+27),l
ld      (iy+28),h
;push    iy
;pop     hl
;jp      cret
jp	pushIYpopHLcret
psect   data
19:
defb    99,111,110,115,116,97,110,116,32,99,111,110,100,105,116,105
defb    111,110,97,108,32,98,114,97,110,99,104,0
29:
defb    99,111,110,115,116,97,110,116,32,114,101,108,97,116,105,111
defb    110,97,108,32,101,120,112,114,101,115,115,105,111,110,0
39:
defb    99,111,110,115,116,97,110,116,32,114,101,108,97,116,105,111
defb    110,97,108,32,101,120,112,114,101,115,115,105,111,110,0
psect   text

