include cgen.inc
global  _sub_43EF
global  ncsv, cret, indir
global  _allocNode
global  _typeLong
global  _typeB
global  _typeVar
global  _dopetab
global  _freeNode
global  _typeX
global  wrelop
global  _sub_385B
global  _sub_37ED
global  _typeChar
global  _nodesize
global  _prWarning
global  _sub_475C
psect   text
_sub_43EF:
call ncsv
defw -6
call    _allocNode
push    hl
pop     iy
ld      a,(ix+6)
ld      (iy+0),a
ld      l,(ix+8)
ld      h,(ix+9)
ld      (iy+25),l
ld      (iy+26),h
ld      l,(ix+10)
ld      h,(ix+11)
ld      (iy+27),l
ld      (iy+28),h
ld      de,_dopetab
ld      l,(iy+0)
ld      h,0
add     hl,hl
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      a,c
and     48
ld      l,a
xor     a
ld      h,a
or      a
jp      nz,l16
ld      a,l
cp      16
jp      z,l13
cp      32
jp      z,l14
cp      48
jp      z,l15
l16:
ld      e,(ix+8)
ld      d,(ix+9)
ld      hl,23
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (iy+23),c
ld      (iy+24),b
ld      hl,21
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (iy+21),c
ld      (iy+22),b
l18:
ld      a,(iy+0)
cp      3
jp      z,l30
cp      9
jp      z,l25
cp      10
jp      z,l28
cp      13
jp      z,l28
cp      20
jp      z,l24
cp      22
jp      z,l19
cp      27
jp      z,l29
cp      28
jp      z,l24
cp      48
jp      z,l24
l17:
;push    iy
;pop     hl
;jp      cret
jp	pushIYpopHLcret
l13:
ld      hl,(_typeLong)
L5:
ld      (iy+23),l
ld      (iy+24),h
jp      l18
l14:
ld      hl,(_typeB)
jp      L5
l15:
ld      hl,(_typeVar)
jp      L5
l19:
ld      l,(ix+8)
ld      h,(ix+9)
ld      a,(hl)
cp      65
jp      nz,l20
ex      de,hl
ld      hl,23
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (ix+-2),c
ld      (ix+-1),b
push    iy
call    _freeNode
ld      l,(ix+8)
ld      h,(ix+9)
ex      (sp),hl
call    _freeNode
pop     bc
ld      l,(ix+10)
ld      h,(ix+11)
push    hl
pop     iy
ld      l,(ix+-2)
ld      h,(ix+-1)
ld      (iy+23),l
ld      (iy+24),h
ex      de,hl
ld      hl,19
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      l,(iy+25)
ld      h,(iy+26)
add     hl,hl
add     hl,bc
inc     hl
inc     hl
ld      e,(hl)
inc     hl
ld      d,(hl)
ld      a,d
rla
sbc     a,a
ld      l,a
ld      h,a
push    hl
push    de
ld      e,(ix+10)
ld      d,(ix+11)
ld      hl,25
add     hl,de
pop     de
ld      (hl),e
inc     hl
ld      (hl),d
inc     hl
pop     bc
ld      (hl),c
inc     hl
ld      (hl),b
jp      l17
l20:
ld      e,(iy+23)
ld      d,(iy+24)
ld      hl,19
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      e,(ix+10)
ld      d,(ix+11)
ld      hl,25
add     hl,de
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
add     hl,hl
add     hl,bc
inc     hl
inc     hl
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (ix+-2),c
ld      (ix+-1),b
ld      e,c
ld      d,b
ld      hl,15
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (iy+23),c
ld      (iy+24),b
ld      hl,13
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (iy+21),c
ld      (iy+22),b
ld      hl,17
add     hl,de
ld      e,(hl)
inc     hl
ld      d,(hl)
ld      a,d
rla
sbc     a,a
ld      l,a
ld      h,a
push    hl
push    de
ld      e,(ix+10)
ld      d,(ix+11)
ld      hl,25
add     hl,de
pop     de
ld      (hl),e
inc     hl
ld      (hl),d
inc     hl
pop     bc
ld      (hl),c
inc     hl
ld      (hl),b
ld      e,(ix+10)
ld      d,(ix+11)
ld      hl,23
add     hl,de
ld      de,(_typeX)
ld      (hl),e
inc     hl
ld      (hl),d
ld      l,(ix+-2)
ld      h,(ix+-1)
inc     hl
inc     hl
inc     hl
bit     4,(hl)
jp      z,l17
call    _allocNode
ld      (ix+8),l
ld      (ix+9),h
push    iy
pop     hl
ld      e,(ix+8)
ld      d,(ix+9)
push    hl
ld      bc,29
ldir
pop     hl
ld      e,(ix+8)
ld      d,(ix+9)
ld      hl,25
add     hl,de
push    iy
pop     de
ld      (hl),e
inc     hl
ld      (hl),d
ld      l,(ix+8)
ld      h,(ix+9)
push    hl
pop     iy
ld      (iy+0),71
ld      l,(ix+-2)
ld      h,(ix+-1)
L2:
ld      (iy+27),l
ld      (iy+28),h
jp      l17
l24:
ld      e,(iy+27)
ld      d,(iy+28)
ld      hl,23
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (iy+23),c
ld      (iy+24),b
ld      hl,21
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (iy+21),c
ld      (iy+22),b
jp      l17
l25:
ld      a,(iy+21)
or      (iy+22)
jp      nz,l26
ld      e,(iy+23)
ld      d,(iy+24)
ld      hl,11
add     hl,de
ld      e,(hl)
inc     hl
ld      d,(hl)
ld      hl,1
call    wrelop
jp      nc,l26
ld      e,(iy+23)
ld      d,(iy+24)
ld      hl,13
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (iy+21),c
ld      (iy+22),b
ld      hl,15
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (iy+23),c
ld      (iy+24),b
l26:
push    iy
call    _sub_385B
L4:
pop     bc
jp      l17
l28:
push    iy
call    _sub_37ED
jp      L4
l29:
ld      hl,(_typeChar)
ld      (iy+23),l
ld      (iy+24),h
ld      (iy+21),1
ld      (iy+22),0
jp      l17
l30:
ld      l,(iy+25)
ld      h,(iy+26)
ld      a,(hl)
cp      66
jp      nz,l31
ex      de,hl
ld      hl,25
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      hl,9
add     hl,bc
ld      e,(hl)
inc     hl
ld      d,(hl)
ld      hl,0
ld      (ix+-6),e
ld      (ix+-5),d
ld      (ix+-4),l
ld      (ix+-3),h
jp      l32
l31:
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
call    _nodesize
pop     bc
ex      de,hl
ld      hl,0
ld      (ix+-6),e
ld      (ix+-5),d
ld      (ix+-4),l
ld      (ix+-3),h
l32:
ld      a,(ix+-6)
or      (ix+-5)
or      (ix+-4)
or      (ix+-3)
jp      nz,l33
ld      hl,19f
push    hl
call    _prWarning
pop     bc
l33:
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
call    _sub_475C
pop     bc
ld      (iy+0),67
ld      hl,(_typeLong)
ld      (iy+23),l
ld      (iy+24),h
ld      (iy+21),0
ld      (iy+22),0
ld      e,(ix+-6)
ld      d,(ix+-5)
ld      l,(ix+-4)
ld      h,(ix+-3)
ld      (iy+25),e
ld      (iy+26),d
jp      L2
global  _sub_46F7
global  aland
global  arelop
global  asalrsh
_sub_46F7:
global csv
call csv
push hl
ld      e,(ix+6)
ld      d,(ix+7)
ld      l,(ix+8)
ld      h,(ix+9)
push    hl
push    de
ex      de,hl
ld      bc,-1
add     hl,bc
ex      de,hl
adc     hl,bc
call    aland
ld      a,e
or      d
or      l
or      h
jp      nz,L6
ld      de,1
ld      hl,0
push    hl
push    de
ld      e,(ix+6)
ld      d,(ix+7)
ld      l,(ix+8)
ld      h,(ix+9)
call    arelop
jp      p,l35
L6:
;ld      l,0
;jp      cret
jp	ldL0cret
l35:
ld      (ix+-1),0
jp      l39
l38:
inc     (ix+-1)
l39:
ld      b,1
push    ix
pop     de
ld      hl,6
add     hl,de
call    asalrsh
ld      a,e
or      d
or      l
or      h
jp      nz,l38
ld      a,(ix+-1)
inc     a
ld      l,a
jp      cret
_sub_475C:
global csv
call csv
push hl
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
ld      de,_dopetab
ld      l,(iy+0)
ld      h,0
add     hl,hl
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      a,c
and     12
ld      l,a
xor     a
ld      h,a
ld      (ix+-2),l
ld      (ix+-1),h
ld      a,l
or      h
jp      z,l41
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
call    _sub_475C
pop     bc

;ld      de,8
;ld      l,(ix+-2)
;ld      h,(ix+-1)
;or      a
;sbc     hl,de
ld	a,(ix+-2)
cp	8

jp      nz,l41
ld      l,(iy+27)
ld      h,(iy+28)
push    hl
call    _sub_475C
pop     bc
l41:
push    iy
call    _freeNode
jp      cret
global  _sub_47B2
global  arelop
global  arelop
global  _sub_3968
global  _sub_14F3
global  _sub_2C5E
global  arelop
global  arelop
global  arelop
global  arelop
global  shal
global  lland
global  shal
global  asalor
global  arelop
global  arelop
_sub_47B2:
global csv
call csv
push hl
push hl
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
ld      l,(ix+8)
ld      h,(ix+9)
dec     hl
xor     a
cp      h
jp      c,L73
jp      nz,L8
ld      a,29
cp      l
jp      c,L73
L8:
add     hl,hl
ld      de,S111
add     hl,de
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
jp      (hl)
l46:
ld      l,(iy+27)
ld      h,(iy+28)
push    hl
pop     iy
l47:
ld      de,1
ld      hl,0
push    hl
push    de
ld      e,(iy+25)
ld      d,(iy+26)
ld      l,(iy+27)
ld      h,(iy+28)
call    arelop
jp      m,L102
ld      de,3
ld      hl,0
push    hl
push    de
ld      e,(iy+25)
ld      d,(iy+26)
ld      l,(iy+27)
ld      h,(iy+28)
call    arelop
jp      p,L102
L95:
;ld      hl,1
;jp      cret
jp	ldHL1cret
l48:
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
pop     iy
l49:
push    iy
call    _nodesize
pop     bc
ld      de,2
L57:
or      a
sbc     hl,de
jp      nz,L73
push    iy
call    _sub_3968
pop     bc
ld      a,l
or      a
jp      nz,L73
;ld      l,1
;jp      cret
jp	ldL1cret
l51:
push    iy
call    _sub_14F3
pop     bc
ld      a,l
cp      3
jp      nz,l53
L73:
;ld      l,0
;jp      cret
jp	ldL0cret
l54:
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
pop     iy
l55:
l53:
push    iy
call    _nodesize
pop     bc
ld      de,4
jp      L57
l57:
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
pop     iy
l58:
push    iy
call    _sub_3968
L76:
;pop     bc
;jp      cret
jp	popBCcret
l59:
ld      a,(iy+25)
cp      8
jp      z,L95
cp      9
L100:
jp      nz,L102
jp      L95
l60:
ld      e,(iy+25)
ld      d,(iy+26)
ld      l,(iy+27)
ld      h,(iy+28)
push    hl
push    de
push    iy
call    _sub_2C5E
pop     bc
pop     bc
pop     bc
ld      (ix+-4),e
ld      (ix+-3),d
ld      (ix+-2),l
ld      (ix+-1),h
ld      de,-128
ld      hl,-1
push    hl
push    de
ld      e,(ix+-4)
ld      d,(ix+-3)
ld      l,(ix+-2)
ld      h,(ix+-1)
call    arelop
jp      m,L102
ld      de,125
ld      hl,0
push    hl
push    de
ld      e,(ix+-4)
ld      d,(ix+-3)
ld      l,(ix+-2)
ld      h,(ix+-1)
L97:
call    arelop
jp      p,L102
jp      L95
l61:
ld      de,1
ld      hl,0
push    hl
push    de
ld      e,(iy+25)
ld      d,(iy+26)
ld      l,(iy+27)
ld      h,(iy+28)
call    arelop
jp      m,L102
ld      de,5
ld      hl,0
push    hl
push    de
ld      e,(iy+25)
ld      d,(iy+26)
ld      l,(iy+27)
ld      h,(iy+28)
jp      L97
l62:
ld      e,(iy+25)
ld      d,(iy+26)
ld      l,(iy+27)
ld      h,(iy+28)
ld      (ix+-4),e
ld      (ix+-3),d
ld      (ix+-2),l
ld      (ix+-1),h
push    iy
call    _sub_14F3
pop     bc
ld      a,l
cp      2
jp      nz,l63
ld      e,(ix+-4)
ld      d,(ix+-3)
ld      l,(ix+-2)
ld      h,(ix+-1)
push    hl
push    de
push    iy
call    _nodesize
pop     bc
add     hl,hl
add     hl,hl
add     hl,hl
ld      b,l
ld      hl,1
call    shal
ex      de,hl
ld      hl,0
call    lland
ld      a,e
or      d
or      l
or      h
jp      z,l63
push    iy
call    _nodesize
pop     bc
add     hl,hl
add     hl,hl
add     hl,hl
ld      b,l
ld      hl,1
call    shal
dec     hl
ex      de,hl
ld      hl,-1
or      a
sbc     hl,de
ex      de,hl
ld      hl,0
push    hl
push    de
push    ix
pop     hl
dec     hl
dec     hl
dec     hl
dec     hl
call    asalor
l63:
bit     7,(ix+-1)
jp      z,L102
ld      de,-4
ld      hl,-1
push    hl
push    de
ld      e,(ix+-4)
ld      d,(ix+-3)
ld      l,(ix+-2)
ld      h,(ix+-1)
call    arelop
jp      m,L102
jp      L95
l64:
ld      l,(iy+27)
ld      h,(iy+28)
push    hl
pop     iy
l65:
push    iy
call    _nodesize
pop     bc

;ld      de,1
;or      a
;sbc     hl,de
ld	a,l
cp	1

jp      nz,L102
push    iy
call    _sub_3968
pop     bc
ld      a,l
or      a
jp      L100
l66:
push    iy
call    _nodesize
pop     bc

;ld      de,4
;or      a
;sbc     hl,de
ld	a,l
cp	4

jp      nz,L73
jp      l68
l69:
push    iy
call    _nodesize
pop     bc

;ld      de,2
;or      a
;sbc     hl,de
ld	a,l
cp	2

jp      nz,L73
l68:
push    iy
call    _sub_14F3
pop     bc
ld      a,l
cp      3
jp      z,L73
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
call    _sub_14F3
pop     bc
ld      a,l
cp      3
jp      z,L73
push    iy
call    _sub_14F3
pop     bc
ld      a,l
cp      2
L101:
jp      z,L95
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
call    _sub_14F3
pop     bc
ld      a,l
cp      2
jp      L100
l72:
ld      a,(iy+25)
or      (iy+26)
or      (iy+27)
or      (iy+28)
L83:
ld      hl,1
jp      z,cret
dec     hl
jp      cret
l73:
push    iy
call    _nodesize
pop     bc

;ld      de,4
;or      a
;sbc     hl,de
ld	a,l
cp	4

jp      nz,L73
l75:
push    iy
call    _sub_14F3
pop     bc
ld      a,l
cp      1
jp      nz,L102
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
call    _sub_14F3
pop     bc
ld      a,l
cp      1
jp      L100
l76:
push    iy
call    _nodesize
pop     bc

;ld      de,2
;or      a
;sbc     hl,de
ld	a,l
cp	2

jp      nz,L73
jp      l75
l78:
ld      de,1
ld      hl,0
push    hl
push    de
ld      e,(iy+25)
ld      d,(iy+26)
ld      l,(iy+27)
ld      h,(iy+28)
call    arelop
ld      bc,1
jp      z,L18
dec     bc
L18:
ld      l,c
jp      cret
l79:
ld      e,(iy+27)
ld      d,(iy+28)
ld      hl,25
add     hl,de
ld      e,(hl)
inc     hl
ld      d,(hl)
inc     hl
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
L63:
push    hl
push    de
call    _sub_46F7
pop     bc
jp      L76
l80:
ld      e,(iy+27)
ld      d,(iy+28)
ld      hl,25
add     hl,de
ld      e,(hl)
inc     hl
ld      d,(hl)
inc     hl
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
push    hl
push    de
ld      hl,-1
pop     bc
or      a
sbc     hl,bc
pop     bc
ex      de,hl
ld      hl,-1
sbc     hl,bc
jp      L63
l81:
push    iy
call    _nodesize
pop     bc

;ld      de,4
;or      a
;sbc     hl,de
ld	a,l
cp	4

jp      nz,L73
l83:
push    iy
call    _sub_14F3
pop     bc
ld      a,l
cp      1
jp      z,L17
push    iy
call    _sub_14F3
pop     bc
ld      a,l
cp      2
jp      z,L17
L102:
;ld      hl,0
;jp      cret
jp	ldHL0cret
l84:
push    iy
call    _nodesize
pop     bc

;ld      de,2
;or      a
;sbc     hl,de
ld	a,l
cp	2

jp      nz,L73
jp      l83
l86:
push    iy
call    _nodesize
pop     bc

;ld      de,1
;or      a
;sbc     hl,de
ld	a,l
cp	1

jp      z,l83
jp      L73
L17:
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
call    _sub_14F3
pop     bc
ld      a,l
cp      3
jp      L100
l88:
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
call    _nodesize
pop     bc
ld      de,1
L66:
or      a
sbc     hl,de
jp      nz,L73
jp      l90
l91:
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
call    _nodesize
pop     bc
ld      de,2
jp      L66
l93:
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
call    _nodesize
pop     bc

;ld      de,4
;or      a
;sbc     hl,de
ld	a,l
cp	4

jp      nz,L73
l90:
push    iy
call    _sub_14F3
pop     bc
ld      a,l
cp      3
jp      nz,L73
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
call    _sub_14F3
pop     bc
ld      a,l
cp      1
jp      L101
l97:
push    iy
call    _sub_14F3
pop     bc
ld      a,l
cp      3
jp      L83
psect   data
S111:
defw    l79
defw    l80
defw    l65
defw    l58
defw    l55
defw    l49
defw    l51
defw    l97
defw    l86
defw    l64
defw    l48
defw    l54
defw    l46
defw    l59
defw    l60
defw    l78
defw    l69
defw    l76
defw    l84
defw    l73
defw    l66
defw    l93
defw    l91
defw    l88
defw    l81
defw    l61
defw    l62
defw    l57
defw    l47
defw    l72
global  _sub_4B89
psect   text
_sub_4B89:
global csv
call csv
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
ld      de,_dopetab
ld      l,(iy+0)
ld      h,0
add     hl,hl
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
bit     4,c
jp      nz,L105
ld      a,(iy+0)
cp      9
jp      nz,L110
ld      l,(iy+25)
ld      h,(iy+26)
ld      a,(hl)
cp      66
jp      z,L105
L110:
ld      a,(iy+0)
cp      14
jp      nz,L104
ld      l,(iy+27)
ld      h,(iy+28)
ld      a,(hl)
cp      67
jp      nz,L104
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
call    _sub_4B89
pop     bc
ld      a,l
or      a
jp      nz,L105
L104:
;ld      hl,0
;jp      cret
jp	ldHL0cret
L105:
;ld      hl,1
;jp      cret
jp	ldHL1cret
global  _sub_4BE5
_sub_4BE5:
global csv
call csv
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
ld      a,(iy+0)
cp      67
jp      nz,L113
ld      a,(iy+25)
or      (iy+26)
or      (iy+27)
or      (iy+28)
jp      nz,L113
;ld      hl,1
;jp      cret
jp	ldHL1cret
L113:
;ld      hl,0
;jp      cret
jp	ldHL0cret
global  _sub_4C12
_sub_4C12:
global csv
call csv
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
ld      a,(iy+0)
cp      9
jp      nz,l101
ld      l,(iy+25)
ld      h,(iy+26)
ld      a,(hl)
cp      66
jp      nz,l101
L117:
;ld      hl,1
;jp      cret
jp	ldHL1cret
l101:
ld      de,_dopetab
ld      l,(iy+0)
ld      h,0
add     hl,hl
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
bit     4,c
jp      z,l102
;ld      hl,0
;jp      cret
jp	ldHL0cret
l102:
push    iy
call    _sub_4B89
pop     bc
ld      a,l
or      a
jp      nz,L117
ld      de,_dopetab
ld      l,(iy+0)
ld      h,0
add     hl,hl
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      a,c
and     15
ld      l,a
xor     a
ld      h,a
jp      cret
global  _sub_4C6D
_sub_4C6D:
global csv
call csv
ld      e,(ix+6)
ld      d,(ix+7)
ld      hl,25
add     hl,de
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
ld      a,(hl)
cp      69
ld      hl,1
jp      z,cret
dec     hl
jp      cret
global  _sub_4C8B
global  _invertTest
_sub_4C8B:
global csv
call csv
push hl
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
ld      l,(iy+25)
ld      h,(iy+26)
ld      (ix+-2),l
ld      (ix+-1),h
ld      a,(hl)
cp      1
jp      nz,l106
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      hl,25
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (ix+-2),c
ld      (ix+-1),b
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
call    _freeNode
pop     bc
push    iy
call    _freeNode
pop     bc
L122:
;ld      l,(ix+-2)
;ld      h,(ix+-1)
;jp      cret
jp	ldLIXm2ldHIXm1cret
l106:
ld      de,_dopetab
ld      l,(ix+-2)
ld      h,(ix+-1)
ld      l,(hl)
ld      h,0
add     hl,hl
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      a,c
and     44
ld      l,a
ld      a,b
and     1
ld      h,a
ld      de,40
or      a
sbc     hl,de
jp      nz,l107
push    iy
call    _freeNode
ld      l,(ix+-2)
ld      h,(ix+-1)
ld      l,(hl)
ld      h,0
ex      (sp),hl
call    _invertTest
pop     bc
L123:
ld      a,l
ld      l,(ix+-2)
ld      h,(ix+-1)
ld      (hl),a
jp      L122
l107:
ld      de,_dopetab
ld      l,(ix+-2)
ld      h,(ix+-1)
ld      l,(hl)
ld      h,0
add     hl,hl
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
bit     5,c
jp      z,l108
ld      hl,0
push    hl
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      hl,25
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
ld      l,1
push    hl
call    _sub_43EF
pop     bc
pop     bc
pop     bc
push    hl
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      hl,25
add     hl,de
pop     de
ld      (hl),e
inc     hl
ld      (hl),d
ld      hl,0
push    hl
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      hl,27
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
ld      l,1
push    hl
call    _sub_43EF
pop     bc
pop     bc
pop     bc
push    hl
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      hl,27
add     hl,de
pop     de
ld      (hl),e
inc     hl
ld      (hl),d
push    iy
call    _freeNode
pop     bc
ld      l,(ix+-2)
ld      h,(ix+-1)
ld      a,(hl)
cp      8
jp      z,L120
ld      hl,8
jp      L123
L120:
ld      hl,61
jp      L123
l108:
;push    iy
;pop     hl
;jp      cret
jp	pushIYpopHLcret
global  _sub_4DA3
global  _sub_415E
_sub_4DA3:
global csv
call csv
push hl
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
ld      e,(iy+25)
ld      d,(iy+26)
ld      hl,21
add     hl,de
ld      a,(hl)
cp      1
jp      nz,L124
ld      hl,17
add     hl,de
ld      e,(hl)
inc     hl
ld      d,(hl)
ld      a,d
rla
sbc     a,a
ld      l,a
ld      h,a
push    hl
push    de
call    _sub_415E
pop     bc
pop     bc
ld      (ix+-2),l
ld      (ix+-1),h
ex      de,hl
ld      hl,23
add     hl,de
ld      e,(iy+23)
ld      d,(iy+24)
ld      (hl),e
inc     hl
ld      (hl),d
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      hl,21
add     hl,de
ld      e,(iy+21)
ld      d,(iy+22)
ld      (hl),e
inc     hl
ld      (hl),d
push    iy
call    _sub_475C
ld      l,(ix+-2)
ld      h,(ix+-1)
ex      (sp),hl
call    _sub_385B
pop     bc
call    _allocNode
push    hl
pop     iy
ld      l,(ix+-2)
ld      h,(ix+-1)
push    iy
pop     de
push    hl
ld      bc,29
ldir
pop     hl
ld      (iy+0),69
ld      (iy+25),8
ld      (iy+26),0
ld      (iy+27),0
ld      (iy+28),0
ld      l,(ix+-2)
ld      h,(ix+-1)
push    hl
push    iy
ld      l,14
push    hl
call    _sub_43EF
pop     bc
pop     bc
pop     bc
push    hl
pop     iy
ld      hl,0
push    hl
push    iy
ld      l,13
push    hl
call    _sub_43EF
pop     bc
;pop     bc
;pop     bc
;jp      cret
jp	popBCpopBCcret
L124:
ld      hl,21
add     hl,de
ld      a,(hl)
cp      2
jp      nz,l111
ld      (iy+0),69
ld      e,(iy+25)
ld      d,(iy+26)
ld      hl,19
add     hl,de
ld      e,(hl)
inc     hl
ld      d,(hl)
ld      a,d
rla
sbc     a,a
ld      l,a
ld      h,a
ld      (iy+25),e
ld      (iy+26),d
ld      (iy+27),l
ld      (iy+28),h
l111:
;push    iy
;pop     hl
;jp      cret
jp	pushIYpopHLcret
global  _sub_4E8D
_sub_4E8D:
global csv
call csv
push hl
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
ld      de,_dopetab
ld      l,(iy+25)
ld      h,(iy+26)
ld      (ix+-2),l
ld      (ix+-1),h
ld      l,(hl)
ld      h,0
add     hl,hl
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
bit     4,b
jp      z,l113
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      hl,23
add     hl,de
ld      e,(iy+23)
ld      d,(iy+24)
ld      (hl),e
inc     hl
ld      (hl),d
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      hl,21
add     hl,de
ld      e,(iy+21)
ld      d,(iy+22)
ld      (hl),e
inc     hl
ld      (hl),d
ld      hl,0
push    hl
ld      l,(ix+-2)
ld      h,(ix+-1)
push    hl
ld      l,9
push    hl
call    _sub_43EF
pop     bc
pop     bc
pop     bc
ld      (ix+-2),l
ld      (ix+-1),h
ld      (iy+25),l
ld      (iy+26),h
jp      l114
l113:
call    _allocNode
ld      (ix+-2),l
ld      (ix+-1),h
push    iy
pop     hl
ld      e,(ix+-2)
ld      d,(ix+-1)
push    hl
ld      bc,29
ldir
pop     hl
ld      l,(ix+-2)
ld      h,(ix+-1)
ld      (hl),65
push    hl
call    _sub_385B
ld      l,(ix+-2)
ld      h,(ix+-1)
ex      (sp),hl
ld      hl,0
push    hl
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
ld      l,9
push    hl
call    _sub_43EF
pop     bc
pop     bc
pop     bc
push    hl
ld      l,20
push    hl
call    _sub_43EF
pop     bc
pop     bc
pop     bc
ld      (iy+25),l
ld      (iy+26),h
l114:
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      hl,23
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (iy+23),c
ld      (iy+24),b
ld      hl,21
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (iy+21),c
ld      (iy+22),b
ld      e,(iy+27)
ld      d,(iy+28)
ld      hl,21
add     hl,de
ld      e,c
ld      d,b
ld      (hl),e
inc     hl
ld      (hl),d
ld      e,(iy+27)
ld      d,(iy+28)
ld      hl,23
add     hl,de
ld      e,(iy+23)
ld      d,(iy+24)
ld      (hl),e
inc     hl
ld      (hl),d
ld      (iy+0),14
ld      hl,0
push    hl
push    iy
ld      l,13
push    hl
call    _sub_43EF
pop     bc
;pop     bc
;pop     bc
;jp      cret
jp	popBCpopBCcret
global  _sub_4FA8
_sub_4FA8:
global csv
call csv
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
ld      l,(iy+27)
ld      h,(iy+28)
push    hl
call    _sub_475C
pop     bc
push    iy
call    _freeNode
pop     bc
ld      l,(iy+25)
ld      h,(iy+26)
jp      cret
global  _sub_4FCE
global  asalsub
global  asalsub
global  _byte_B013
_sub_4FCE:
global csv
call csv
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
ld      a,(iy+0)
cp      6
jp      z,l126
cp      12
jp      z,l119
cp      24
jp      z,l121
cp      34
jp      z,l125
cp      36
jp      z,l120
cp      39
jp      z,l123
l117:
ld      a,1
ld      (_byte_B013),a
ld      e,(iy+27)
ld      d,(iy+28)
ld      hl,25
add     hl,de
ld      e,(hl)
inc     hl
ld      d,(hl)
inc     hl
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
push    hl
push    de
call    _sub_46F7
pop     bc
pop     bc
ld      e,l
ld      d,0
ld      hl,-1
add     hl,de
ex      de,hl
ld      hl,0
push    hl
push    de
ld      e,(iy+27)
ld      d,(iy+28)
ld      hl,25
add     hl,de
pop     de
ld      (hl),e
inc     hl
ld      (hl),d
inc     hl
pop     bc
ld      (hl),c
inc     hl
ld      (hl),b
L128:
;push    iy
;pop     hl
;jp      cret
jp	pushIYpopHLcret
l119:
ld      (iy+0),31
jp      l117
l120:
ld      (iy+0),40
jp      l117
l121:
push    iy
call    _sub_14F3
pop     bc
ld      a,l
cp      2
jp      nz,L128
ld      (iy+0),47
jp      l117
l123:
push    iy
call    _sub_14F3
pop     bc
ld      a,l
cp      2
jp      nz,L128
ld      (iy+0),42
jp      l117
l125:
ld      (iy+0),35
L129:
ld      de,1
ld      hl,0
push    hl
push    de
ld      e,(iy+27)
ld      d,(iy+28)
ld      hl,25
add     hl,de
call    asalsub
jp      L128
l126:
ld      (iy+0),7
jp      L129
global  _sub_508A
global  _sprintf
global  _strlen

IF RAM128

global  _MyAlloc
global  _PutString
ELSE

global  _allocMem
global  _strcpy

ENDIF

global  _newLocal
global  wrelop
global  _sub_6246
global  wrelop
global  wrelop
global  wrelop
_sub_508A:
call ncsv
defw -23
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
push    hl
call    _sub_14F3
pop     bc
ld      a,l
cp      3
jp      nz,l128
ld      l,(iy+25)
ld      h,(iy+26)
ld      a,(hl)
cp      67
jp      nz,l128
ex      de,hl
ld      hl,25
add     hl,de
ld      e,(hl)
inc     hl
ld      d,(hl)
inc     hl
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
ld      (ix+-23),e
ld      (ix+-22),d
ld      (ix+-21),l
ld      (ix+-20),h
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
call    _freeNode
ld      l,(iy+27)
ld      h,(iy+28)
ex      (sp),hl
call    _freeNode
ld      e,(ix+-23)
ld      d,(ix+-22)
ld      l,(ix+-21)
ld      h,(ix+-20)
ex      (sp),hl
push    de
ld      hl,29f
push    hl
push    ix
pop     de
ld      hl,-19
add     hl,de
push    hl
call    _sprintf
pop     bc
pop     bc
pop     bc
push    ix
pop     de
ld      hl,-19
add     hl,de
ex      (sp),hl
call    _strlen
pop     bc
inc     hl
push    hl

IF RAM128

call    _MyAlloc

ELSE

call    _allocMem

ENDIF

ld      (iy+25),l
ld      (iy+26),h

IF RAM128

ex      (sp),hl
push    ix
pop     de
ld      hl,-19
add     hl,de
push    hl
call    _PutString

ELSE

push    ix
pop     de
ld      hl,-19
add     hl,de
ex      (sp),hl
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
call    _strcpy

ENDIF

pop     bc
pop     bc
call    _newLocal
ld      (iy+27),l
ld      (iy+28),h
ld      (iy+0),68
L142:
;push    iy
;pop     hl
;jp      cret
jp	pushIYpopHLcret
l128:
ld      de,_dopetab
ld      l,(iy+25)
ld      h,(iy+26)
ld      (ix+-2),l
ld      (ix+-1),h
ld      l,(hl)
ld      h,0
add     hl,hl
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
bit     4,b
jp      z,l129
push    iy
call    _nodesize
ex      (sp),hl
ld      l,(ix+-2)
ld      h,(ix+-1)
push    hl
call    _nodesize
pop     bc
pop     de
call    wrelop
jp      c,l129
push    iy
call    _sub_14F3
pop     bc
ld      a,l
cp      3
ld      l,(ix+-2)
ld      h,(ix+-1)
push    hl
jp      z,L136
call    _sub_14F3
pop     bc
ld      a,l
cp      3
jp      z,l129
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      hl,23
add     hl,de
ld      e,(iy+23)
ld      d,(iy+24)
ld      (hl),e
inc     hl
ld      (hl),d
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      hl,21
add     hl,de
ld      e,(iy+21)
ld      d,(iy+22)
ld      (hl),e
inc     hl
ld      (hl),d
ld      l,(iy+27)
ld      h,(iy+28)
push    hl
call    _freeNode
pop     bc
L139:
push    iy
call    _freeNode
pop     bc
;ld      l,(ix+-2)
;ld      h,(ix+-1)
;jp      cret
jp	ldLIXm2ldHIXm1cret
l129:
ld      l,(ix+-2)
ld      h,(ix+-1)
push    hl
L136:
push    iy
call    _sub_6246
pop     bc
pop     bc
ld      a,l
or      a
jp      z,l130
ld      l,(iy+27)
ld      h,(iy+28)
push    hl
call    _sub_475C
pop     bc
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      hl,23
add     hl,de
ld      e,(iy+23)
ld      d,(iy+24)
ld      (hl),e
inc     hl
ld      (hl),d
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      hl,21
add     hl,de
ld      e,(iy+21)
ld      d,(iy+22)
ld      (hl),e
inc     hl
ld      (hl),d
jp      L139
l130:
push    iy
call    _nodesize
ex      (sp),hl
ld      l,(ix+-2)
ld      h,(ix+-1)
push    hl
call    _nodesize
pop     bc
pop     de
call    wrelop
jp      c,L142
ld      l,(ix+-2)
ld      h,(ix+-1)
ld      a,(hl)
cp      20
jp      nz,l132
push    iy
call    _nodesize
pop     bc
push    hl
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      hl,25
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
call    _nodesize
pop     bc
pop     de
call    wrelop
jp      c,l132
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      hl,25
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
push    iy
call    _sub_6246
pop     bc
pop     bc
ld      a,l
or      a
jp      nz,L134
ld      l,(ix+-2)
ld      h,(ix+-1)
push    hl
call    _sub_14F3
pop     bc
ld      e,l
push    de
push    iy
call    _sub_14F3
pop     bc
ld      a,l
pop     de
cp      e
jp      nz,l132
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      hl,25
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
call    _sub_14F3
pop     bc
ld      e,l
push    de
push    iy
call    _sub_14F3
pop     bc
ld      a,l
pop     de
cp      e
jp      nz,l132
L134:
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      hl,25
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (iy+25),c
ld      (iy+26),b
ld      hl,27
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
call    _freeNode
ld      l,(ix+-2)
ld      h,(ix+-1)
ex      (sp),hl
call    _freeNode
pop     bc
jp      L142
l132:
ld      de,_dopetab
ld      l,(ix+-2)
ld      h,(ix+-1)
ld      l,(hl)
ld      h,0
add     hl,hl
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
xor     a
ld      l,a
ld      a,b
and     12
ld      h,a
ld      a,l
or      h
jp      z,L142
ld      l,(ix+-2)
ld      h,(ix+-1)
push    hl
call    _sub_14F3
pop     bc
ld      a,l
cp      3
jp      z,L142
ld      de,_dopetab
ld      l,(ix+-2)
ld      h,(ix+-1)
ld      l,(hl)
ld      h,0
add     hl,hl
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
bit     2,b
jp      z,l135
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      hl,25
add     hl,de
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
ld      a,(hl)
cp      20
jp      nz,L142
ld      l,e
ld      h,d
push    hl
call    _nodesize
pop     bc
push    hl
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      hl,25
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      hl,25
add     hl,bc
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
call    _nodesize
pop     bc
pop     de
call    wrelop
jp      nc,L142
l135:
ld      l,(iy+27)
ld      h,(iy+28)
push    hl
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      hl,25
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
ld      l,20
push    hl
call    _sub_43EF
pop     bc
pop     bc
pop     bc
ld      (ix+-4),l
ld      (ix+-3),h
ld      l,(iy+27)
ld      h,(iy+28)
push    iy
pop     de
push    hl
ld      bc,29
ldir
pop     hl
ld      de,_dopetab
ld      l,(ix+-2)
ld      h,(ix+-1)
ld      l,(hl)
ld      h,0
add     hl,hl
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
bit     3,c
push    iy
jp      z,L137
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      hl,27
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
ld      l,20
push    hl
call    _sub_43EF
pop     bc
pop     bc
pop     bc
push    hl
pop     iy
jp      l137
L137:
call    _freeNode
pop     bc
ld      iy,0
l137:
push    iy
ld      l,(ix+-4)
ld      h,(ix+-3)
push    hl
ld      l,(ix+-2)
ld      h,(ix+-1)
ld      l,(hl)
push    hl
call    _sub_43EF
pop     bc
pop     bc
ld      (ix+-4),l
ld      (ix+-3),h
ld      l,(ix+-2)
ld      h,(ix+-1)
ex      (sp),hl
call    _freeNode
pop     bc
ld      l,(ix+-4)
ld      h,(ix+-3)
jp      cret
global  _sub_53EE
_sub_53EE:
global csv
call csv
push hl
ld      l,(ix+6)
ld      h,(ix+7)
push    hl
pop     iy
ld      e,(iy+25)
ld      d,(iy+26)
ld      (ix+-2),e
ld      (ix+-1),d
ld      hl,25
add     hl,de
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
ld      l,(hl)
ld      h,0
add     hl,hl
ld      de,_dopetab
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
bit     4,b
jp      z,l139
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      hl,25
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (ix+-2),c
ld      (ix+-1),b
ld      e,c
ld      d,b
ld      hl,23
add     hl,de
ld      e,(iy+23)
ld      d,(iy+24)
ld      (hl),e
inc     hl
ld      (hl),d
ld      e,c
ld      d,b
ld      hl,21
add     hl,de
ld      e,(iy+21)
ld      d,(iy+22)
ld      (hl),e
inc     hl
ld      (hl),d
ld      l,(iy+25)
ld      h,(iy+26)
push    hl
call    _freeNode
pop     bc
push    iy
call    _freeNode
pop     bc
;ld      l,(ix+-2)
;ld      h,(ix+-1)
;jp      cret
jp	ldLIXm2ldHIXm1cret
l139:
ld      (iy+0),20
ld      l,(ix+-2)
ld      h,(ix+-1)
ld      (iy+27),l
ld      (iy+28),h
ex      de,hl
ld      hl,25
add     hl,de
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (iy+25),c
ld      (iy+26),b
ld      l,e
ld      h,d
ld      (hl),65
ld      hl,23
add     hl,de
ld      e,(iy+23)
ld      d,(iy+24)
ld      (hl),e
inc     hl
ld      (hl),d
ld      e,(ix+-2)
ld      d,(ix+-1)
ld      hl,21
add     hl,de
ld      e,(iy+21)
ld      d,(iy+22)
ld      (hl),e
inc     hl
ld      (hl),d
ld      a,1
ld      (_byte_B013),a
;push    iy
;pop     hl
;jp      cret
jp	pushIYpopHLcret
psect   data
19:
defb    83,105,122,101,111,102,32,121,105,101,108,100,115,32,48,0
29:
defb    37,108,100,0
psect   text

