#define NUM_TREASURESCORES  19
#define NUM_ROOMSCORES      5

enum
{
  O_NOTHING,
  O_YOU,
  O_CYCLOPS,
  O_GHOSTS,
  O_BAT,
  O_THIEF,
  O_TROLL,
  O_LOWERED_BASKET,
  O_RAISED_BASKET,
  O_TROPHY_CASE,
  O_MACHINE,
  O_MAILBOX,
  O_KITCHEN_TABLE,
  O_ATTIC_TABLE,
  O_WATER,
  O_SKULL,
  O_TIMBERS,
  O_LUNCH,
  O_BELL,
  O_HOT_BELL,
  O_BOOK,
  O_AXE,
  O_BROKEN_LAMP,
  O_SCEPTRE,
  O_SANDWICH_BAG,
  O_CHALICE,
  O_GARLIC,
  O_TRIDENT,
  O_BOTTLE,
  O_COFFIN,
  O_PUMP,
  O_DIAMOND,
  O_JADE,
  O_KNIFE,
  O_BURNED_OUT_LANTERN,
  O_BAG_OF_COINS,
  O_LAMP,
  O_EMERALD,
  O_ADVERTISEMENT,
  O_INFLATED_BOAT,
  O_MATCH,
  O_PAINTING,
  O_CANDLES,
  O_GUNK,
  O_LEAVES,
  O_PUNCTURED_BOAT,
  O_INFLATABLE_BOAT,
  O_BAR,
  O_POT_OF_GOLD,
  O_BUOY,
  O_ROPE,
  O_RUSTY_KNIFE,
  O_BRACELET,
  O_TOOL_CHEST,
  O_SCREWDRIVER,
  O_KEYS,
  O_SHOVEL,
  O_COAL,
  O_SCARAB,
  O_LARGE_BAG,
  O_STILETTO,
  O_SWORD,
  O_MAP,
  O_BOAT_LABEL,
  O_TORCH,
  O_GUIDE,
  O_TRUNK,
  O_TUBE,
  O_PUTTY,
  O_OWNERS_MANUAL,
  O_WRENCH,
  O_NEST,
  O_EGG,
  O_BROKEN_EGG,
  O_BAUBLE,
  O_CANARY,
  O_BROKEN_CANARY,
  O_ENGRAVINGS,
  O_ZORKMID,
  O_GRUE
};

enum
{
  R_NULL,
  R_WEST_OF_HOUSE,
  R_STONE_BARROW,
  R_NORTH_OF_HOUSE,
  R_SOUTH_OF_HOUSE,
  R_EAST_OF_HOUSE,
  R_FOREST_1,
  R_FOREST_2,
  R_MOUNTAINS,
  R_FOREST_3,
  R_PATH,
  R_UP_A_TREE,
  R_GRATING_CLEARING,
  R_CLEARING,
  R_KITCHEN,
  R_ATTIC,
  R_LIVING_ROOM,
  R_CELLAR,
  R_TROLL_ROOM,
  R_EAST_OF_CHASM,
  R_GALLERY,
  R_STUDIO,
  R_MAZE_1,
  R_MAZE_2,
  R_MAZE_3,
  R_MAZE_4,
  R_DEAD_END_1,
  R_MAZE_5,
  R_DEAD_END_2,
  R_MAZE_6,
  R_MAZE_7,
  R_MAZE_8,
  R_DEAD_END_3,
  R_MAZE_9,
  R_MAZE_10,
  R_MAZE_11,
  R_GRATING_ROOM,
  R_MAZE_12,
  R_DEAD_END_4,
  R_MAZE_13,
  R_MAZE_14,
  R_MAZE_15,
  R_CYCLOPS_ROOM,
  R_STRANGE_PASSAGE,
  R_TREASURE_ROOM,
  R_RESERVOIR_SOUTH,
  R_RESERVOIR,
  R_RESERVOIR_NORTH,
  R_STREAM_VIEW,
  R_IN_STREAM,
  R_MIRROR_R_1,
  R_MIRROR_R_2,
  R_SMALL_CAVE,
  R_TINY_CAVE,
  R_COLD_PASSAGE,
  R_NARROW_PASSAGE,
  R_WINDING_PASSAGE,
  R_TWISTING_PASSAGE,
  R_ATLANTIS_ROOM,
  R_EW_PASSAGE,
  R_ROUND_ROOM,
  R_DEEP_CANYON,
  R_DAMP_CAVE,
  R_LOUD_ROOM,
  R_NS_PASSAGE,
  R_CHASM_ROOM,
  R_ENTRANCE_TO_HADES,
  R_LAND_OF_LIVING_DEAD,
  R_ENGRAVINGS_CAVE,
  R_EGYPT_ROOM,
  R_DOME_ROOM,
  R_TORCH_ROOM,
  R_NORTH_TEMPLE,
  R_SOUTH_TEMPLE,
  R_DAM_ROOM,
  R_DAM_LOBBY,
  R_MAINTENANCE_ROOM,
  R_DAM_BASE,
  R_RIVER_1,
  R_RIVER_2,
  R_RIVER_3,
  R_WHITE_CLIFFS_NORTH,
  R_WHITE_CLIFFS_SOUTH,
  R_RIVER_4,
  R_RIVER_5,
  R_SHORE,
  R_SANDY_BEACH,
  R_SANDY_CAVE,
  R_ARAGAIN_FALLS,
  R_ON_RAINBOW,
  R_END_OF_RAINBOW,
  R_CANYON_BOTTOM,
  R_CLIFF_MIDDLE,
  R_CANYON_VIEW,
  R_MINE_ENTRANCE,
  R_SQUEEKY_ROOM,
  R_BAT_ROOM,
  R_SHAFT_ROOM,
  R_SMELLY_ROOM,
  R_GAS_ROOM,
  R_LADDER_TOP,
  R_LADDER_BOTTOM,
  R_DEAD_END_5,
  R_TIMBER_ROOM,
  R_LOWER_SHAFT,
  R_MACHINE_ROOM,
  R_MINE_1,
  R_MINE_2,
  R_MINE_3,
  R_MINE_4,
  R_SLIDE_ROOM
};

struct TREASURESCORE_STRUCT
{
  int obj;
  char take_value;
  char case_value;
  char flags; /* &1 taken  &2 put in case */
};

struct TREASURESCORE_STRUCT TreasureScore[NUM_TREASURESCORES] =
{
/*                   take case*/
/*  obj              valu valu flags*/

  { O_EGG          ,  5 ,  5 , 0 },
  { O_CANARY       ,  6 ,  4 , 0 },
  { O_PAINTING     ,  4 ,  6 , 0 },
  { O_BAR          , 10 ,  5 , 0 },
  { O_TORCH        , 14 ,  6 , 0 },
  { O_COFFIN       , 10 , 15 , 0 },
  { O_SCEPTRE      ,  4 ,  6 , 0 },
  { O_TRUNK        , 15 ,  5 , 0 },
  { O_TRIDENT      ,  4 , 11 , 0 },
  { O_JADE         ,  5 ,  5 , 0 },
  { O_BRACELET     ,  5 ,  5 , 0 },
  { O_DIAMOND      , 10 , 10 , 0 },
  { O_BAG_OF_COINS , 10 ,  5 , 0 },
  { O_SKULL        , 10 , 10 , 0 },
  { O_SCARAB       ,  5 ,  5 , 0 },
  { O_EMERALD      ,  5 , 10 , 0 },
  { O_CHALICE      , 10 ,  5 , 0 },
  { O_POT_OF_GOLD  , 10 , 10 , 0 },
  { O_BAUBLE       ,  1 ,  1 , 0 }
};

struct ROOMSCORE_STRUCT
{
  int room;
  char value;
  char flag;
};

struct ROOMSCORE_STRUCT RoomScore[NUM_ROOMSCORES] =
{
/*  obj                 valu flag*/

  { R_KITCHEN       , 10 , 0 },
  { R_CELLAR        , 25 , 0 },
  { R_EW_PASSAGE    ,  5 , 0 },
  { R_LOWER_SHAFT   , 13 , 0 },
  { R_TREASURE_ROOM , 25 , 0 }
};
