enum
{
  O_NOTHING,
  O_YOU,
  O_CYCLOPS,
  O_GHOSTS,
  O_BAT,
  O_THIEF,
  O_TROLL,
  O_LOWERED_BASKET,
  O_RAISED_BASKET,
  O_TROPHY_CASE,
  O_MACHINE,
  O_MAILBOX,
  O_KITCHEN_TABLE,
  O_ATTIC_TABLE,
  O_WATER,
  O_SKULL,
  O_TIMBERS,
  O_LUNCH,
  O_BELL,
  O_HOT_BELL,
  O_BOOK,
  O_AXE,
  O_BROKEN_LAMP,
  O_SCEPTRE,
  O_SANDWICH_BAG,
  O_CHALICE,
  O_GARLIC,
  O_TRIDENT,
  O_BOTTLE,
  O_COFFIN,
  O_PUMP,
  O_DIAMOND,
  O_JADE,
  O_KNIFE,
  O_BURNED_OUT_LANTERN,
  O_BAG_OF_COINS,
  O_LAMP,
  O_EMERALD,
  O_ADVERTISEMENT,
  O_INFLATED_BOAT,
  O_MATCH,
  O_PAINTING,
  O_CANDLES,
  O_GUNK,
  O_LEAVES,
  O_PUNCTURED_BOAT,
  O_INFLATABLE_BOAT,
  O_BAR,
  O_POT_OF_GOLD,
  O_BUOY,
  O_ROPE,
  O_RUSTY_KNIFE,
  O_BRACELET,
  O_TOOL_CHEST,
  O_SCREWDRIVER,
  O_KEYS,
  O_SHOVEL,
  O_COAL,
  O_SCARAB,
  O_LARGE_BAG,
  O_STILETTO,
  O_SWORD,
  O_MAP,
  O_BOAT_LABEL,
  O_TORCH,
  O_GUIDE,
  O_TRUNK,
  O_TUBE,
  O_PUTTY,
  O_OWNERS_MANUAL,
  O_WRENCH,
  O_NEST,
  O_EGG,
  O_BROKEN_EGG,
  O_BAUBLE,
  O_CANARY,
  O_BROKEN_CANARY,
  O_ENGRAVINGS,
  O_ZORKMID,
  O_GRUE
};


/*phrase must contain a maximum of three words*/

/*for matching to work, phrases must be listed in order of decreasing word size*/

/*different objects can have the same phrase, but there must*/
/*be larger phrases for them, so player can be more specific when needed*/

/*words must be separated by exactly one space*/

/*NOTE: if there is a phrase like "disk drive" and then phrases "disk" and drive",*/
/*which represent two different objects, parser will ask player to be more specific,*/
/*so it is best to avoid "disk drive" and use something like "storage drive"*/


/* objects that have same phrase as fixed objects:*/
/*   water*/

/* objects that have same phrase but won't prompt player to be specific*/
/* because they won't exist in same room at same time:*/
/*   basket                                                (raised and lowered)*/
/*   brass bell  bell                                      (cool and hot)*/
/*   lantern  lamp                                         (unbroken and broken)*/
/*   boat                                                  (uninflated, inflated, punctured)*/
/*   large egg  jewel-encrusted egg  egg                   (unbroken and broken)*/
/*   golden canary  gold canary  clockwork canary  canary  (unbroken and broken)*/
/*   table                                                 (kitchen and attic)*/

/* objects that have same phrase and will prompt player to be specific*/
/* if they are in same room at same time:*/
/*   lantern  lamp                                         (unbroken/broken and burned-out)*/
/*   bag                                                   (sandwich bag, bag of coins, large bag)*/
/*   knife                                                 (nasty and rusty)*/
/*   pile                                                  (leaves, uninflated boat, coal)*/
/*   book                                                  (black and guide)*/

struct NOUNPHRASETOO_STRUCT
{
  char *phrase;
  short obj;
};


struct NOUNPHRASETOO_STRUCT NounPhraseToObj[] =
{
  { "me"                          , O_YOU                },
  { "myself"                      , O_YOU                },
  { "i"                           , O_YOU                },
  { "self"                        , O_YOU                },
  { "bare hands"                  , O_YOU                },
  { "my hands"                    , O_YOU                },
  { "my hand"                     , O_YOU                },
  { "hands"                       , O_YOU                },
  { "hand"                        , O_YOU                },
  { "my teeth"                    , O_YOU                },
  { "teeth"                       , O_YOU                },
  { "cyclops"                     , O_CYCLOPS            },
  { "evil spirits"                , O_GHOSTS             },
  { "spirits"                     , O_GHOSTS             },
  { "spirit"                      , O_GHOSTS             },
  { "ghosts"                      , O_GHOSTS             },
  { "ghost"                       , O_GHOSTS             },
  { "vampire bat"                 , O_BAT                },
  { "bat"                         , O_BAT                },
  { "individual"                  , O_THIEF              },
  { "man"                         , O_THIEF              },
  { "person"                      , O_THIEF              },
  { "thief"                       , O_THIEF              },
  { "robber"                      , O_THIEF              },
  { "nasty troll"                 , O_TROLL              },
  { "troll"                       , O_TROLL              },
  { "basket"                      , O_LOWERED_BASKET     },
  { "basket"                      , O_RAISED_BASKET      },
  { "trophy case"                 , O_TROPHY_CASE        },
  { "case"                        , O_TROPHY_CASE        },
  { "machine"                     , O_MACHINE            },
  { "lid"                         , O_MACHINE            },
  { "small mailbox"               , O_MAILBOX            },
  { "mailbox"                     , O_MAILBOX            },
  { "box"                         , O_MAILBOX            },
  { "quantity of water"           , O_WATER              },
  { "water"                       , O_WATER              },
  { "crystal skull"               , O_SKULL              },
  { "skull"                       , O_SKULL              },
  { "broken timber"               , O_TIMBERS            },
  { "timber"                      , O_TIMBERS            },
  { "hot pepper sandwich"         , O_LUNCH              },
  { "pepper sandwich"             , O_LUNCH              },
  { "sandwich"                    , O_LUNCH              },
  { "lunch"                       , O_LUNCH              },
  { "brass bell"                  , O_BELL               },
  { "bell"                        , O_BELL               },
  { "red hot bell"                , O_HOT_BELL           },
  { "hot brass bell"              , O_HOT_BELL           },
  { "hot bell"                    , O_HOT_BELL           },
  { "brass bell"                  , O_HOT_BELL           },
  { "bell"                        , O_HOT_BELL           },
  { "large book"                  , O_BOOK               },
  { "black book"                  , O_BOOK               },
  { "book"                        , O_BOOK               },
  { "page"                        , O_BOOK               },
  { "bloody axe"                  , O_AXE                },
  { "bloody ax"                   , O_AXE                },
  { "axe"                         , O_AXE                },
  { "ax"                          , O_AXE                },
  { "broken lantern"              , O_BROKEN_LAMP        },
  { "broken lamp"                 , O_BROKEN_LAMP        },
  { "lantern"                     , O_BROKEN_LAMP        },
  { "lamp"                        , O_BROKEN_LAMP        },
  { "ornamented sceptre"          , O_SCEPTRE            },
  { "ornamented scepter"          , O_SCEPTRE            },
  { "sceptre"                     , O_SCEPTRE            },
  { "scepter"                     , O_SCEPTRE            },
  { "elongated sack"              , O_SANDWICH_BAG       },
  { "brown sack"                  , O_SANDWICH_BAG       },
  { "elongated bag"               , O_SANDWICH_BAG       },
  { "brown bag"                   , O_SANDWICH_BAG       },
  { "sack"                        , O_SANDWICH_BAG       },
  { "bag"                         , O_SANDWICH_BAG       },
  { "engraved chalice"            , O_CHALICE            },
  { "silver chalice"              , O_CHALICE            },
  { "chalice"                     , O_CHALICE            },
  { "clove of garlic"             , O_GARLIC             },
  { "clove"                       , O_GARLIC             },
  { "garlic"                      , O_GARLIC             },
  { "crystal trident"             , O_TRIDENT            },
  { "trident"                     , O_TRIDENT            },
  { "glass bottle"                , O_BOTTLE             },
  { "bottle"                      , O_BOTTLE             },
  { "solid-gold coffin"           , O_COFFIN             },
  { "gold coffin"                 , O_COFFIN             },
  { "coffin"                      , O_COFFIN             },
  { "hand-held pump"              , O_PUMP               },
  { "air pump"                    , O_PUMP               },
  { "pump"                        , O_PUMP               },
  { "huge diamond"                , O_DIAMOND            },
  { "enormous diamond"            , O_DIAMOND            },
  { "diamond"                     , O_DIAMOND            },
  { "exquisite figurine"          , O_JADE               },
  { "jade figurine"               , O_JADE               },
  { "figurine"                    , O_JADE               },
  { "nasty-looking knife"         , O_KNIFE              },
  { "nasty knife"                 , O_KNIFE              },
  { "knife"                       , O_KNIFE              },
  { "burned-out lantern"          , O_BURNED_OUT_LANTERN },
  { "burned-out lamp"             , O_BURNED_OUT_LANTERN },
  { "useless lantern"             , O_BURNED_OUT_LANTERN },
  { "useless lamp"                , O_BURNED_OUT_LANTERN },
  { "lantern"                     , O_BURNED_OUT_LANTERN },
  { "lamp"                        , O_BURNED_OUT_LANTERN },
  { "bag of coins"                , O_BAG_OF_COINS       },
  { "leather bag"                 , O_BAG_OF_COINS       },
  { "bag"                         , O_BAG_OF_COINS       },
  { "coins"                       , O_BAG_OF_COINS       },
  { "brass lantern"               , O_LAMP               },
  { "brass lamp"                  , O_LAMP               },
  { "lantern"                     , O_LAMP               },
  { "lamp"                        , O_LAMP               },
  { "light"                       , O_LAMP               },
  { "large emerald"               , O_EMERALD            },
  { "emerald"                     , O_EMERALD            },
  { "small leaflet"               , O_ADVERTISEMENT      },
  { "leaflet"                     , O_ADVERTISEMENT      },
  { "mail"                        , O_ADVERTISEMENT      },
  { "magic boat"                  , O_INFLATED_BOAT      },
  { "inflated boat"               , O_INFLATED_BOAT      },
  { "boat"                        , O_INFLATED_BOAT      },
  { "match"                       , O_MATCH              },
  { "matches"                     , O_MATCH              },
  { "matchbook"                   , O_MATCH              },
  { "beautiful painting"          , O_PAINTING           },
  { "painting"                    , O_PAINTING           },
  { "pair of candles"             , O_CANDLES            },
  { "candles"                     , O_CANDLES            },
  { "piece of slag"               , O_GUNK               },
  { "vitreous slag"               , O_GUNK               },
  { "slag"                        , O_GUNK               },
  { "pile of leaves"              , O_LEAVES             },
  { "leaves"                      , O_LEAVES             },
  { "pile"                        , O_LEAVES             },
  { "punctured boat"              , O_PUNCTURED_BOAT     },
  { "boat"                        , O_PUNCTURED_BOAT     },
  { "pile of plastic"             , O_INFLATABLE_BOAT    },
  { "inflatable boat"             , O_INFLATABLE_BOAT    },
  { "plastic"                     , O_INFLATABLE_BOAT    },
  { "pile"                        , O_INFLATABLE_BOAT    },
  { "boat"                        , O_INFLATABLE_BOAT    },
  { "valve"                       , O_INFLATABLE_BOAT    },
  { "bar of platinum"             , O_BAR                },
  { "large bar"                   , O_BAR                },
  { "platinum bar"                , O_BAR                },
  { "bar"                         , O_BAR                },
  { "pot of gold"                 , O_POT_OF_GOLD        },
  { "pot"                         , O_POT_OF_GOLD        },
  { "gold"                        , O_POT_OF_GOLD        },
  { "red buoy"                    , O_BUOY               },
  { "buoy"                        , O_BUOY               },
  { "coil of rope"                , O_ROPE               },
  { "coil"                        , O_ROPE               },
  { "rope"                        , O_ROPE               },
  { "rusty knife"                 , O_RUSTY_KNIFE        },
  { "knife"                       , O_RUSTY_KNIFE        },
  { "sapphire-encrusted bracelet" , O_BRACELET           },
  { "sapphire bracelet"           , O_BRACELET           },
  { "bracelet"                    , O_BRACELET           },
  { "tool chests"                 , O_TOOL_CHEST         },
  { "tool chest"                  , O_TOOL_CHEST         },
  { "chests"                      , O_TOOL_CHEST         },
  { "chest"                       , O_TOOL_CHEST         },
  { "screwdriver"                 , O_SCREWDRIVER        },
  { "skeleton key"                , O_KEYS               },
  { "key"                         , O_KEYS               },
  { "shovel"                      , O_SHOVEL             },
  { "pile of coal"                , O_COAL               },
  { "small pile"                  , O_COAL               },
  { "pile"                        , O_COAL               },
  { "coal"                        , O_COAL               },
  { "beautiful scarab"            , O_SCARAB             },
  { "jeweled scarab"              , O_SCARAB             },
  { "scarab"                      , O_SCARAB             },
  { "large bag"                   , O_LARGE_BAG          },
  { "thief's bag"                 , O_LARGE_BAG          },
  { "bag"                         , O_LARGE_BAG          },
  { "vicious stiletto"            , O_STILETTO           },
  { "stiletto"                    , O_STILETTO           },
  { "elvish sword"                , O_SWORD              },
  { "antique sword"               , O_SWORD              },
  { "sword"                       , O_SWORD              },
  { "ancient map"                 , O_MAP                },
  { "ancient parchment"           , O_MAP                },
  { "parchment map"               , O_MAP                },
  { "map"                         , O_MAP                },
  { "parchment"                   , O_MAP                },
  { "tan label"                   , O_BOAT_LABEL         },
  { "label"                       , O_BOAT_LABEL         },
  { "ivory torch"                 , O_TORCH              },
  { "torch"                       , O_TORCH              },
  { "tour guidebook"              , O_GUIDE              },
  { "tour guide"                  , O_GUIDE              },
  { "guide book"                  , O_GUIDE              },
  { "guidebook"                   , O_GUIDE              },
  { "guide"                       , O_GUIDE              },
  { "book"                        , O_GUIDE              },
  { "trunk of jewels"             , O_TRUNK              },
  { "old trunk"                   , O_TRUNK              },
  { "trunk"                       , O_TRUNK              },
  { "jewels"                      , O_TRUNK              },
  { "tube of toothpaste"          , O_TUBE               },
  { "toothpaste tube"             , O_TUBE               },
  { "toothpaste"                  , O_TUBE               },
  { "tube"                        , O_TUBE               },
  { "viscous material"            , O_PUTTY              },
  { "material"                    , O_PUTTY              },
  { "gunk"                        , O_PUTTY              },
  { "glue"                        , O_PUTTY              },
  { "piece of paper"              , O_OWNERS_MANUAL      },
  { "zork manual"                 , O_OWNERS_MANUAL      },
  { "owner's manual"              , O_OWNERS_MANUAL      },
  { "manual"                      , O_OWNERS_MANUAL      },
  { "paper"                       , O_OWNERS_MANUAL      },
  { "wrench"                      , O_WRENCH             },
  { "small nest"                  , O_NEST               },
  { "bird's nest"                 , O_NEST               },
  { "bird nest"                   , O_NEST               },
  { "nest"                        , O_NEST               },
  { "large egg"                   , O_EGG                },
  { "jewel-encrusted egg"         , O_EGG                },
  { "egg"                         , O_EGG                },
  { "broken egg"                  , O_BROKEN_EGG         },
  { "ruined egg"                  , O_BROKEN_EGG         },
  { "large egg"                   , O_BROKEN_EGG         },
  { "jewel-encrusted egg"         , O_BROKEN_EGG         },
  { "egg"                         , O_BROKEN_EGG         },
  { "beautiful bauble"            , O_BAUBLE             },
  { "brass bauble"                , O_BAUBLE             },
  { "bauble"                      , O_BAUBLE             },
  { "golden canary"               , O_CANARY             },
  { "gold canary"                 , O_CANARY             },
  { "clockwork canary"            , O_CANARY             },
  { "canary"                      , O_CANARY             },
  { "broken canary"               , O_BROKEN_CANARY      },
  { "golden canary"               , O_BROKEN_CANARY      },
  { "gold canary"                 , O_BROKEN_CANARY      },
  { "clockwork canary"            , O_BROKEN_CANARY      },
  { "canary"                      , O_BROKEN_CANARY      },
  { "old engravings"              , O_ENGRAVINGS         },
  { "old engraving"               , O_ENGRAVINGS         },
  { "engravings"                  , O_ENGRAVINGS         },
  { "engraving"                   , O_ENGRAVINGS         },
  { "lurking grues"               , O_GRUE               },
  { "lurking grue"                , O_GRUE               },
  { "grues"                       , O_GRUE               },
  { "grue"                        , O_GRUE               },
  { "zorkmids"                    , O_ZORKMID            },
  { "zorkmid"                     , O_ZORKMID            },
  { "kitchen table"               , O_KITCHEN_TABLE      },
  { "table"                       , O_KITCHEN_TABLE      },
  { "table"                       , O_ATTIC_TABLE        },

  { 0 , 0 }
};

