enum
{
  R_NULL,
  R_WEST_OF_HOUSE,
  R_STONE_BARROW,
  R_NORTH_OF_HOUSE,
  R_SOUTH_OF_HOUSE,
  R_EAST_OF_HOUSE,
  R_FOREST_1,
  R_FOREST_2,
  R_MOUNTAINS,
  R_FOREST_3,
  R_PATH,
  R_UP_A_TREE,
  R_GRATING_CLEARING,
  R_CLEARING,
  R_KITCHEN,
  R_ATTIC,
  R_LIVING_ROOM,
  R_CELLAR,
  R_TROLL_ROOM,
  R_EAST_OF_CHASM,
  R_GALLERY,
  R_STUDIO,
  R_MAZE_1,
  R_MAZE_2,
  R_MAZE_3,
  R_MAZE_4,
  R_DEAD_END_1,
  R_MAZE_5,
  R_DEAD_END_2,
  R_MAZE_6,
  R_MAZE_7,
  R_MAZE_8,
  R_DEAD_END_3,
  R_MAZE_9,
  R_MAZE_10,
  R_MAZE_11,
  R_GRATING_ROOM,
  R_MAZE_12,
  R_DEAD_END_4,
  R_MAZE_13,
  R_MAZE_14,
  R_MAZE_15,
  R_CYCLOPS_ROOM,
  R_STRANGE_PASSAGE,
  R_TREASURE_ROOM,
  R_RESERVOIR_SOUTH,
  R_RESERVOIR,
  R_RESERVOIR_NORTH,
  R_STREAM_VIEW,
  R_IN_STREAM,
  R_MIRROR_R_1,
  R_MIRROR_R_2,
  R_SMALL_CAVE,
  R_TINY_CAVE,
  R_COLD_PASSAGE,
  R_NARROW_PASSAGE,
  R_WINDING_PASSAGE,
  R_TWISTING_PASSAGE,
  R_ATLANTIS_ROOM,
  R_EW_PASSAGE,
  R_ROUND_ROOM,
  R_DEEP_CANYON,
  R_DAMP_CAVE,
  R_LOUD_ROOM,
  R_NS_PASSAGE,
  R_CHASM_ROOM,
  R_ENTRANCE_TO_HADES,
  R_LAND_OF_LIVING_DEAD,
  R_ENGRAVINGS_CAVE,
  R_EGYPT_ROOM,
  R_DOME_ROOM,
  R_TORCH_ROOM,
  R_NORTH_TEMPLE,
  R_SOUTH_TEMPLE,
  R_DAM_ROOM,
  R_DAM_LOBBY,
  R_MAINTENANCE_ROOM,
  R_DAM_BASE,
  R_RIVER_1,
  R_RIVER_2,
  R_RIVER_3,
  R_WHITE_CLIFFS_NORTH,
  R_WHITE_CLIFFS_SOUTH,
  R_RIVER_4,
  R_RIVER_5,
  R_SHORE,
  R_SANDY_BEACH,
  R_SANDY_CAVE,
  R_ARAGAIN_FALLS,
  R_ON_RAINBOW,
  R_END_OF_RAINBOW,
  R_CANYON_BOTTOM,
  R_CLIFF_MIDDLE,
  R_CANYON_VIEW,
  R_MINE_ENTRANCE,
  R_SQUEEKY_ROOM,
  R_BAT_ROOM,
  R_SHAFT_ROOM,
  R_SMELLY_ROOM,
  R_GAS_ROOM,
  R_LADDER_TOP,
  R_LADDER_BOTTOM,
  R_DEAD_END_5,
  R_TIMBER_ROOM,
  R_LOWER_SHAFT,
  R_MACHINE_ROOM,
  R_MINE_1,
  R_MINE_2,
  R_MINE_3,
  R_MINE_4,
  R_SLIDE_ROOM
};

/*fixed (unmoving) objects*/

enum
{
  F_SCENERY_VIS = 2048, /*some anonymous scenery object, visible*/
  F_SCENERY_NOTVIS,     /*                               not visible*/

  F_NOTVIS,             /*fixed object not visible*/

  F_AMB,                /*amibiguous (ask for clarification)*/

  /*game-specific data follows*/

  F_SLIDE,
  F_BOARD,
  F_SONGBIRD,
  F_WHITE_HOUSE,
  F_FOREST,
  F_TREE,
  F_KITCHEN_WINDOW,
  F_CHIMNEY,
  F_BOARDED_WINDOW,
  F_CRACK,
  F_GRATE,
  F_CLIMBABLE_CLIFF,
  F_WHITE_CLIFF,
  F_BODIES,
  F_RAINBOW,
  F_RIVER,
  F_LADDER,
  F_TRAP_DOOR,
  F_STAIRS,
  F_MOUNTAIN_RANGE,
  F_BOLT,
  F_BUBBLE,
  F_ALTAR,
  F_YELLOW_BUTTON,
  F_BROWN_BUTTON,
  F_RED_BUTTON,
  F_BLUE_BUTTON,
  F_RUG,
  F_DAM,
  F_FRONT_DOOR,
  F_BARROW_DOOR,
  F_BARROW,
  F_BONES,
  F_LEAK,
  F_MIRROR2,
  F_MIRROR1,
  F_PRAYER,
  F_RAILING,
  F_SAND,
  F_MACHINE_SWITCH,
  F_WOODEN_DOOR,
  F_PEDESTAL,
  F_CONTROL_PANEL,
  F_NAILS,
  F_GRANITE_WALL,
  F_CHAIN,
  F_GATE,
  F_STUDIO_DOOR,
  F_CHASM,
  F_LAKE,
  F_STREAM,
  F_GAS
};


/* single words that refer to multiple objects:*/
/*   window  cliff  door  table  button*/

/* two-word noun phrases must come before one-word, for matching to work properly*/

struct NOUNPHRASETOFIXEDO_STRUCT
{
  char *phrase;
  short room;
  short fobj;
};


struct NOUNPHRASETOFIXEDO_STRUCT NounPhraseToFixedObj[] =
{
  { "steep slide"          , R_CELLAR              , F_SLIDE           },
  { "steep slide"          , R_SLIDE_ROOM          , F_SLIDE           },
  { "metal slide"          , R_CELLAR              , F_SLIDE           },
  { "metal slide"          , R_SLIDE_ROOM          , F_SLIDE           },
  { "steep ramp"           , R_CELLAR              , F_SLIDE           },
  { "steep ramp"           , R_SLIDE_ROOM          , F_SLIDE           },
  { "metal ramp"           , R_CELLAR              , F_SLIDE           },
  { "metal ramp"           , R_SLIDE_ROOM          , F_SLIDE           },
  { "slide"                , R_CELLAR              , F_SLIDE           },
  { "slide"                , R_SLIDE_ROOM          , F_SLIDE           },
  { "ramp"                 , R_CELLAR              , F_SLIDE           },
  { "ramp"                 , R_SLIDE_ROOM          , F_SLIDE           },
  { "boards"               , R_WEST_OF_HOUSE       , F_BOARD           },
  { "boards"               , R_NORTH_OF_HOUSE      , F_BOARD           },
  { "boards"               , R_SOUTH_OF_HOUSE      , F_BOARD           },
  { "board"                , R_WEST_OF_HOUSE       , F_BOARD           },
  { "board"                , R_NORTH_OF_HOUSE      , F_BOARD           },
  { "board"                , R_SOUTH_OF_HOUSE      , F_BOARD           },
  { "song bird"            , R_FOREST_1            , F_SONGBIRD        },
  { "song bird"            , R_FOREST_2            , F_SONGBIRD        },
  { "song bird"            , R_FOREST_3            , F_SONGBIRD        },
  { "song bird"            , R_PATH                , F_SONGBIRD        },
  { "song bird"            , R_UP_A_TREE           , F_SONGBIRD        },
  { "song bird"            , R_CLEARING            , F_SONGBIRD        },
  { "songbird"             , R_FOREST_1            , F_SONGBIRD        },
  { "songbird"             , R_FOREST_2            , F_SONGBIRD        },
  { "songbird"             , R_FOREST_3            , F_SONGBIRD        },
  { "songbird"             , R_PATH                , F_SONGBIRD        },
  { "songbird"             , R_UP_A_TREE           , F_SONGBIRD        },
  { "songbird"             , R_CLEARING            , F_SONGBIRD        },
  { "bird"                 , R_FOREST_1            , F_SONGBIRD        },
  { "bird"                 , R_FOREST_2            , F_SONGBIRD        },
  { "bird"                 , R_FOREST_3            , F_SONGBIRD        },
  { "bird"                 , R_PATH                , F_SONGBIRD        },
  { "bird"                 , R_UP_A_TREE           , F_SONGBIRD        },
  { "bird"                 , R_CLEARING            , F_SONGBIRD        },
  { "white house"          , R_WEST_OF_HOUSE       , F_WHITE_HOUSE     },
  { "white house"          , R_NORTH_OF_HOUSE      , F_WHITE_HOUSE     },
  { "white house"          , R_SOUTH_OF_HOUSE      , F_WHITE_HOUSE     },
  { "white house"          , R_EAST_OF_HOUSE       , F_WHITE_HOUSE     },
  { "white house"          , R_FOREST_1            , F_WHITE_HOUSE     },
  { "white house"          , R_FOREST_2            , F_WHITE_HOUSE     },
  { "white house"          , R_MOUNTAINS           , F_WHITE_HOUSE     },
  { "white house"          , R_FOREST_3            , F_WHITE_HOUSE     },
  { "white house"          , R_PATH                , F_WHITE_HOUSE     },
  { "white house"          , R_UP_A_TREE           , F_WHITE_HOUSE     },
  { "white house"          , R_GRATING_CLEARING    , F_WHITE_HOUSE     },
  { "white house"          , R_CLEARING            , F_WHITE_HOUSE     },
  { "house"                , R_WEST_OF_HOUSE       , F_WHITE_HOUSE     },
  { "house"                , R_NORTH_OF_HOUSE      , F_WHITE_HOUSE     },
  { "house"                , R_SOUTH_OF_HOUSE      , F_WHITE_HOUSE     },
  { "house"                , R_EAST_OF_HOUSE       , F_WHITE_HOUSE     },
  { "house"                , R_FOREST_1            , F_WHITE_HOUSE     },
  { "house"                , R_FOREST_2            , F_WHITE_HOUSE     },
  { "house"                , R_MOUNTAINS           , F_WHITE_HOUSE     },
  { "house"                , R_FOREST_3            , F_WHITE_HOUSE     },
  { "house"                , R_PATH                , F_WHITE_HOUSE     },
  { "house"                , R_UP_A_TREE           , F_WHITE_HOUSE     },
  { "house"                , R_GRATING_CLEARING    , F_WHITE_HOUSE     },
  { "house"                , R_CLEARING            , F_WHITE_HOUSE     },
  { "forest"               , R_WEST_OF_HOUSE       , F_FOREST          },
  { "forest"               , R_NORTH_OF_HOUSE      , F_FOREST          },
  { "forest"               , R_SOUTH_OF_HOUSE      , F_FOREST          },
  { "forest"               , R_EAST_OF_HOUSE       , F_FOREST          },
  { "forest"               , R_FOREST_1            , F_FOREST          },
  { "forest"               , R_FOREST_2            , F_FOREST          },
  { "forest"               , R_FOREST_3            , F_FOREST          },
  { "forest"               , R_PATH                , F_FOREST          },
  { "forest"               , R_UP_A_TREE           , F_FOREST          },
  { "forest"               , R_CLEARING            , F_FOREST          },
  { "trees"                , R_WEST_OF_HOUSE       , F_FOREST          },
  { "trees"                , R_NORTH_OF_HOUSE      , F_FOREST          },
  { "trees"                , R_SOUTH_OF_HOUSE      , F_FOREST          },
  { "trees"                , R_EAST_OF_HOUSE       , F_FOREST          },
  { "trees"                , R_FOREST_1            , F_FOREST          },
  { "trees"                , R_FOREST_2            , F_FOREST          },
  { "trees"                , R_FOREST_3            , F_FOREST          },
  { "trees"                , R_PATH                , F_FOREST          },
  { "trees"                , R_UP_A_TREE           , F_FOREST          },
  { "trees"                , R_CLEARING            , F_FOREST          },
  { "large tree"           , R_FOREST_1            , F_TREE            },
  { "large tree"           , R_FOREST_2            , F_TREE            },
  { "large tree"           , R_MOUNTAINS           , F_TREE            },
  { "large tree"           , R_FOREST_3            , F_TREE            },
  { "large tree"           , R_PATH                , F_TREE            },
  { "large tree"           , R_UP_A_TREE           , F_TREE            },
  { "large tree"           , R_CLEARING            , F_TREE            },
  { "tree"                 , R_FOREST_1            , F_TREE            },
  { "tree"                 , R_FOREST_2            , F_TREE            },
  { "tree"                 , R_MOUNTAINS           , F_TREE            },
  { "tree"                 , R_FOREST_3            , F_TREE            },
  { "tree"                 , R_PATH                , F_TREE            },
  { "tree"                 , R_UP_A_TREE           , F_TREE            },
  { "tree"                 , R_CLEARING            , F_TREE            },
  { "small window"         , R_EAST_OF_HOUSE       , F_KITCHEN_WINDOW  },
  { "small window"         , R_KITCHEN             , F_KITCHEN_WINDOW  },
  { "kitchen window"       , R_EAST_OF_HOUSE       , F_KITCHEN_WINDOW  },
  { "kitchen window"       , R_KITCHEN             , F_KITCHEN_WINDOW  },
  { "window"               , R_EAST_OF_HOUSE       , F_KITCHEN_WINDOW  },
  { "window"               , R_KITCHEN             , F_KITCHEN_WINDOW  },
  { "dark chimney"         , R_KITCHEN             , F_CHIMNEY         },
  { "dark chimney"         , R_STUDIO              , F_CHIMNEY         },
  { "narrow chimney"       , R_KITCHEN             , F_CHIMNEY         },
  { "narrow chimney"       , R_STUDIO              , F_CHIMNEY         },
  { "chimney"              , R_KITCHEN             , F_CHIMNEY         },
  { "chimney"              , R_STUDIO              , F_CHIMNEY         },
  { "boarded window"       , R_NORTH_OF_HOUSE      , F_BOARDED_WINDOW  },
  { "boarded window"       , R_SOUTH_OF_HOUSE      , F_BOARDED_WINDOW  },
  { "window"               , R_NORTH_OF_HOUSE      , F_BOARDED_WINDOW  },
  { "window"               , R_SOUTH_OF_HOUSE      , F_BOARDED_WINDOW  },
  { "narrow crack"         , R_DAMP_CAVE           , F_CRACK           },
  { "narrow crack"         , R_CHASM_ROOM          , F_CRACK           },
  { "crack"                , R_DAMP_CAVE           , F_CRACK           },
  { "crack"                , R_CHASM_ROOM          , F_CRACK           },
  { "grate"                , R_GRATING_CLEARING    , F_GRATE           },
  { "grate"                , R_GRATING_ROOM        , F_GRATE           },
  { "grating"              , R_GRATING_CLEARING    , F_GRATE           },
  { "grating"              , R_GRATING_ROOM        , F_GRATE           },
  { "rocky ledge"          , R_CANYON_BOTTOM       , F_CLIMBABLE_CLIFF },
  { "rocky ledge"          , R_CLIFF_MIDDLE        , F_CLIMBABLE_CLIFF },
  { "rocky ledge"          , R_CANYON_VIEW         , F_CLIMBABLE_CLIFF },
  { "rocky cliff"          , R_CANYON_BOTTOM       , F_CLIMBABLE_CLIFF },
  { "rocky cliff"          , R_CLIFF_MIDDLE        , F_CLIMBABLE_CLIFF },
  { "rocky cliff"          , R_CANYON_VIEW         , F_CLIMBABLE_CLIFF },
  { "ledge"                , R_CANYON_BOTTOM       , F_CLIMBABLE_CLIFF },
  { "ledge"                , R_CLIFF_MIDDLE        , F_CLIMBABLE_CLIFF },
  { "ledge"                , R_CANYON_VIEW         , F_CLIMBABLE_CLIFF },
  { "cliff"                , R_CANYON_BOTTOM       , F_CLIMBABLE_CLIFF },
  { "cliff"                , R_CLIFF_MIDDLE        , F_CLIMBABLE_CLIFF },
  { "cliff"                , R_CANYON_VIEW         , F_CLIMBABLE_CLIFF },
  { "white cliff"          , R_WHITE_CLIFFS_NORTH  , F_WHITE_CLIFF     },
  { "white cliff"          , R_WHITE_CLIFFS_SOUTH  , F_WHITE_CLIFF     },
  { "white cliffs"         , R_WHITE_CLIFFS_NORTH  , F_WHITE_CLIFF     },
  { "white cliffs"         , R_WHITE_CLIFFS_SOUTH  , F_WHITE_CLIFF     },
  { "cliff"                , R_WHITE_CLIFFS_NORTH  , F_WHITE_CLIFF     },
  { "cliff"                , R_WHITE_CLIFFS_SOUTH  , F_WHITE_CLIFF     },
  { "cliffs"               , R_WHITE_CLIFFS_NORTH  , F_WHITE_CLIFF     },
  { "cliffs"               , R_WHITE_CLIFFS_SOUTH  , F_WHITE_CLIFF     },
  { "mangled bodies"       , R_ENTRANCE_TO_HADES   , F_BODIES          },
  { "mangled bodies"       , R_LAND_OF_LIVING_DEAD , F_BODIES          },
  { "bodies"               , R_ENTRANCE_TO_HADES   , F_BODIES          },
  { "bodies"               , R_LAND_OF_LIVING_DEAD , F_BODIES          },
  { "rainbow"              , R_ARAGAIN_FALLS       , F_RAINBOW         },
  { "rainbow"              , R_ON_RAINBOW          , F_RAINBOW         },
  { "rainbow"              , R_END_OF_RAINBOW      , F_RAINBOW         },
  { "rainbow"              , R_CANYON_VIEW         , F_RAINBOW         },
  { "frigid river"         , R_DAM_BASE            , F_RIVER           },
  { "frigid river"         , R_RIVER_1             , F_RIVER           },
  { "frigid river"         , R_RIVER_2             , F_RIVER           },
  { "frigid river"         , R_RIVER_3             , F_RIVER           },
  { "frigid river"         , R_WHITE_CLIFFS_NORTH  , F_RIVER           },
  { "frigid river"         , R_WHITE_CLIFFS_SOUTH  , F_RIVER           },
  { "frigid river"         , R_RIVER_4             , F_RIVER           },
  { "frigid river"         , R_RIVER_5             , F_RIVER           },
  { "frigid river"         , R_SHORE               , F_RIVER           },
  { "frigid river"         , R_SANDY_BEACH         , F_RIVER           },
  { "frigid river"         , R_ARAGAIN_FALLS       , F_RIVER           },
  { "frigid river"         , R_END_OF_RAINBOW      , F_RIVER           },
  { "frigid river"         , R_CANYON_BOTTOM       , F_RIVER           },
  { "frigid river"         , R_CLIFF_MIDDLE        , F_RIVER           },
  { "frigid river"         , R_CANYON_VIEW         , F_RIVER           },
  { "river"                , R_DAM_BASE            , F_RIVER           },
  { "river"                , R_RIVER_1             , F_RIVER           },
  { "river"                , R_RIVER_2             , F_RIVER           },
  { "river"                , R_RIVER_3             , F_RIVER           },
  { "river"                , R_WHITE_CLIFFS_NORTH  , F_RIVER           },
  { "river"                , R_WHITE_CLIFFS_SOUTH  , F_RIVER           },
  { "river"                , R_RIVER_4             , F_RIVER           },
  { "river"                , R_RIVER_5             , F_RIVER           },
  { "river"                , R_SHORE               , F_RIVER           },
  { "river"                , R_SANDY_BEACH         , F_RIVER           },
  { "river"                , R_ARAGAIN_FALLS       , F_RIVER           },
  { "river"                , R_END_OF_RAINBOW      , F_RIVER           },
  { "river"                , R_CANYON_BOTTOM       , F_RIVER           },
  { "river"                , R_CLIFF_MIDDLE        , F_RIVER           },
  { "river"                , R_CANYON_VIEW         , F_RIVER           },
  { "rickety ladder"       , R_LADDER_TOP          , F_LADDER          },
  { "rickety ladder"       , R_LADDER_BOTTOM       , F_LADDER          },
  { "narrow ladder"        , R_LADDER_TOP          , F_LADDER          },
  { "narrow ladder"        , R_LADDER_BOTTOM       , F_LADDER          },
  { "wooden ladder"        , R_LADDER_TOP          , F_LADDER          },
  { "wooden ladder"        , R_LADDER_BOTTOM       , F_LADDER          },
  { "ladder"               , R_LADDER_TOP          , F_LADDER          },
  { "ladder"               , R_LADDER_BOTTOM       , F_LADDER          },
  { "trap door"            , R_LIVING_ROOM         , F_TRAP_DOOR       },
  { "trap door"            , R_CELLAR              , F_TRAP_DOOR       },
  { "trap"                 , R_LIVING_ROOM         , F_TRAP_DOOR       },
  { "trap"                 , R_CELLAR              , F_TRAP_DOOR       },
  { "trap-door"            , R_LIVING_ROOM         , F_TRAP_DOOR       },
  { "trap-door"            , R_CELLAR              , F_TRAP_DOOR       },
  { "trapdoor"             , R_LIVING_ROOM         , F_TRAP_DOOR       },
  { "trapdoor"             , R_CELLAR              , F_TRAP_DOOR       },
  { "door"                 , R_LIVING_ROOM         , F_AMB             },  /* two doors in this room*/
  { "door"                 , R_CELLAR              , F_TRAP_DOOR       },
  { "stairs"               , R_KITCHEN             , F_STAIRS          },
  { "stairs"               , R_ATTIC               , F_STAIRS          },
  { "stairs"               , R_LIVING_ROOM         , F_STAIRS          },
  { "stairs"               , R_CELLAR              , F_STAIRS          },
  { "stairs"               , R_CYCLOPS_ROOM        , F_STAIRS          },
  { "stairs"               , R_TREASURE_ROOM       , F_STAIRS          },
  { "stairs"               , R_RESERVOIR_NORTH     , F_STAIRS          },
  { "stairs"               , R_SMALL_CAVE          , F_STAIRS          },
  { "stairs"               , R_TINY_CAVE           , F_STAIRS          },
  { "stairs"               , R_ATLANTIS_ROOM       , F_STAIRS          },
  { "stairs"               , R_EW_PASSAGE          , F_STAIRS          },
  { "stairs"               , R_DEEP_CANYON         , F_STAIRS          },
  { "stairs"               , R_LOUD_ROOM           , F_STAIRS          },
  { "stairs"               , R_CHASM_ROOM          , F_STAIRS          },
  { "stairs"               , R_EGYPT_ROOM          , F_STAIRS          },
  { "stairs"               , R_TORCH_ROOM          , F_STAIRS          },
  { "stairs"               , R_NORTH_TEMPLE        , F_STAIRS          },
  { "stairs"               , R_SMELLY_ROOM         , F_STAIRS          },
  { "stairs"               , R_GAS_ROOM            , F_STAIRS          },
  { "stairs"               , R_LADDER_TOP          , F_STAIRS          },
  { "staircase"            , R_KITCHEN             , F_STAIRS          },
  { "staircase"            , R_ATTIC               , F_STAIRS          },
  { "staircase"            , R_LIVING_ROOM         , F_STAIRS          },
  { "staircase"            , R_CELLAR              , F_STAIRS          },
  { "staircase"            , R_CYCLOPS_ROOM        , F_STAIRS          },
  { "staircase"            , R_TREASURE_ROOM       , F_STAIRS          },
  { "staircase"            , R_RESERVOIR_NORTH     , F_STAIRS          },
  { "staircase"            , R_SMALL_CAVE          , F_STAIRS          },
  { "staircase"            , R_TINY_CAVE           , F_STAIRS          },
  { "staircase"            , R_ATLANTIS_ROOM       , F_STAIRS          },
  { "staircase"            , R_EW_PASSAGE          , F_STAIRS          },
  { "staircase"            , R_DEEP_CANYON         , F_STAIRS          },
  { "staircase"            , R_LOUD_ROOM           , F_STAIRS          },
  { "staircase"            , R_CHASM_ROOM          , F_STAIRS          },
  { "staircase"            , R_EGYPT_ROOM          , F_STAIRS          },
  { "staircase"            , R_TORCH_ROOM          , F_STAIRS          },
  { "staircase"            , R_NORTH_TEMPLE        , F_STAIRS          },
  { "staircase"            , R_SMELLY_ROOM         , F_STAIRS          },
  { "staircase"            , R_GAS_ROOM            , F_STAIRS          },
  { "staircase"            , R_LADDER_TOP          , F_STAIRS          },
  { "stairway"             , R_KITCHEN             , F_STAIRS          },
  { "stairway"             , R_ATTIC               , F_STAIRS          },
  { "stairway"             , R_LIVING_ROOM         , F_STAIRS          },
  { "stairway"             , R_CELLAR              , F_STAIRS          },
  { "stairway"             , R_CYCLOPS_ROOM        , F_STAIRS          },
  { "stairway"             , R_TREASURE_ROOM       , F_STAIRS          },
  { "stairway"             , R_RESERVOIR_NORTH     , F_STAIRS          },
  { "stairway"             , R_SMALL_CAVE          , F_STAIRS          },
  { "stairway"             , R_TINY_CAVE           , F_STAIRS          },
  { "stairway"             , R_ATLANTIS_ROOM       , F_STAIRS          },
  { "stairway"             , R_EW_PASSAGE          , F_STAIRS          },
  { "stairway"             , R_DEEP_CANYON         , F_STAIRS          },
  { "stairway"             , R_LOUD_ROOM           , F_STAIRS          },
  { "stairway"             , R_CHASM_ROOM          , F_STAIRS          },
  { "stairway"             , R_EGYPT_ROOM          , F_STAIRS          },
  { "stairway"             , R_TORCH_ROOM          , F_STAIRS          },
  { "stairway"             , R_NORTH_TEMPLE        , F_STAIRS          },
  { "stairway"             , R_SMELLY_ROOM         , F_STAIRS          },
  { "stairway"             , R_GAS_ROOM            , F_STAIRS          },
  { "stairway"             , R_LADDER_TOP          , F_STAIRS          },
  { "mountain range"       , R_MOUNTAINS           , F_MOUNTAIN_RANGE  },
  { "range"                , R_MOUNTAINS           , F_MOUNTAIN_RANGE  },
  { "mountain"             , R_MOUNTAINS           , F_MOUNTAIN_RANGE  },
  { "mountains"            , R_MOUNTAINS           , F_MOUNTAIN_RANGE  },
  { "large bolt"           , R_DAM_ROOM            , F_BOLT            },
  { "metal bolt"           , R_DAM_ROOM            , F_BOLT            },
  { "large nut"            , R_DAM_ROOM            , F_BOLT            },
  { "metal nut"            , R_DAM_ROOM            , F_BOLT            },
  { "bolt"                 , R_DAM_ROOM            , F_BOLT            },
  { "nut"                  , R_DAM_ROOM            , F_BOLT            },
  { "small bubble"         , R_DAM_ROOM            , F_BUBBLE          },
  { "green bubble"         , R_DAM_ROOM            , F_BUBBLE          },
  { "bubble"               , R_DAM_ROOM            , F_BUBBLE          },
  { "altar"                , R_SOUTH_TEMPLE        , F_ALTAR           },
  { "yellow button"        , R_MAINTENANCE_ROOM    , F_YELLOW_BUTTON   },
  { "button"               , R_MAINTENANCE_ROOM    , F_AMB             },  /* four buttons in this room*/
  { "brown button"         , R_MAINTENANCE_ROOM    , F_BROWN_BUTTON    },
  { "button"               , R_MAINTENANCE_ROOM    , F_AMB             },  /* four buttons in this room*/
  { "red button"           , R_MAINTENANCE_ROOM    , F_RED_BUTTON      },
  { "button"               , R_MAINTENANCE_ROOM    , F_AMB             },  /* four buttons in this room*/
  { "blue button"          , R_MAINTENANCE_ROOM    , F_BLUE_BUTTON     },
  { "button"               , R_MAINTENANCE_ROOM    , F_AMB             },  /* four buttons in this room*/
  { "large carpet"         , R_LIVING_ROOM         , F_RUG             },
  { "oriental carpet"      , R_LIVING_ROOM         , F_RUG             },
  { "large rug"            , R_LIVING_ROOM         , F_RUG             },
  { "oriental rug"         , R_LIVING_ROOM         , F_RUG             },
  { "carpet"               , R_LIVING_ROOM         , F_RUG             },
  { "rug"                  , R_LIVING_ROOM         , F_RUG             },
  { "dam"                  , R_DAM_ROOM            , F_DAM             },
  { "gate"                 , R_DAM_ROOM            , F_DAM             },
  { "gates"                , R_DAM_ROOM            , F_DAM             },
  { "front door"           , R_WEST_OF_HOUSE       , F_FRONT_DOOR      },
  { "boarded door"         , R_WEST_OF_HOUSE       , F_FRONT_DOOR      },
  { "door"                 , R_WEST_OF_HOUSE       , F_FRONT_DOOR      },
  { "huge door"            , R_STONE_BARROW        , F_BARROW_DOOR     },
  { "stone door"           , R_STONE_BARROW        , F_BARROW_DOOR     },
  { "door"                 , R_STONE_BARROW        , F_BARROW_DOOR     },
  { "massive barrow"       , R_STONE_BARROW        , F_BARROW          },
  { "stone barrow"         , R_STONE_BARROW        , F_BARROW          },
  { "barrow"               , R_STONE_BARROW        , F_BARROW          },
  { "skeleton"             , R_MAZE_5              , F_BONES           },
  { "leaky pipe"           , R_MAINTENANCE_ROOM    , F_LEAK            },
  { "leak"                 , R_MAINTENANCE_ROOM    , F_LEAK            },
  { "pipe"                 , R_MAINTENANCE_ROOM    , F_LEAK            },
  { "enormous mirror"      , R_MIRROR_R_2       , F_MIRROR2         },
  { "mirror"               , R_MIRROR_R_2       , F_MIRROR2         },
  { "reflection"           , R_MIRROR_R_2       , F_MIRROR2         },
  { "enormous mirror"      , R_MIRROR_R_1       , F_MIRROR1         },
  { "mirror"               , R_MIRROR_R_1       , F_MIRROR1         },
  { "reflection"           , R_MIRROR_R_1       , F_MIRROR1         },
  { "ancient inscription"  , R_NORTH_TEMPLE        , F_PRAYER          },
  { "ancient prayer"       , R_NORTH_TEMPLE        , F_PRAYER          },
  { "inscription"          , R_NORTH_TEMPLE        , F_PRAYER          },
  { "prayer"               , R_NORTH_TEMPLE        , F_PRAYER          },
  { "wooden railing"       , R_DOME_ROOM           , F_RAILING         },
  { "wooden rail"          , R_DOME_ROOM           , F_RAILING         },
  { "railing"              , R_DOME_ROOM           , F_RAILING         },
  { "rail"                 , R_DOME_ROOM           , F_RAILING         },
  { "sand"                 , R_SANDY_CAVE          , F_SAND            },
  { "switch"               , R_MACHINE_ROOM        , F_MACHINE_SWITCH  },
  { "wooden door"          , R_LIVING_ROOM         , F_WOODEN_DOOR     },
  { "gothic lettering"     , R_LIVING_ROOM         , F_WOODEN_DOOR     },
  { "lettering"            , R_LIVING_ROOM         , F_WOODEN_DOOR     },
  { "door"                 , R_LIVING_ROOM         , F_AMB             },  /* two doors in this room*/
  { "white pedestal"       , R_TORCH_ROOM          , F_PEDESTAL        },
  { "marble pedestal"      , R_TORCH_ROOM          , F_PEDESTAL        },
  { "pedestal"             , R_TORCH_ROOM          , F_PEDESTAL        },
  { "control panel"        , R_DAM_ROOM            , F_CONTROL_PANEL   },
  { "panel"                , R_DAM_ROOM            , F_CONTROL_PANEL   },
  { "nails"                , R_LIVING_ROOM         , F_NAILS           },
  { "nail"                 , R_LIVING_ROOM         , F_NAILS           },
  { "granite wall"         , R_TREASURE_ROOM       , F_GRANITE_WALL    },
  { "granite wall"         , R_NORTH_TEMPLE        , F_GRANITE_WALL    },
  { "granite wall"         , R_SLIDE_ROOM          , F_GRANITE_WALL    },
  { "iron chain"           , R_SHAFT_ROOM          , F_CHAIN           },
  { "chain"                , R_SHAFT_ROOM          , F_CHAIN           },
  { "iron chain"           , R_LOWER_SHAFT         , F_CHAIN           },
  { "chain"                , R_LOWER_SHAFT         , F_CHAIN           },
  { "gate"                 , R_ENTRANCE_TO_HADES   , F_GATE            },
  { "gateway"              , R_ENTRANCE_TO_HADES   , F_GATE            },
  { "door"                 , R_STUDIO              , F_STUDIO_DOOR     },
  { "paint"                , R_STUDIO              , F_STUDIO_DOOR     },
  { "chasm"                , R_EAST_OF_CHASM       , F_CHASM           },
  { "chasm"                , R_RESERVOIR_SOUTH     , F_CHASM           },
  { "chasm"                , R_CHASM_ROOM          , F_CHASM           },
  { "lake"                 , R_RESERVOIR_SOUTH     , F_LAKE            },
  { "lake"                 , R_RESERVOIR_NORTH     , F_LAKE            },
  { "stream"               , R_RESERVOIR           , F_STREAM          },
  { "stream"               , R_STREAM_VIEW         , F_STREAM          },
  { "stream"               , R_IN_STREAM           , F_STREAM          },
  { "gas"                  , R_SMELLY_ROOM         , F_GAS             },
  { "gas"                  , R_GAS_ROOM            , F_GAS             },
  { "odor"                 , R_SMELLY_ROOM         , F_GAS             },
  { "odor"                 , R_GAS_ROOM            , F_GAS             },

  {0, 0, 0}
};

