c -v -c opbss.c
c -v -c opdata.c
c -v -c opctype1.c
c -v -c -o optim1b.c
c -v -c -o optim1c.c
c -v -c -o optim1d.c
c -v -c -o op21a.c
c -v -c -o op21b.c
c -v -c -o op21c.c
c -v -c -o op21d.c
c -v -c -o op31a.c
c -v -c -o op31b.c
c -v -c -o op31c.c
c -v -c -o op31d.c
c -v -c -o op41a.c
c -v -c -o op41b.c
c -v -c -o opbase.c
z80as -j oplibc
z80as opcrtcpm
z80as odynm512
z80as opov1red
z80as opov2red
z80as opover
c -v -c -o optop.c
